In [2]:
# Cell 1: Fine-tune MiniLM on Fault Descriptions and extract fine-tuned embeddings

import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel, AdamW
from tqdm import tqdm

# Load data
# df = pd.read_excel("fault-logs-o-ran-12k.xlsx", engine="openpyxl")
df = pd.read_excel("fault-logs-o-ran-64.xls")

fault_texts = df["Fault Description"].fillna("").astype(str).tolist()


# Load MiniLM tokenizer and model
model_name = "sentence-transformers/all-MiniLM-L6-v2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

# Custom dataset
class FaultDataset(Dataset):
    def __init__(self, texts):
        self.texts = texts

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoded = tokenizer(self.texts[idx], padding="max_length", truncation=True, max_length=64, return_tensors="pt")
        return {key: val.squeeze(0) for key, val in encoded.items()}

# DataLoader
dataset = FaultDataset(fault_texts)
loader = DataLoader(dataset, batch_size=16, shuffle=False)

# Optimizer
optimizer = AdamW(model.parameters(), lr=2e-5)

# Fine-tune MiniLM (light fine-tuning)
model.train()
for epoch in range(1):  # Keep it low to avoid overfitting
    for batch in tqdm(loader, desc="Fine-tuning MiniLM"):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        sentence_embeddings = outputs.last_hidden_state[:, 0, :]  # [CLS] token

        # Self-supervised dummy objective (contrastive not implemented here for simplicity)
        loss = sentence_embeddings.norm(p=2, dim=1).mean()  # L2 regularization proxy
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

# Re-extract embeddings using fine-tuned MiniLM
model.eval()
all_embeddings = []

with torch.no_grad():
    for batch in tqdm(loader, desc="Extracting Fine-tuned Embeddings"):
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        embeddings = outputs.last_hidden_state[:, 0, :]
        all_embeddings.append(embeddings.cpu())

final_embeddings = torch.cat(all_embeddings, dim=0)
print(f"Final Embedding Shape: {final_embeddings.shape}")  # Shape: [num_samples, hidden_dim]

/home/iiitb/rag-env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/iiitb/rag-env/lib/python3.11/site-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Fine-tuning MiniLM: 100%|█████████████████████████| 4/4 [00:00<00:00,  6.10it/s]
Extracting Fine-tuned Embeddings: 100%|███████████| 4/4 [00:00<00:00, 54.99it/s]

Final Embedding Shape: torch.Size([64, 384])

In [19]:
import torch
import torch.nn as nn

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Number of generators
num_generators = 30

# Generator
class Generator(nn.Module):
    def __init__(self, latent_dim=100, output_dim=384):
        super(Generator, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.ReLU(True),
            nn.Linear(256, 256),
            nn.ReLU(True),
            nn.Linear(256, 256),
            nn.ReLU(True),
            nn.Linear(256, output_dim),
        )

    def forward(self, z):
        return self.model(z)

# Create generators
generators = [
    Generator(latent_dim=100, output_dim=384).to(device)
    for _ in range(num_generators)
]

# MAD-GAN Discriminator
class MADDiscriminator(nn.Module):
    def __init__(self, input_dim=384, num_generators=30):
        super(MADDiscriminator, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, 256),
            nn.LeakyReLU(0.2),
            nn.Linear(256, num_generators + 1),
        )
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        logits = self.net(x)
        return self.softmax(logits)

# Create discriminator
discriminator = MADDiscriminator(
    input_dim=384,
    num_generators=num_generators
).to(device)

In [20]:
import torch.nn.functional as F

# Hyperparameters
latent_dim = 100
hidden_dim = final_embeddings.shape[1]  # 384
batch_size = 64
num_epochs = 500
lr = 1e-4
K = 30  # Number of generators

# Create multiple generators
generators = [Generator(latent_dim, hidden_dim).to(device) for _ in range(K)]
D = MADDiscriminator(input_dim=hidden_dim, num_generators=K).to(device)

# Optimizers
opt_G = [torch.optim.Adam(G.parameters(), lr=lr) for G in generators]
opt_D = torch.optim.Adam(D.parameters(), lr=lr)

# Loss function
ce_loss = nn.CrossEntropyLoss()
mse_loss = nn.MSELoss()

# Dataset and loader
real_dataset = torch.utils.data.TensorDataset(final_embeddings)
real_loader = torch.utils.data.DataLoader(real_dataset, batch_size=batch_size, shuffle=True)

# Training loop
for epoch in range(num_epochs):
    for x_batch, in real_loader:
        x_batch = x_batch.to(device)
        bsz = x_batch.size(0)

        # ============================
        # 1. Train Discriminator
        # ============================

        # Real data → label 0
        real_labels = torch.zeros(bsz, dtype=torch.long).to(device)  # class 0 = real
        real_preds = D(x_batch)  # shape: [bsz, K+1]
        loss_real = ce_loss(real_preds, real_labels)

        # Fake data from all generators → label j ∈ [1..K]
        fake_data = []
        fake_labels = []
        for j, G in enumerate(generators):
            z = torch.randn(bsz, latent_dim).to(device)
            x_fake = G(z).detach()
            fake_preds = D(x_fake)  # shape: [bsz, K+1]
            labels = torch.full((bsz,), j + 1, dtype=torch.long).to(device)  # class j+1 = G_j
            loss_fake = ce_loss(fake_preds, labels)
            fake_data.append((x_fake, labels, loss_fake))

        # Combine all losses
        loss_D = loss_real + sum(lf for _, _, lf in fake_data)

        opt_D.zero_grad()
        loss_D.backward()
        opt_D.step()

        # ============================
        # 2. Train each Generator
        # ============================

        loss_G_total = 0.0
        loss_MSE_total = 0.0

        for j, G in enumerate(generators):
            z = torch.randn(bsz, latent_dim).to(device)
            x_fake = G(z)
            preds = D(x_fake)
            target_class = torch.zeros(bsz, dtype=torch.long).to(device)  # Wants to be seen as "real" (class 0)

            loss_G = ce_loss(preds, target_class)

            # Optional MSE term (to guide towards data manifold)
            idx = torch.randint(0, final_embeddings.size(0), (bsz,))
            x_real_ref = final_embeddings[idx].to(device)
            loss_MSE = mse_loss(x_fake, x_real_ref)

            total_loss = loss_G + loss_MSE
            opt_G[j].zero_grad()
            total_loss.backward()
            opt_G[j].step()

            loss_G_total += loss_G.item()
            loss_MSE_total += loss_MSE.item()

    print(f"Epoch {epoch+1} | D Loss: {loss_D.item():.4f} | Avg G Loss: {loss_G_total/K:.4f} | Avg MSE: {loss_MSE_total/K:.4f}")

# Save all generators and discriminator
for j, G in enumerate(generators):
    torch.save(G.state_dict(), f"trained_generator_{j+1}.pt")

torch.save(D.state_dict(), "trained_discriminator.pt")

Epoch 1 | D Loss: 106.4529 | Avg G Loss: 3.4320 | Avg MSE: 0.1059
Epoch 2 | D Loss: 106.4514 | Avg G Loss: 3.4319 | Avg MSE: 0.1056
Epoch 3 | D Loss: 106.4502 | Avg G Loss: 3.4319 | Avg MSE: 0.1047
Epoch 4 | D Loss: 106.4489 | Avg G Loss: 3.4318 | Avg MSE: 0.1039
Epoch 5 | D Loss: 106.4474 | Avg G Loss: 3.4318 | Avg MSE: 0.1032
Epoch 6 | D Loss: 106.4462 | Avg G Loss: 3.4317 | Avg MSE: 0.1022
Epoch 7 | D Loss: 106.4450 | Avg G Loss: 3.4317 | Avg MSE: 0.1022
Epoch 8 | D Loss: 106.4438 | Avg G Loss: 3.4316 | Avg MSE: 0.1018
Epoch 9 | D Loss: 106.4425 | Avg G Loss: 3.4315 | Avg MSE: 0.1002
Epoch 10 | D Loss: 106.4411 | Avg G Loss: 3.4315 | Avg MSE: 0.1000
Epoch 11 | D Loss: 106.4401 | Avg G Loss: 3.4314 | Avg MSE: 0.0994
Epoch 12 | D Loss: 106.4388 | Avg G Loss: 3.4313 | Avg MSE: 0.0986
Epoch 13 | D Loss: 106.4374 | Avg G Loss: 3.4312 | Avg MSE: 0.0979
Epoch 14 | D Loss: 106.4361 | Avg G Loss: 3.4311 | Avg MSE: 0.0969
Epoch 15 | D Loss: 106.4347 | Avg G Loss: 3.4310 | Avg MSE: 0.0968
Epoch 16 | D Loss: 106.4333 | Avg G Loss: 3.4308 | Avg MSE: 0.0963
Epoch 17 | D Loss: 106.4320 | Avg G Loss: 3.4307 | Avg MSE: 0.0956
Epoch 18 | D Loss: 106.4307 | Avg G Loss: 3.4306 | Avg MSE: 0.0950
Epoch 19 | D Loss: 106.4291 | Avg G Loss: 3.4304 | Avg MSE: 0.0941
Epoch 20 | D Loss: 106.4277 | Avg G Loss: 3.4302 | Avg MSE: 0.0933
Epoch 21 | D Loss: 106.4261 | Avg G Loss: 3.4300 | Avg MSE: 0.0929
Epoch 22 | D Loss: 106.4245 | Avg G Loss: 3.4298 | Avg MSE: 0.0916
Epoch 23 | D Loss: 106.4229 | Avg G Loss: 3.4295 | Avg MSE: 0.0906
Epoch 24 | D Loss: 106.4212 | Avg G Loss: 3.4293 | Avg MSE: 0.0897
Epoch 25 | D Loss: 106.4194 | Avg G Loss: 3.4289 | Avg MSE: 0.0889
Epoch 26 | D Loss: 106.4176 | Avg G Loss: 3.4286 | Avg MSE: 0.0881
Epoch 27 | D Loss: 106.4158 | Avg G Loss: 3.4282 | Avg MSE: 0.0876
Epoch 28 | D Loss: 106.4139 | Avg G Loss: 3.4277 | Avg MSE: 0.0869
Epoch 29 | D Loss: 106.4121 | Avg G Loss: 3.4272 | Avg MSE: 0.0853
Epoch 30 | D Loss: 106.4100 | Avg G Loss: 3.4267 | Avg MSE: 0.0848
Epoch 31 | D Loss: 106.4081 | Avg G Loss: 3.4260 | Avg MSE: 0.0836
Epoch 32 | D Loss: 106.4057 | Avg G Loss: 3.4253 | Avg MSE: 0.0824
Epoch 33 | D Loss: 106.4036 | Avg G Loss: 3.4245 | Avg MSE: 0.0822
Epoch 34 | D Loss: 106.4016 | Avg G Loss: 3.4236 | Avg MSE: 0.0811
Epoch 35 | D Loss: 106.3995 | Avg G Loss: 3.4225 | Avg MSE: 0.0797
Epoch 36 | D Loss: 106.3974 | Avg G Loss: 3.4213 | Avg MSE: 0.0789
Epoch 37 | D Loss: 106.3949 | Avg G Loss: 3.4200 | Avg MSE: 0.0784
Epoch 38 | D Loss: 106.3925 | Avg G Loss: 3.4186 | Avg MSE: 0.0770
Epoch 39 | D Loss: 106.3904 | Avg G Loss: 3.4168 | Avg MSE: 0.0766
Epoch 40 | D Loss: 106.3886 | Avg G Loss: 3.4151 | Avg MSE: 0.0743
Epoch 41 | D Loss: 106.3861 | Avg G Loss: 3.4130 | Avg MSE: 0.0741
Epoch 42 | D Loss: 106.3841 | Avg G Loss: 3.4106 | Avg MSE: 0.0734
Epoch 43 | D Loss: 106.3818 | Avg G Loss: 3.4081 | Avg MSE: 0.0726
Epoch 44 | D Loss: 106.3805 | Avg G Loss: 3.4054 | Avg MSE: 0.0728
Epoch 45 | D Loss: 106.3789 | Avg G Loss: 3.4021 | Avg MSE: 0.0718
Epoch 46 | D Loss: 106.3780 | Avg G Loss: 3.3988 | Avg MSE: 0.0717
Epoch 47 | D Loss: 106.3768 | Avg G Loss: 3.3951 | Avg MSE: 0.0713
Epoch 48 | D Loss: 106.3764 | Avg G Loss: 3.3914 | Avg MSE: 0.0712
Epoch 49 | D Loss: 106.3763 | Avg G Loss: 3.3878 | Avg MSE: 0.0718
Epoch 50 | D Loss: 106.3773 | Avg G Loss: 3.3843 | Avg MSE: 0.0722
Epoch 51 | D Loss: 106.3776 | Avg G Loss: 3.3801 | Avg MSE: 0.0726
Epoch 52 | D Loss: 106.3786 | Avg G Loss: 3.3765 | Avg MSE: 0.0735
Epoch 53 | D Loss: 106.3794 | Avg G Loss: 3.3737 | Avg MSE: 0.0750
Epoch 54 | D Loss: 106.3809 | Avg G Loss: 3.3714 | Avg MSE: 0.0754
Epoch 55 | D Loss: 106.3825 | Avg G Loss: 3.3696 | Avg MSE: 0.0772
Epoch 56 | D Loss: 106.3821 | Avg G Loss: 3.3683 | Avg MSE: 0.0787
Epoch 57 | D Loss: 106.3825 | Avg G Loss: 3.3689 | Avg MSE: 0.0800
Epoch 58 | D Loss: 106.3831 | Avg G Loss: 3.3699 | Avg MSE: 0.0820
Epoch 59 | D Loss: 106.3823 | Avg G Loss: 3.3713 | Avg MSE: 0.0827
Epoch 60 | D Loss: 106.3810 | Avg G Loss: 3.3743 | Avg MSE: 0.0835
Epoch 61 | D Loss: 106.3793 | Avg G Loss: 3.3775 | Avg MSE: 0.0839
Epoch 62 | D Loss: 106.3782 | Avg G Loss: 3.3811 | Avg MSE: 0.0829
Epoch 63 | D Loss: 106.3764 | Avg G Loss: 3.3840 | Avg MSE: 0.0834
Epoch 64 | D Loss: 106.3747 | Avg G Loss: 3.3877 | Avg MSE: 0.0814
Epoch 65 | D Loss: 106.3738 | Avg G Loss: 3.3907 | Avg MSE: 0.0804
Epoch 66 | D Loss: 106.3719 | Avg G Loss: 3.3936 | Avg MSE: 0.0774
Epoch 67 | D Loss: 106.3714 | Avg G Loss: 3.3959 | Avg MSE: 0.0760
Epoch 68 | D Loss: 106.3713 | Avg G Loss: 3.3981 | Avg MSE: 0.0734
Epoch 69 | D Loss: 106.3716 | Avg G Loss: 3.3999 | Avg MSE: 0.0711
Epoch 70 | D Loss: 106.3712 | Avg G Loss: 3.4012 | Avg MSE: 0.0685
Epoch 71 | D Loss: 106.3717 | Avg G Loss: 3.4023 | Avg MSE: 0.0660
Epoch 72 | D Loss: 106.3732 | Avg G Loss: 3.4026 | Avg MSE: 0.0640
Epoch 73 | D Loss: 106.3737 | Avg G Loss: 3.4029 | Avg MSE: 0.0616
Epoch 74 | D Loss: 106.3747 | Avg G Loss: 3.4027 | Avg MSE: 0.0592
Epoch 75 | D Loss: 106.3760 | Avg G Loss: 3.4026 | Avg MSE: 0.0578
Epoch 76 | D Loss: 106.3772 | Avg G Loss: 3.4020 | Avg MSE: 0.0565
Epoch 77 | D Loss: 106.3797 | Avg G Loss: 3.4013 | Avg MSE: 0.0547
Epoch 78 | D Loss: 106.3813 | Avg G Loss: 3.4001 | Avg MSE: 0.0530
Epoch 79 | D Loss: 106.3830 | Avg G Loss: 3.3994 | Avg MSE: 0.0516
Epoch 80 | D Loss: 106.3857 | Avg G Loss: 3.3979 | Avg MSE: 0.0510
Epoch 81 | D Loss: 106.3871 | Avg G Loss: 3.3966 | Avg MSE: 0.0497
Epoch 82 | D Loss: 106.3898 | Avg G Loss: 3.3949 | Avg MSE: 0.0491
Epoch 83 | D Loss: 106.3921 | Avg G Loss: 3.3934 | Avg MSE: 0.0481
Epoch 84 | D Loss: 106.3951 | Avg G Loss: 3.3916 | Avg MSE: 0.0475
Epoch 85 | D Loss: 106.3972 | Avg G Loss: 3.3898 | Avg MSE: 0.0473
Epoch 86 | D Loss: 106.4002 | Avg G Loss: 3.3879 | Avg MSE: 0.0465
Epoch 87 | D Loss: 106.4022 | Avg G Loss: 3.3860 | Avg MSE: 0.0468
Epoch 88 | D Loss: 106.4053 | Avg G Loss: 3.3840 | Avg MSE: 0.0460
Epoch 89 | D Loss: 106.4082 | Avg G Loss: 3.3818 | Avg MSE: 0.0462
Epoch 90 | D Loss: 106.4120 | Avg G Loss: 3.3800 | Avg MSE: 0.0457
Epoch 91 | D Loss: 106.4144 | Avg G Loss: 3.3776 | Avg MSE: 0.0463
Epoch 92 | D Loss: 106.4184 | Avg G Loss: 3.3759 | Avg MSE: 0.0458
Epoch 93 | D Loss: 106.4227 | Avg G Loss: 3.3735 | Avg MSE: 0.0461
Epoch 94 | D Loss: 106.4260 | Avg G Loss: 3.3715 | Avg MSE: 0.0462
Epoch 95 | D Loss: 106.4305 | Avg G Loss: 3.3698 | Avg MSE: 0.0468
Epoch 96 | D Loss: 106.4337 | Avg G Loss: 3.3686 | Avg MSE: 0.0474
Epoch 97 | D Loss: 106.4366 | Avg G Loss: 3.3677 | Avg MSE: 0.0477
Epoch 98 | D Loss: 106.4409 | Avg G Loss: 3.3665 | Avg MSE: 0.0484
Epoch 99 | D Loss: 106.4428 | Avg G Loss: 3.3655 | Avg MSE: 0.0494
Epoch 100 | D Loss: 106.4465 | Avg G Loss: 3.3658 | Avg MSE: 0.0503
Epoch 101 | D Loss: 106.4493 | Avg G Loss: 3.3658 | Avg MSE: 0.0513
Epoch 102 | D Loss: 106.4495 | Avg G Loss: 3.3663 | Avg MSE: 0.0516
Epoch 103 | D Loss: 106.4519 | Avg G Loss: 3.3678 | Avg MSE: 0.0524
Epoch 104 | D Loss: 106.4539 | Avg G Loss: 3.3692 | Avg MSE: 0.0525
Epoch 105 | D Loss: 106.4561 | Avg G Loss: 3.3704 | Avg MSE: 0.0531
Epoch 106 | D Loss: 106.4573 | Avg G Loss: 3.3729 | Avg MSE: 0.0523
Epoch 107 | D Loss: 106.4573 | Avg G Loss: 3.3745 | Avg MSE: 0.0537
Epoch 108 | D Loss: 106.4584 | Avg G Loss: 3.3772 | Avg MSE: 0.0528
Epoch 109 | D Loss: 106.4601 | Avg G Loss: 3.3795 | Avg MSE: 0.0529
Epoch 110 | D Loss: 106.4616 | Avg G Loss: 3.3823 | Avg MSE: 0.0513
Epoch 111 | D Loss: 106.4605 | Avg G Loss: 3.3846 | Avg MSE: 0.0510
Epoch 112 | D Loss: 106.4605 | Avg G Loss: 3.3869 | Avg MSE: 0.0502
Epoch 113 | D Loss: 106.4621 | Avg G Loss: 3.3893 | Avg MSE: 0.0495
Epoch 114 | D Loss: 106.4638 | Avg G Loss: 3.3915 | Avg MSE: 0.0474
Epoch 115 | D Loss: 106.4648 | Avg G Loss: 3.3935 | Avg MSE: 0.0472
Epoch 116 | D Loss: 106.4653 | Avg G Loss: 3.3957 | Avg MSE: 0.0453
Epoch 117 | D Loss: 106.4673 | Avg G Loss: 3.3977 | Avg MSE: 0.0443
Epoch 118 | D Loss: 106.4677 | Avg G Loss: 3.3994 | Avg MSE: 0.0432
Epoch 119 | D Loss: 106.4696 | Avg G Loss: 3.4011 | Avg MSE: 0.0421
Epoch 120 | D Loss: 106.4698 | Avg G Loss: 3.4028 | Avg MSE: 0.0398
Epoch 121 | D Loss: 106.4703 | Avg G Loss: 3.4044 | Avg MSE: 0.0391
Epoch 122 | D Loss: 106.4707 | Avg G Loss: 3.4058 | Avg MSE: 0.0376
Epoch 123 | D Loss: 106.4708 | Avg G Loss: 3.4073 | Avg MSE: 0.0366

Epoch 124 | D Loss: 106.4709 | Avg G Loss: 3.4086 | Avg MSE: 0.0360
Epoch 125 | D Loss: 106.4706 | Avg G Loss: 3.4099 | Avg MSE: 0.0347
Epoch 126 | D Loss: 106.4717 | Avg G Loss: 3.4111 | Avg MSE: 0.0343
Epoch 127 | D Loss: 106.4715 | Avg G Loss: 3.4122 | Avg MSE: 0.0330
Epoch 128 | D Loss: 106.4712 | Avg G Loss: 3.4134 | Avg MSE: 0.0325
Epoch 129 | D Loss: 106.4711 | Avg G Loss: 3.4145 | Avg MSE: 0.0317
Epoch 130 | D Loss: 106.4708 | Avg G Loss: 3.4154 | Avg MSE: 0.0310
Epoch 131 | D Loss: 106.4708 | Avg G Loss: 3.4163 | Avg MSE: 0.0306
Epoch 132 | D Loss: 106.4693 | Avg G Loss: 3.4172 | Avg MSE: 0.0299
Epoch 133 | D Loss: 106.4682 | Avg G Loss: 3.4181 | Avg MSE: 0.0293
Epoch 134 | D Loss: 106.4687 | Avg G Loss: 3.4189 | Avg MSE: 0.0296
Epoch 135 | D Loss: 106.4689 | Avg G Loss: 3.4196 | Avg MSE: 0.0284
Epoch 136 | D Loss: 106.4680 | Avg G Loss: 3.4203 | Avg MSE: 0.0280
Epoch 137 | D Loss: 106.4667 | Avg G Loss: 3.4210 | Avg MSE: 0.0276
Epoch 138 | D Loss: 106.4673 | Avg G Loss: 3.4216 | Avg MSE: 0.0269
Epoch 139 | D Loss: 106.4660 | Avg G Loss: 3.4222 | Avg MSE: 0.0261
Epoch 140 | D Loss: 106.4656 | Avg G Loss: 3.4228 | Avg MSE: 0.0259
Epoch 141 | D Loss: 106.4653 | Avg G Loss: 3.4232 | Avg MSE: 0.0255
Epoch 142 | D Loss: 106.4647 | Avg G Loss: 3.4237 | Avg MSE: 0.0256
Epoch 143 | D Loss: 106.4633 | Avg G Loss: 3.4241 | Avg MSE: 0.0253
Epoch 144 | D Loss: 106.4637 | Avg G Loss: 3.4245 | Avg MSE: 0.0248
Epoch 145 | D Loss: 106.4635 | Avg G Loss: 3.4249 | Avg MSE: 0.0249
Epoch 146 | D Loss: 106.4623 | Avg G Loss: 3.4252 | Avg MSE: 0.0244
Epoch 147 | D Loss: 106.4625 | Avg G Loss: 3.4255 | Avg MSE: 0.0246
Epoch 148 | D Loss: 106.4617 | Avg G Loss: 3.4258 | Avg MSE: 0.0241
Epoch 149 | D Loss: 106.4607 | Avg G Loss: 3.4261 | Avg MSE: 0.0236
Epoch 150 | D Loss: 106.4608 | Avg G Loss: 3.4264 | Avg MSE: 0.0236
Epoch 151 | D Loss: 106.4608 | Avg G Loss: 3.4266 | Avg MSE: 0.0242
Epoch 152 | D Loss: 106.4594 | Avg G Loss: 3.4268 | Avg MSE: 0.0232
Epoch 153 | D Loss: 106.4592 | Avg G Loss: 3.4271 | Avg MSE: 0.0232
Epoch 154 | D Loss: 106.4596 | Avg G Loss: 3.4273 | Avg MSE: 0.0229
Epoch 155 | D Loss: 106.4592 | Avg G Loss: 3.4274 | Avg MSE: 0.0227
Epoch 156 | D Loss: 106.4592 | Avg G Loss: 3.4276 | Avg MSE: 0.0230
Epoch 157 | D Loss: 106.4584 | Avg G Loss: 3.4277 | Avg MSE: 0.0231
Epoch 158 | D Loss: 106.4582 | Avg G Loss: 3.4279 | Avg MSE: 0.0231
Epoch 159 | D Loss: 106.4577 | Avg G Loss: 3.4280 | Avg MSE: 0.0226
Epoch 160 | D Loss: 106.4580 | Avg G Loss: 3.4281 | Avg MSE: 0.0228
Epoch 161 | D Loss: 106.4581 | Avg G Loss: 3.4282 | Avg MSE: 0.0227
Epoch 162 | D Loss: 106.4573 | Avg G Loss: 3.4283 | Avg MSE: 0.0227
Epoch 163 | D Loss: 106.4571 | Avg G Loss: 3.4284 | Avg MSE: 0.0224
Epoch 164 | D Loss: 106.4573 | Avg G Loss: 3.4285 | Avg MSE: 0.0229
Epoch 165 | D Loss: 106.4570 | Avg G Loss: 3.4286 | Avg MSE: 0.0221
Epoch 166 | D Loss: 106.4569 | Avg G Loss: 3.4286 | Avg MSE: 0.0228
Epoch 167 | D Loss: 106.4568 | Avg G Loss: 3.4287 | Avg MSE: 0.0228
Epoch 168 | D Loss: 106.4564 | Avg G Loss: 3.4288 | Avg MSE: 0.0221
Epoch 169 | D Loss: 106.4569 | Avg G Loss: 3.4288 | Avg MSE: 0.0220
Epoch 170 | D Loss: 106.4561 | Avg G Loss: 3.4289 | Avg MSE: 0.0218
Epoch 171 | D Loss: 106.4565 | Avg G Loss: 3.4290 | Avg MSE: 0.0228
Epoch 172 | D Loss: 106.4564 | Avg G Loss: 3.4290 | Avg MSE: 0.0216
Epoch 173 | D Loss: 106.4558 | Avg G Loss: 3.4290 | Avg MSE: 0.0225
Epoch 174 | D Loss: 106.4559 | Avg G Loss: 3.4291 | Avg MSE: 0.0221
Epoch 175 | D Loss: 106.4555 | Avg G Loss: 3.4291 | Avg MSE: 0.0219
Epoch 176 | D Loss: 106.4557 | Avg G Loss: 3.4292 | Avg MSE: 0.0217
Epoch 177 | D Loss: 106.4550 | Avg G Loss: 3.4292 | Avg MSE: 0.0221
Epoch 178 | D Loss: 106.4552 | Avg G Loss: 3.4292 | Avg MSE: 0.0222
Epoch 179 | D Loss: 106.4552 | Avg G Loss: 3.4292 | Avg MSE: 0.0219
Epoch 180 | D Loss: 106.4555 | Avg G Loss: 3.4293 | Avg MSE: 0.0220
Epoch 181 | D Loss: 106.4549 | Avg G Loss: 3.4293 | Avg MSE: 0.0218
Epoch 182 | D Loss: 106.4548 | Avg G Loss: 3.4293 | Avg MSE: 0.0225
Epoch 183 | D Loss: 106.4545 | Avg G Loss: 3.4293 | Avg MSE: 0.0220
Epoch 184 | D Loss: 106.4544 | Avg G Loss: 3.4294 | Avg MSE: 0.0221
Epoch 185 | D Loss: 106.4541 | Avg G Loss: 3.4294 | Avg MSE: 0.0215
Epoch 186 | D Loss: 106.4541 | Avg G Loss: 3.4294 | Avg MSE: 0.0218
Epoch 187 | D Loss: 106.4544 | Avg G Loss: 3.4294 | Avg MSE: 0.0220
Epoch 188 | D Loss: 106.4537 | Avg G Loss: 3.4294 | Avg MSE: 0.0219
Epoch 189 | D Loss: 106.4542 | Avg G Loss: 3.4294 | Avg MSE: 0.0217
Epoch 190 | D Loss: 106.4539 | Avg G Loss: 3.4295 | Avg MSE: 0.0222
Epoch 191 | D Loss: 106.4541 | Avg G Loss: 3.4295 | Avg MSE: 0.0221
Epoch 192 | D Loss: 106.4538 | Avg G Loss: 3.4295 | Avg MSE: 0.0216
Epoch 193 | D Loss: 106.4539 | Avg G Loss: 3.4295 | Avg MSE: 0.0220
Epoch 194 | D Loss: 106.4538 | Avg G Loss: 3.4295 | Avg MSE: 0.0214
Epoch 195 | D Loss: 106.4531 | Avg G Loss: 3.4296 | Avg MSE: 0.0214
Epoch 196 | D Loss: 106.4538 | Avg G Loss: 3.4296 | Avg MSE: 0.0222
Epoch 197 | D Loss: 106.4533 | Avg G Loss: 3.4296 | Avg MSE: 0.0218
Epoch 198 | D Loss: 106.4537 | Avg G Loss: 3.4296 | Avg MSE: 0.0217
Epoch 199 | D Loss: 106.4533 | Avg G Loss: 3.4296 | Avg MSE: 0.0222
Epoch 200 | D Loss: 106.4532 | Avg G Loss: 3.4296 | Avg MSE: 0.0219
Epoch 201 | D Loss: 106.4538 | Avg G Loss: 3.4296 | Avg MSE: 0.0223
Epoch 202 | D Loss: 106.4536 | Avg G Loss: 3.4296 | Avg MSE: 0.0213
Epoch 203 | D Loss: 106.4544 | Avg G Loss: 3.4296 | Avg MSE: 0.0219
Epoch 204 | D Loss: 106.4537 | Avg G Loss: 3.4296 | Avg MSE: 0.0219
Epoch 205 | D Loss: 106.4539 | Avg G Loss: 3.4296 | Avg MSE: 0.0216
Epoch 206 | D Loss: 106.4534 | Avg G Loss: 3.4296 | Avg MSE: 0.0219
Epoch 207 | D Loss: 106.4544 | Avg G Loss: 3.4296 | Avg MSE: 0.0217
Epoch 208 | D Loss: 106.4536 | Avg G Loss: 3.4296 | Avg MSE: 0.0217
Epoch 209 | D Loss: 106.4543 | Avg G Loss: 3.4296 | Avg MSE: 0.0218
Epoch 210 | D Loss: 106.4541 | Avg G Loss: 3.4297 | Avg MSE: 0.0219
Epoch 211 | D Loss: 106.4548 | Avg G Loss: 3.4297 | Avg MSE: 0.0217
Epoch 212 | D Loss: 106.4543 | Avg G Loss: 3.4297 | Avg MSE: 0.0219
Epoch 213 | D Loss: 106.4546 | Avg G Loss: 3.4297 | Avg MSE: 0.0212
Epoch 214 | D Loss: 106.4546 | Avg G Loss: 3.4297 | Avg MSE: 0.0212
Epoch 215 | D Loss: 106.4549 | Avg G Loss: 3.4297 | Avg MSE: 0.0217
Epoch 216 | D Loss: 106.4546 | Avg G Loss: 3.4298 | Avg MSE: 0.0214
Epoch 217 | D Loss: 106.4543 | Avg G Loss: 3.4298 | Avg MSE: 0.0215
Epoch 218 | D Loss: 106.4541 | Avg G Loss: 3.4298 | Avg MSE: 0.0219
Epoch 219 | D Loss: 106.4540 | Avg G Loss: 3.4298 | Avg MSE: 0.0221
Epoch 220 | D Loss: 106.4540 | Avg G Loss: 3.4298 | Avg MSE: 0.0217
Epoch 221 | D Loss: 106.4543 | Avg G Loss: 3.4298 | Avg MSE: 0.0223
Epoch 222 | D Loss: 106.4546 | Avg G Loss: 3.4298 | Avg MSE: 0.0219
Epoch 223 | D Loss: 106.4542 | Avg G Loss: 3.4298 | Avg MSE: 0.0219
Epoch 224 | D Loss: 106.4542 | Avg G Loss: 3.4298 | Avg MSE: 0.0217
Epoch 225 | D Loss: 106.4536 | Avg G Loss: 3.4299 | Avg MSE: 0.0217
Epoch 226 | D Loss: 106.4538 | Avg G Loss: 3.4299 | Avg MSE: 0.0218
Epoch 227 | D Loss: 106.4529 | Avg G Loss: 3.4299 | Avg MSE: 0.0219
Epoch 228 | D Loss: 106.4532 | Avg G Loss: 3.4299 | Avg MSE: 0.0218
Epoch 229 | D Loss: 106.4535 | Avg G Loss: 3.4299 | Avg MSE: 0.0215
Epoch 230 | D Loss: 106.4531 | Avg G Loss: 3.4299 | Avg MSE: 0.0222
Epoch 231 | D Loss: 106.4531 | Avg G Loss: 3.4299 | Avg MSE: 0.0209
Epoch 232 | D Loss: 106.4533 | Avg G Loss: 3.4299 | Avg MSE: 0.0211
Epoch 233 | D Loss: 106.4534 | Avg G Loss: 3.4299 | Avg MSE: 0.0220
Epoch 234 | D Loss: 106.4528 | Avg G Loss: 3.4299 | Avg MSE: 0.0221
Epoch 235 | D Loss: 106.4534 | Avg G Loss: 3.4299 | Avg MSE: 0.0217
Epoch 236 | D Loss: 106.4528 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 237 | D Loss: 106.4532 | Avg G Loss: 3.4299 | Avg MSE: 0.0215
Epoch 238 | D Loss: 106.4531 | Avg G Loss: 3.4298 | Avg MSE: 0.0213
Epoch 239 | D Loss: 106.4533 | Avg G Loss: 3.4299 | Avg MSE: 0.0211
Epoch 240 | D Loss: 106.4530 | Avg G Loss: 3.4298 | Avg MSE: 0.0219
Epoch 241 | D Loss: 106.4534 | Avg G Loss: 3.4298 | Avg MSE: 0.0216
Epoch 242 | D Loss: 106.4532 | Avg G Loss: 3.4298 | Avg MSE: 0.0216
Epoch 243 | D Loss: 106.4534 | Avg G Loss: 3.4298 | Avg MSE: 0.0215
Epoch 244 | D Loss: 106.4533 | Avg G Loss: 3.4298 | Avg MSE: 0.0219
Epoch 245 | D Loss: 106.4538 | Avg G Loss: 3.4298 | Avg MSE: 0.0223
Epoch 246 | D Loss: 106.4537 | Avg G Loss: 3.4298 | Avg MSE: 0.0215
Epoch 247 | D Loss: 106.4540 | Avg G Loss: 3.4297 | Avg MSE: 0.0215

Epoch 248 | D Loss: 106.4536 | Avg G Loss: 3.4297 | Avg MSE: 0.0216
Epoch 249 | D Loss: 106.4539 | Avg G Loss: 3.4297 | Avg MSE: 0.0218
Epoch 250 | D Loss: 106.4544 | Avg G Loss: 3.4297 | Avg MSE: 0.0212
Epoch 251 | D Loss: 106.4534 | Avg G Loss: 3.4297 | Avg MSE: 0.0218
Epoch 252 | D Loss: 106.4540 | Avg G Loss: 3.4297 | Avg MSE: 0.0219
Epoch 253 | D Loss: 106.4539 | Avg G Loss: 3.4297 | Avg MSE: 0.0216
Epoch 254 | D Loss: 106.4540 | Avg G Loss: 3.4297 | Avg MSE: 0.0215
Epoch 255 | D Loss: 106.4543 | Avg G Loss: 3.4297 | Avg MSE: 0.0221
Epoch 256 | D Loss: 106.4539 | Avg G Loss: 3.4297 | Avg MSE: 0.0214
Epoch 257 | D Loss: 106.4546 | Avg G Loss: 3.4297 | Avg MSE: 0.0210
Epoch 258 | D Loss: 106.4539 | Avg G Loss: 3.4297 | Avg MSE: 0.0216
Epoch 259 | D Loss: 106.4542 | Avg G Loss: 3.4297 | Avg MSE: 0.0215
Epoch 260 | D Loss: 106.4538 | Avg G Loss: 3.4297 | Avg MSE: 0.0216
Epoch 261 | D Loss: 106.4544 | Avg G Loss: 3.4297 | Avg MSE: 0.0214
Epoch 262 | D Loss: 106.4550 | Avg G Loss: 3.4297 | Avg MSE: 0.0214
Epoch 263 | D Loss: 106.4547 | Avg G Loss: 3.4297 | Avg MSE: 0.0215
Epoch 264 | D Loss: 106.4544 | Avg G Loss: 3.4297 | Avg MSE: 0.0214
Epoch 265 | D Loss: 106.4546 | Avg G Loss: 3.4297 | Avg MSE: 0.0213
Epoch 266 | D Loss: 106.4547 | Avg G Loss: 3.4297 | Avg MSE: 0.0215
Epoch 267 | D Loss: 106.4547 | Avg G Loss: 3.4297 | Avg MSE: 0.0216
Epoch 268 | D Loss: 106.4541 | Avg G Loss: 3.4297 | Avg MSE: 0.0215
Epoch 269 | D Loss: 106.4542 | Avg G Loss: 3.4297 | Avg MSE: 0.0217
Epoch 270 | D Loss: 106.4540 | Avg G Loss: 3.4298 | Avg MSE: 0.0216
Epoch 271 | D Loss: 106.4542 | Avg G Loss: 3.4298 | Avg MSE: 0.0211
Epoch 272 | D Loss: 106.4544 | Avg G Loss: 3.4298 | Avg MSE: 0.0222
Epoch 273 | D Loss: 106.4539 | Avg G Loss: 3.4298 | Avg MSE: 0.0216
Epoch 274 | D Loss: 106.4540 | Avg G Loss: 3.4298 | Avg MSE: 0.0219
Epoch 275 | D Loss: 106.4538 | Avg G Loss: 3.4299 | Avg MSE: 0.0211
Epoch 276 | D Loss: 106.4539 | Avg G Loss: 3.4299 | Avg MSE: 0.0212
Epoch 277 | D Loss: 106.4536 | Avg G Loss: 3.4299 | Avg MSE: 0.0215
Epoch 278 | D Loss: 106.4538 | Avg G Loss: 3.4299 | Avg MSE: 0.0215
Epoch 279 | D Loss: 106.4541 | Avg G Loss: 3.4300 | Avg MSE: 0.0212
Epoch 280 | D Loss: 106.4537 | Avg G Loss: 3.4300 | Avg MSE: 0.0210
Epoch 281 | D Loss: 106.4539 | Avg G Loss: 3.4300 | Avg MSE: 0.0210
Epoch 282 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0219
Epoch 283 | D Loss: 106.4537 | Avg G Loss: 3.4301 | Avg MSE: 0.0215
Epoch 284 | D Loss: 106.4538 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 285 | D Loss: 106.4535 | Avg G Loss: 3.4301 | Avg MSE: 0.0210
Epoch 286 | D Loss: 106.4537 | Avg G Loss: 3.4301 | Avg MSE: 0.0217
Epoch 287 | D Loss: 106.4536 | Avg G Loss: 3.4301 | Avg MSE: 0.0218
Epoch 288 | D Loss: 106.4529 | Avg G Loss: 3.4301 | Avg MSE: 0.0211
Epoch 289 | D Loss: 106.4530 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 290 | D Loss: 106.4534 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 291 | D Loss: 106.4532 | Avg G Loss: 3.4301 | Avg MSE: 0.0216
Epoch 292 | D Loss: 106.4528 | Avg G Loss: 3.4300 | Avg MSE: 0.0218
Epoch 293 | D Loss: 106.4531 | Avg G Loss: 3.4300 | Avg MSE: 0.0217
Epoch 294 | D Loss: 106.4537 | Avg G Loss: 3.4300 | Avg MSE: 0.0215
Epoch 295 | D Loss: 106.4527 | Avg G Loss: 3.4300 | Avg MSE: 0.0216
Epoch 296 | D Loss: 106.4529 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 297 | D Loss: 106.4531 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 298 | D Loss: 106.4529 | Avg G Loss: 3.4299 | Avg MSE: 0.0214
Epoch 299 | D Loss: 106.4536 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 300 | D Loss: 106.4533 | Avg G Loss: 3.4298 | Avg MSE: 0.0214
Epoch 301 | D Loss: 106.4533 | Avg G Loss: 3.4298 | Avg MSE: 0.0215
Epoch 302 | D Loss: 106.4533 | Avg G Loss: 3.4298 | Avg MSE: 0.0215
Epoch 303 | D Loss: 106.4532 | Avg G Loss: 3.4298 | Avg MSE: 0.0216
Epoch 304 | D Loss: 106.4528 | Avg G Loss: 3.4298 | Avg MSE: 0.0216
Epoch 305 | D Loss: 106.4531 | Avg G Loss: 3.4298 | Avg MSE: 0.0213
Epoch 306 | D Loss: 106.4531 | Avg G Loss: 3.4299 | Avg MSE: 0.0214
Epoch 307 | D Loss: 106.4529 | Avg G Loss: 3.4299 | Avg MSE: 0.0217
Epoch 308 | D Loss: 106.4529 | Avg G Loss: 3.4299 | Avg MSE: 0.0216
Epoch 309 | D Loss: 106.4537 | Avg G Loss: 3.4299 | Avg MSE: 0.0217
Epoch 310 | D Loss: 106.4532 | Avg G Loss: 3.4299 | Avg MSE: 0.0214
Epoch 311 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0216
Epoch 312 | D Loss: 106.4531 | Avg G Loss: 3.4300 | Avg MSE: 0.0215
Epoch 313 | D Loss: 106.4534 | Avg G Loss: 3.4300 | Avg MSE: 0.0223
Epoch 314 | D Loss: 106.4539 | Avg G Loss: 3.4300 | Avg MSE: 0.0213
Epoch 315 | D Loss: 106.4532 | Avg G Loss: 3.4301 | Avg MSE: 0.0219
Epoch 316 | D Loss: 106.4533 | Avg G Loss: 3.4301 | Avg MSE: 0.0215
Epoch 317 | D Loss: 106.4530 | Avg G Loss: 3.4301 | Avg MSE: 0.0217
Epoch 318 | D Loss: 106.4531 | Avg G Loss: 3.4301 | Avg MSE: 0.0210
Epoch 319 | D Loss: 106.4530 | Avg G Loss: 3.4301 | Avg MSE: 0.0211
Epoch 320 | D Loss: 106.4532 | Avg G Loss: 3.4301 | Avg MSE: 0.0211
Epoch 321 | D Loss: 106.4534 | Avg G Loss: 3.4300 | Avg MSE: 0.0212
Epoch 322 | D Loss: 106.4534 | Avg G Loss: 3.4300 | Avg MSE: 0.0217
Epoch 323 | D Loss: 106.4533 | Avg G Loss: 3.4300 | Avg MSE: 0.0214
Epoch 324 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0211
Epoch 325 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0216
Epoch 326 | D Loss: 106.4537 | Avg G Loss: 3.4299 | Avg MSE: 0.0217
Epoch 327 | D Loss: 106.4537 | Avg G Loss: 3.4299 | Avg MSE: 0.0219
Epoch 328 | D Loss: 106.4536 | Avg G Loss: 3.4299 | Avg MSE: 0.0218
Epoch 329 | D Loss: 106.4536 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 330 | D Loss: 106.4535 | Avg G Loss: 3.4299 | Avg MSE: 0.0214
Epoch 331 | D Loss: 106.4537 | Avg G Loss: 3.4299 | Avg MSE: 0.0217
Epoch 332 | D Loss: 106.4531 | Avg G Loss: 3.4299 | Avg MSE: 0.0211
Epoch 333 | D Loss: 106.4537 | Avg G Loss: 3.4299 | Avg MSE: 0.0223
Epoch 334 | D Loss: 106.4535 | Avg G Loss: 3.4299 | Avg MSE: 0.0214
Epoch 335 | D Loss: 106.4535 | Avg G Loss: 3.4299 | Avg MSE: 0.0216
Epoch 336 | D Loss: 106.4532 | Avg G Loss: 3.4299 | Avg MSE: 0.0209
Epoch 337 | D Loss: 106.4529 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 338 | D Loss: 106.4528 | Avg G Loss: 3.4299 | Avg MSE: 0.0216
Epoch 339 | D Loss: 106.4527 | Avg G Loss: 3.4300 | Avg MSE: 0.0217
Epoch 340 | D Loss: 106.4530 | Avg G Loss: 3.4299 | Avg MSE: 0.0212
Epoch 341 | D Loss: 106.4528 | Avg G Loss: 3.4300 | Avg MSE: 0.0218
Epoch 342 | D Loss: 106.4526 | Avg G Loss: 3.4300 | Avg MSE: 0.0211
Epoch 343 | D Loss: 106.4526 | Avg G Loss: 3.4299 | Avg MSE: 0.0214
Epoch 344 | D Loss: 106.4526 | Avg G Loss: 3.4299 | Avg MSE: 0.0218
Epoch 345 | D Loss: 106.4525 | Avg G Loss: 3.4299 | Avg MSE: 0.0212
Epoch 346 | D Loss: 106.4530 | Avg G Loss: 3.4299 | Avg MSE: 0.0208
Epoch 347 | D Loss: 106.4527 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 348 | D Loss: 106.4529 | Avg G Loss: 3.4298 | Avg MSE: 0.0216
Epoch 349 | D Loss: 106.4530 | Avg G Loss: 3.4298 | Avg MSE: 0.0212
Epoch 350 | D Loss: 106.4532 | Avg G Loss: 3.4298 | Avg MSE: 0.0217
Epoch 351 | D Loss: 106.4537 | Avg G Loss: 3.4298 | Avg MSE: 0.0213
Epoch 352 | D Loss: 106.4537 | Avg G Loss: 3.4298 | Avg MSE: 0.0214
Epoch 353 | D Loss: 106.4538 | Avg G Loss: 3.4298 | Avg MSE: 0.0212
Epoch 354 | D Loss: 106.4538 | Avg G Loss: 3.4298 | Avg MSE: 0.0210
Epoch 355 | D Loss: 106.4541 | Avg G Loss: 3.4298 | Avg MSE: 0.0213
Epoch 356 | D Loss: 106.4539 | Avg G Loss: 3.4298 | Avg MSE: 0.0218
Epoch 357 | D Loss: 106.4543 | Avg G Loss: 3.4298 | Avg MSE: 0.0215
Epoch 358 | D Loss: 106.4541 | Avg G Loss: 3.4298 | Avg MSE: 0.0212
Epoch 359 | D Loss: 106.4541 | Avg G Loss: 3.4298 | Avg MSE: 0.0211
Epoch 360 | D Loss: 106.4547 | Avg G Loss: 3.4298 | Avg MSE: 0.0215
Epoch 361 | D Loss: 106.4548 | Avg G Loss: 3.4298 | Avg MSE: 0.0219
Epoch 362 | D Loss: 106.4539 | Avg G Loss: 3.4299 | Avg MSE: 0.0216
Epoch 363 | D Loss: 106.4543 | Avg G Loss: 3.4299 | Avg MSE: 0.0212
Epoch 364 | D Loss: 106.4543 | Avg G Loss: 3.4299 | Avg MSE: 0.0212
Epoch 365 | D Loss: 106.4537 | Avg G Loss: 3.4299 | Avg MSE: 0.0208
Epoch 366 | D Loss: 106.4536 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 367 | D Loss: 106.4535 | Avg G Loss: 3.4300 | Avg MSE: 0.0212
Epoch 368 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0218
Epoch 369 | D Loss: 106.4535 | Avg G Loss: 3.4300 | Avg MSE: 0.0213
Epoch 370 | D Loss: 106.4532 | Avg G Loss: 3.4300 | Avg MSE: 0.0215
Epoch 371 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0211

Epoch 372 | D Loss: 106.4535 | Avg G Loss: 3.4300 | Avg MSE: 0.0209
Epoch 373 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0216
Epoch 374 | D Loss: 106.4537 | Avg G Loss: 3.4300 | Avg MSE: 0.0211
Epoch 375 | D Loss: 106.4530 | Avg G Loss: 3.4301 | Avg MSE: 0.0217
Epoch 376 | D Loss: 106.4534 | Avg G Loss: 3.4301 | Avg MSE: 0.0211
Epoch 377 | D Loss: 106.4536 | Avg G Loss: 3.4300 | Avg MSE: 0.0211
Epoch 378 | D Loss: 106.4529 | Avg G Loss: 3.4301 | Avg MSE: 0.0216
Epoch 379 | D Loss: 106.4533 | Avg G Loss: 3.4301 | Avg MSE: 0.0216
Epoch 380 | D Loss: 106.4535 | Avg G Loss: 3.4301 | Avg MSE: 0.0215
Epoch 381 | D Loss: 106.4530 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 382 | D Loss: 106.4534 | Avg G Loss: 3.4301 | Avg MSE: 0.0208
Epoch 383 | D Loss: 106.4535 | Avg G Loss: 3.4301 | Avg MSE: 0.0208
Epoch 384 | D Loss: 106.4531 | Avg G Loss: 3.4301 | Avg MSE: 0.0209
Epoch 385 | D Loss: 106.4527 | Avg G Loss: 3.4301 | Avg MSE: 0.0209
Epoch 386 | D Loss: 106.4528 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 387 | D Loss: 106.4526 | Avg G Loss: 3.4301 | Avg MSE: 0.0209
Epoch 388 | D Loss: 106.4526 | Avg G Loss: 3.4301 | Avg MSE: 0.0211
Epoch 389 | D Loss: 106.4528 | Avg G Loss: 3.4301 | Avg MSE: 0.0213
Epoch 390 | D Loss: 106.4523 | Avg G Loss: 3.4301 | Avg MSE: 0.0207
Epoch 391 | D Loss: 106.4524 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 392 | D Loss: 106.4519 | Avg G Loss: 3.4302 | Avg MSE: 0.0213
Epoch 393 | D Loss: 106.4524 | Avg G Loss: 3.4302 | Avg MSE: 0.0213
Epoch 394 | D Loss: 106.4520 | Avg G Loss: 3.4302 | Avg MSE: 0.0213
Epoch 395 | D Loss: 106.4522 | Avg G Loss: 3.4302 | Avg MSE: 0.0210
Epoch 396 | D Loss: 106.4521 | Avg G Loss: 3.4302 | Avg MSE: 0.0214
Epoch 397 | D Loss: 106.4518 | Avg G Loss: 3.4302 | Avg MSE: 0.0213
Epoch 398 | D Loss: 106.4523 | Avg G Loss: 3.4301 | Avg MSE: 0.0214
Epoch 399 | D Loss: 106.4519 | Avg G Loss: 3.4301 | Avg MSE: 0.0214
Epoch 400 | D Loss: 106.4521 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 401 | D Loss: 106.4515 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 402 | D Loss: 106.4518 | Avg G Loss: 3.4301 | Avg MSE: 0.0218
Epoch 403 | D Loss: 106.4518 | Avg G Loss: 3.4301 | Avg MSE: 0.0210
Epoch 404 | D Loss: 106.4518 | Avg G Loss: 3.4300 | Avg MSE: 0.0211
Epoch 405 | D Loss: 106.4517 | Avg G Loss: 3.4300 | Avg MSE: 0.0209
Epoch 406 | D Loss: 106.4517 | Avg G Loss: 3.4300 | Avg MSE: 0.0212
Epoch 407 | D Loss: 106.4518 | Avg G Loss: 3.4300 | Avg MSE: 0.0212
Epoch 408 | D Loss: 106.4517 | Avg G Loss: 3.4300 | Avg MSE: 0.0213
Epoch 409 | D Loss: 106.4515 | Avg G Loss: 3.4300 | Avg MSE: 0.0212
Epoch 410 | D Loss: 106.4515 | Avg G Loss: 3.4300 | Avg MSE: 0.0216
Epoch 411 | D Loss: 106.4511 | Avg G Loss: 3.4300 | Avg MSE: 0.0214
Epoch 412 | D Loss: 106.4515 | Avg G Loss: 3.4300 | Avg MSE: 0.0218
Epoch 413 | D Loss: 106.4513 | Avg G Loss: 3.4300 | Avg MSE: 0.0213
Epoch 414 | D Loss: 106.4511 | Avg G Loss: 3.4300 | Avg MSE: 0.0209
Epoch 415 | D Loss: 106.4514 | Avg G Loss: 3.4300 | Avg MSE: 0.0213
Epoch 416 | D Loss: 106.4510 | Avg G Loss: 3.4300 | Avg MSE: 0.0215
Epoch 417 | D Loss: 106.4512 | Avg G Loss: 3.4300 | Avg MSE: 0.0208
Epoch 418 | D Loss: 106.4514 | Avg G Loss: 3.4300 | Avg MSE: 0.0211
Epoch 419 | D Loss: 106.4511 | Avg G Loss: 3.4300 | Avg MSE: 0.0209
Epoch 420 | D Loss: 106.4515 | Avg G Loss: 3.4300 | Avg MSE: 0.0214
Epoch 421 | D Loss: 106.4516 | Avg G Loss: 3.4300 | Avg MSE: 0.0208
Epoch 422 | D Loss: 106.4519 | Avg G Loss: 3.4299 | Avg MSE: 0.0212
Epoch 423 | D Loss: 106.4519 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 424 | D Loss: 106.4520 | Avg G Loss: 3.4299 | Avg MSE: 0.0213
Epoch 425 | D Loss: 106.4519 | Avg G Loss: 3.4299 | Avg MSE: 0.0216
Epoch 426 | D Loss: 106.4519 | Avg G Loss: 3.4298 | Avg MSE: 0.0209
Epoch 427 | D Loss: 106.4520 | Avg G Loss: 3.4298 | Avg MSE: 0.0213
Epoch 428 | D Loss: 106.4520 | Avg G Loss: 3.4297 | Avg MSE: 0.0213
Epoch 429 | D Loss: 106.4523 | Avg G Loss: 3.4297 | Avg MSE: 0.0214
Epoch 430 | D Loss: 106.4522 | Avg G Loss: 3.4297 | Avg MSE: 0.0216
Epoch 431 | D Loss: 106.4524 | Avg G Loss: 3.4297 | Avg MSE: 0.0208
Epoch 432 | D Loss: 106.4527 | Avg G Loss: 3.4297 | Avg MSE: 0.0210
Epoch 433 | D Loss: 106.4531 | Avg G Loss: 3.4297 | Avg MSE: 0.0218
Epoch 434 | D Loss: 106.4528 | Avg G Loss: 3.4297 | Avg MSE: 0.0211
Epoch 435 | D Loss: 106.4529 | Avg G Loss: 3.4297 | Avg MSE: 0.0217
Epoch 436 | D Loss: 106.4529 | Avg G Loss: 3.4297 | Avg MSE: 0.0213
Epoch 437 | D Loss: 106.4529 | Avg G Loss: 3.4297 | Avg MSE: 0.0208
Epoch 438 | D Loss: 106.4526 | Avg G Loss: 3.4297 | Avg MSE: 0.0212
Epoch 439 | D Loss: 106.4528 | Avg G Loss: 3.4297 | Avg MSE: 0.0217
Epoch 440 | D Loss: 106.4534 | Avg G Loss: 3.4298 | Avg MSE: 0.0211
Epoch 441 | D Loss: 106.4530 | Avg G Loss: 3.4298 | Avg MSE: 0.0209
Epoch 442 | D Loss: 106.4526 | Avg G Loss: 3.4298 | Avg MSE: 0.0217
Epoch 443 | D Loss: 106.4530 | Avg G Loss: 3.4298 | Avg MSE: 0.0218
Epoch 444 | D Loss: 106.4532 | Avg G Loss: 3.4299 | Avg MSE: 0.0211
Epoch 445 | D Loss: 106.4533 | Avg G Loss: 3.4299 | Avg MSE: 0.0215
Epoch 446 | D Loss: 106.4530 | Avg G Loss: 3.4299 | Avg MSE: 0.0212
Epoch 447 | D Loss: 106.4528 | Avg G Loss: 3.4299 | Avg MSE: 0.0211
Epoch 448 | D Loss: 106.4534 | Avg G Loss: 3.4300 | Avg MSE: 0.0211
Epoch 449 | D Loss: 106.4532 | Avg G Loss: 3.4300 | Avg MSE: 0.0215
Epoch 450 | D Loss: 106.4531 | Avg G Loss: 3.4301 | Avg MSE: 0.0212
Epoch 451 | D Loss: 106.4533 | Avg G Loss: 3.4301 | Avg MSE: 0.0206
Epoch 452 | D Loss: 106.4536 | Avg G Loss: 3.4301 | Avg MSE: 0.0216
Epoch 453 | D Loss: 106.4536 | Avg G Loss: 3.4301 | Avg MSE: 0.0209
Epoch 454 | D Loss: 106.4531 | Avg G Loss: 3.4302 | Avg MSE: 0.0212
Epoch 455 | D Loss: 106.4533 | Avg G Loss: 3.4302 | Avg MSE: 0.0209
Epoch 456 | D Loss: 106.4536 | Avg G Loss: 3.4302 | Avg MSE: 0.0212
Epoch 457 | D Loss: 106.4539 | Avg G Loss: 3.4303 | Avg MSE: 0.0213
Epoch 458 | D Loss: 106.4535 | Avg G Loss: 3.4303 | Avg MSE: 0.0214
Epoch 459 | D Loss: 106.4538 | Avg G Loss: 3.4303 | Avg MSE: 0.0209
Epoch 460 | D Loss: 106.4540 | Avg G Loss: 3.4303 | Avg MSE: 0.0217
Epoch 461 | D Loss: 106.4537 | Avg G Loss: 3.4303 | Avg MSE: 0.0205
Epoch 462 | D Loss: 106.4545 | Avg G Loss: 3.4304 | Avg MSE: 0.0208
Epoch 463 | D Loss: 106.4536 | Avg G Loss: 3.4304 | Avg MSE: 0.0213
Epoch 464 | D Loss: 106.4542 | Avg G Loss: 3.4304 | Avg MSE: 0.0212
Epoch 465 | D Loss: 106.4543 | Avg G Loss: 3.4304 | Avg MSE: 0.0211
Epoch 466 | D Loss: 106.4541 | Avg G Loss: 3.4304 | Avg MSE: 0.0207
Epoch 467 | D Loss: 106.4538 | Avg G Loss: 3.4304 | Avg MSE: 0.0209
Epoch 468 | D Loss: 106.4538 | Avg G Loss: 3.4305 | Avg MSE: 0.0210
Epoch 469 | D Loss: 106.4540 | Avg G Loss: 3.4304 | Avg MSE: 0.0214
Epoch 470 | D Loss: 106.4539 | Avg G Loss: 3.4305 | Avg MSE: 0.0206
Epoch 471 | D Loss: 106.4535 | Avg G Loss: 3.4304 | Avg MSE: 0.0211
Epoch 472 | D Loss: 106.4538 | Avg G Loss: 3.4304 | Avg MSE: 0.0217
Epoch 473 | D Loss: 106.4535 | Avg G Loss: 3.4304 | Avg MSE: 0.0216
Epoch 474 | D Loss: 106.4533 | Avg G Loss: 3.4304 | Avg MSE: 0.0206
Epoch 475 | D Loss: 106.4532 | Avg G Loss: 3.4304 | Avg MSE: 0.0212
Epoch 476 | D Loss: 106.4531 | Avg G Loss: 3.4304 | Avg MSE: 0.0210
Epoch 477 | D Loss: 106.4530 | Avg G Loss: 3.4304 | Avg MSE: 0.0213
Epoch 478 | D Loss: 106.4531 | Avg G Loss: 3.4304 | Avg MSE: 0.0218
Epoch 479 | D Loss: 106.4532 | Avg G Loss: 3.4304 | Avg MSE: 0.0214
Epoch 480 | D Loss: 106.4534 | Avg G Loss: 3.4304 | Avg MSE: 0.0214
Epoch 481 | D Loss: 106.4539 | Avg G Loss: 3.4304 | Avg MSE: 0.0213
Epoch 482 | D Loss: 106.4538 | Avg G Loss: 3.4304 | Avg MSE: 0.0215
Epoch 483 | D Loss: 106.4535 | Avg G Loss: 3.4305 | Avg MSE: 0.0212
Epoch 484 | D Loss: 106.4539 | Avg G Loss: 3.4305 | Avg MSE: 0.0214
Epoch 485 | D Loss: 106.4539 | Avg G Loss: 3.4305 | Avg MSE: 0.0215
Epoch 486 | D Loss: 106.4539 | Avg G Loss: 3.4306 | Avg MSE: 0.0214
Epoch 487 | D Loss: 106.4543 | Avg G Loss: 3.4306 | Avg MSE: 0.0212
Epoch 488 | D Loss: 106.4540 | Avg G Loss: 3.4306 | Avg MSE: 0.0215
Epoch 489 | D Loss: 106.4539 | Avg G Loss: 3.4307 | Avg MSE: 0.0211
Epoch 490 | D Loss: 106.4540 | Avg G Loss: 3.4307 | Avg MSE: 0.0215
Epoch 491 | D Loss: 106.4534 | Avg G Loss: 3.4307 | Avg MSE: 0.0209
Epoch 492 | D Loss: 106.4535 | Avg G Loss: 3.4307 | Avg MSE: 0.0216

Epoch 493 | D Loss: 106.4531 | Avg G Loss: 3.4308 | Avg MSE: 0.0212
Epoch 494 | D Loss: 106.4535 | Avg G Loss: 3.4308 | Avg MSE: 0.0209
Epoch 495 | D Loss: 106.4528 | Avg G Loss: 3.4308 | Avg MSE: 0.0213
Epoch 496 | D Loss: 106.4527 | Avg G Loss: 3.4308 | Avg MSE: 0.0212
Epoch 497 | D Loss: 106.4529 | Avg G Loss: 3.4308 | Avg MSE: 0.0213
Epoch 498 | D Loss: 106.4528 | Avg G Loss: 3.4308 | Avg MSE: 0.0211
Epoch 499 | D Loss: 106.4525 | Avg G Loss: 3.4308 | Avg MSE: 0.0210
Epoch 500 | D Loss: 106.4525 | Avg G Loss: 3.4308 | Avg MSE: 0.0214

In [5]:
from transformers import AutoTokenizer, AutoModel
import torch
import pandas as pd
from tqdm import tqdm

# Load fault texts
df = pd.read_excel("fault-logs-o-ran-350.xls")
#df = pd.read_excel("proj-training-12k.xlsx", engine="openpyxl")
fault_texts = df["Fault Description"].astype(str).tolist()

# Load MiniLM tokenizer + model
tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
model = AutoModel.from_pretrained("sentence-transformers/all-MiniLM-L6-v2")
model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

max_length = 128
token_level_embeddings = []

with torch.no_grad():
    for sentence in tqdm(fault_texts):
        encoded = tokenizer(sentence, padding="max_length", truncation=True,
                            max_length=max_length, return_tensors="pt").to(device)
        
        output = model(**encoded)  # output.last_hidden_state: [1, 128, 384]
        token_embeds = output.last_hidden_state.squeeze(0).cpu()  # [128, 384]
        
        token_level_embeddings.append(token_embeds)

# Save as a tensor [N, 128, 384]
token_level_embeddings = torch.stack(token_level_embeddings)
torch.save(token_level_embeddings, "minilm_token_embeddings.pt")

100%|████████████████████████████████████████| 350/350 [00:00<00:00, 359.15it/s]

In [2]:
import pandas as pd
import torch
from torch.utils.data import Dataset
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling

# Load fault logs
df = pd.read_excel("fault-logs-o-ran-350.xls")
#df = pd.read_excel("proj-training-12k.xlsx", engine="openpyxl")
fault_texts = df["Fault Description"].astype(str).tolist()

# Tokenizer and GPT-2
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")

# Dataset
class FaultDataset(Dataset):
    def __init__(self, texts, tokenizer):
        self.examples = tokenizer(texts, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
    def __len__(self):
        return len(self.examples["input_ids"])
    def __getitem__(self, idx):
        return {k: v[idx] for k, v in self.examples.items()}

dataset = FaultDataset(fault_texts, tokenizer)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Training
training_args = TrainingArguments(
    output_dir="./gpt2-finetuned-fault",
    per_device_train_batch_size=4,
    num_train_epochs=10,
    logging_steps=10,
    save_strategy="epoch",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    tokenizer=tokenizer,
    data_collator=data_collator
)

trainer.train()
model.save_pretrained("gpt2-finetuned-fault")
tokenizer.save_pretrained("gpt2-finetuned-fault")

/tmp/ipykernel_4393/3540866464.py:38: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

('gpt2-finetuned-fault/tokenizer_config.json',
 'gpt2-finetuned-fault/special_tokens_map.json',
 'gpt2-finetuned-fault/vocab.json',
 'gpt2-finetuned-fault/merges.txt',
 'gpt2-finetuned-fault/added_tokens.json')

In [16]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import pandas as pd

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load MiniLM token embeddings
minilm_token_embeds = torch.load("minilm_token_embeddings.pt")

# Load texts
df = pd.read_excel("fault-logs-o-ran-350.xls")
fault_texts = df["Fault Description"].astype(str).tolist()

# Load GPT-2
tokenizer = GPT2Tokenizer.from_pretrained("gpt2-finetuned-fault")
tokenizer.pad_token = tokenizer.eos_token

gpt2 = GPT2LMHeadModel.from_pretrained("gpt2-finetuned-fault").to(device)
gpt2.eval()

for p in gpt2.parameters():
    p.requires_grad = False

MAX_LEN = 128

class ProjectorDataset(Dataset):

    def __init__(self, embeds, texts):

        tok = tokenizer(
            texts,
            padding="max_length",
            truncation=True,
            max_length=MAX_LEN,
            return_tensors="pt"
        )

        self.embeds = embeds
        self.input_ids = tok["input_ids"]
        self.attn_mask = tok["attention_mask"]

        # ignore pad tokens
        self.labels = self.input_ids.clone()
        self.labels[self.attn_mask == 0] = -100

    def __len__(self):
        return len(self.embeds)

    def __getitem__(self, idx):
        return {
            "embed": self.embeds[idx],
            "labels": self.labels[idx],
            "mask": self.attn_mask[idx]
        }

dataset = ProjectorDataset(minilm_token_embeds, fault_texts)
loader = DataLoader(dataset, batch_size=8, shuffle=True)

# projector
class EmbeddingProjector(nn.Module):

    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(384,512),
            nn.GELU(),
            nn.Linear(512,768),
            nn.GELU(),
            nn.Linear(768,768)
        )

    def forward(self,x):

        B,T,D = x.size()

        x = x.view(B*T,D)
        x = self.net(x)
        x = x.view(B,T,768)

        return x


projector = EmbeddingProjector().to(device)

optimizer = torch.optim.Adam(projector.parameters(), lr=1e-4)

EPOCHS = 300

for epoch in range(EPOCHS):

    projector.train()
    total_loss = 0

    for batch in loader:

        embeds = batch["embed"].to(device)
        labels = batch["labels"].to(device)
        mask = batch["mask"].to(device)

        proj = projector(embeds)

        outputs = gpt2(
            inputs_embeds=proj,
            attention_mask=mask,
            labels=labels
        )

        loss = outputs.loss

        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{EPOCHS} | Loss {total_loss/len(loader):.4f}")

torch.save(projector.state_dict(),"trained_projector-new.pt")

Epoch 1/300 | Loss 11.6195
Epoch 2/300 | Loss 7.0127
Epoch 3/300 | Loss 6.5585
Epoch 4/300 | Loss 6.3562
Epoch 5/300 | Loss 6.1865
Epoch 6/300 | Loss 6.0581
Epoch 7/300 | Loss 5.9535
Epoch 8/300 | Loss 5.8589
Epoch 9/300 | Loss 5.7775
Epoch 10/300 | Loss 5.7050
Epoch 11/300 | Loss 5.6322
Epoch 12/300 | Loss 5.5842
Epoch 13/300 | Loss 5.5293
Epoch 14/300 | Loss 5.4641
Epoch 15/300 | Loss 5.4042
Epoch 16/300 | Loss 5.3391
Epoch 17/300 | Loss 5.2981
Epoch 18/300 | Loss 5.2631
Epoch 19/300 | Loss 5.2359
Epoch 20/300 | Loss 5.1901
Epoch 21/300 | Loss 5.1461
Epoch 22/300 | Loss 5.0886
Epoch 23/300 | Loss 5.0740
Epoch 24/300 | Loss 5.0076
Epoch 25/300 | Loss 4.9776
Epoch 26/300 | Loss 4.9498
Epoch 27/300 | Loss 4.8807
Epoch 28/300 | Loss 4.8717
Epoch 29/300 | Loss 4.8677
Epoch 30/300 | Loss 4.8259
Epoch 31/300 | Loss 4.7707
Epoch 32/300 | Loss 4.7544
Epoch 33/300 | Loss 4.7055
Epoch 34/300 | Loss 4.6856
Epoch 35/300 | Loss 4.6993
Epoch 36/300 | Loss 4.6475
Epoch 37/300 | Loss 4.6005
Epoch 38/300 | Loss 4.6066
Epoch 39/300 | Loss 4.5606
Epoch 40/300 | Loss 4.5232
Epoch 41/300 | Loss 4.4868
Epoch 42/300 | Loss 4.4645
Epoch 43/300 | Loss 4.4792
Epoch 44/300 | Loss 4.4177
Epoch 45/300 | Loss 4.3993
Epoch 46/300 | Loss 4.3795
Epoch 47/300 | Loss 4.3374
Epoch 48/300 | Loss 4.2965
Epoch 49/300 | Loss 4.2823
Epoch 50/300 | Loss 4.2260
Epoch 51/300 | Loss 4.2305
Epoch 52/300 | Loss 4.2306
Epoch 53/300 | Loss 4.2082
Epoch 54/300 | Loss 4.2030
Epoch 55/300 | Loss 4.1749
Epoch 56/300 | Loss 4.1268
Epoch 57/300 | Loss 4.0983
Epoch 58/300 | Loss 4.0790
Epoch 59/300 | Loss 4.0782
Epoch 60/300 | Loss 4.0919
Epoch 61/300 | Loss 4.0283
Epoch 62/300 | Loss 4.0155
Epoch 63/300 | Loss 3.9715
Epoch 64/300 | Loss 3.9409
Epoch 65/300 | Loss 3.9147
Epoch 66/300 | Loss 3.9155
Epoch 67/300 | Loss 3.9207
Epoch 68/300 | Loss 3.8756
Epoch 69/300 | Loss 3.8543
Epoch 70/300 | Loss 3.8885
Epoch 71/300 | Loss 3.8638
Epoch 72/300 | Loss 3.8577
Epoch 73/300 | Loss 3.7921
Epoch 74/300 | Loss 3.7619
Epoch 75/300 | Loss 3.7462
Epoch 76/300 | Loss 3.7631
Epoch 77/300 | Loss 3.7777
Epoch 78/300 | Loss 3.7453
Epoch 79/300 | Loss 3.7214
Epoch 80/300 | Loss 3.6758
Epoch 81/300 | Loss 3.6612
Epoch 82/300 | Loss 3.6563
Epoch 83/300 | Loss 3.6447
Epoch 84/300 | Loss 3.6228
Epoch 85/300 | Loss 3.5893
Epoch 86/300 | Loss 3.5548
Epoch 87/300 | Loss 3.5572
Epoch 88/300 | Loss 3.5891
Epoch 89/300 | Loss 3.5815
Epoch 90/300 | Loss 3.5214
Epoch 91/300 | Loss 3.5237
Epoch 92/300 | Loss 3.5011
Epoch 93/300 | Loss 3.4629
Epoch 94/300 | Loss 3.4694
Epoch 95/300 | Loss 3.4246
Epoch 96/300 | Loss 3.3916
Epoch 97/300 | Loss 3.4595
Epoch 98/300 | Loss 3.4492
Epoch 99/300 | Loss 3.3940
Epoch 100/300 | Loss 3.3865
Epoch 101/300 | Loss 3.3546
Epoch 102/300 | Loss 3.3268
Epoch 103/300 | Loss 3.3348
Epoch 104/300 | Loss 3.3674
Epoch 105/300 | Loss 3.3633
Epoch 106/300 | Loss 3.3329
Epoch 107/300 | Loss 3.3000
Epoch 108/300 | Loss 3.2661
Epoch 109/300 | Loss 3.2512
Epoch 110/300 | Loss 3.2618
Epoch 111/300 | Loss 3.2539
Epoch 112/300 | Loss 3.2041
Epoch 113/300 | Loss 3.2065
Epoch 114/300 | Loss 3.2244
Epoch 115/300 | Loss 3.2159
Epoch 116/300 | Loss 3.1845
Epoch 117/300 | Loss 3.1641
Epoch 118/300 | Loss 3.1411
Epoch 119/300 | Loss 3.1304
Epoch 120/300 | Loss 3.1294
Epoch 121/300 | Loss 3.1545
Epoch 122/300 | Loss 3.1395
Epoch 123/300 | Loss 3.0953
Epoch 124/300 | Loss 3.0791
Epoch 125/300 | Loss 3.0982
Epoch 126/300 | Loss 3.0940
Epoch 127/300 | Loss 3.0909
Epoch 128/300 | Loss 3.0482
Epoch 129/300 | Loss 3.0498
Epoch 130/300 | Loss 2.9947
Epoch 131/300 | Loss 2.9702
Epoch 132/300 | Loss 2.9647
Epoch 133/300 | Loss 2.9713
Epoch 134/300 | Loss 2.9869
Epoch 135/300 | Loss 3.0130
Epoch 136/300 | Loss 3.0236
Epoch 137/300 | Loss 3.0285
Epoch 138/300 | Loss 2.9494
Epoch 139/300 | Loss 2.9477
Epoch 140/300 | Loss 2.9520
Epoch 141/300 | Loss 2.9365
Epoch 142/300 | Loss 2.8821
Epoch 143/300 | Loss 2.9178
Epoch 144/300 | Loss 2.9138
Epoch 145/300 | Loss 2.8952
Epoch 146/300 | Loss 2.8869
Epoch 147/300 | Loss 2.8388
Epoch 148/300 | Loss 2.8416
Epoch 149/300 | Loss 2.8452
Epoch 150/300 | Loss 2.8461
Epoch 151/300 | Loss 2.8052
Epoch 152/300 | Loss 2.7996
Epoch 153/300 | Loss 2.8065
Epoch 154/300 | Loss 2.7740
Epoch 155/300 | Loss 2.7670
Epoch 156/300 | Loss 2.8238
Epoch 157/300 | Loss 2.7631
Epoch 158/300 | Loss 2.7436
Epoch 159/300 | Loss 2.7601
Epoch 160/300 | Loss 2.7241
Epoch 161/300 | Loss 2.7602
Epoch 162/300 | Loss 2.7295
Epoch 163/300 | Loss 2.7087
Epoch 164/300 | Loss 2.7146
Epoch 165/300 | Loss 2.7329
Epoch 166/300 | Loss 2.7035
Epoch 167/300 | Loss 2.6509
Epoch 168/300 | Loss 2.6493
Epoch 169/300 | Loss 2.6651
Epoch 170/300 | Loss 2.7033
Epoch 171/300 | Loss 2.6835
Epoch 172/300 | Loss 2.6779
Epoch 173/300 | Loss 2.6204
Epoch 174/300 | Loss 2.6036
Epoch 175/300 | Loss 2.6045
Epoch 176/300 | Loss 2.6437
Epoch 177/300 | Loss 2.6670
Epoch 178/300 | Loss 2.6370
Epoch 179/300 | Loss 2.6112
Epoch 180/300 | Loss 2.6067
Epoch 181/300 | Loss 2.5588
Epoch 182/300 | Loss 2.5539
Epoch 183/300 | Loss 2.5762
Epoch 184/300 | Loss 2.5532
Epoch 185/300 | Loss 2.5416
Epoch 186/300 | Loss 2.5252
Epoch 187/300 | Loss 2.5538
Epoch 188/300 | Loss 2.5452
Epoch 189/300 | Loss 2.5439
Epoch 190/300 | Loss 2.5213
Epoch 191/300 | Loss 2.5018
Epoch 192/300 | Loss 2.4976
Epoch 193/300 | Loss 2.4792
Epoch 194/300 | Loss 2.4676
Epoch 195/300 | Loss 2.4660
Epoch 196/300 | Loss 2.4779
Epoch 197/300 | Loss 2.4546
Epoch 198/300 | Loss 2.4503
Epoch 199/300 | Loss 2.4508
Epoch 200/300 | Loss 2.4687
Epoch 201/300 | Loss 2.4621
Epoch 202/300 | Loss 2.4649
Epoch 203/300 | Loss 2.4491
Epoch 204/300 | Loss 2.4440
Epoch 205/300 | Loss 2.4228
Epoch 206/300 | Loss 2.3956
Epoch 207/300 | Loss 2.3659
Epoch 208/300 | Loss 2.3696
Epoch 209/300 | Loss 2.3886
Epoch 210/300 | Loss 2.3512
Epoch 211/300 | Loss 2.3570
Epoch 212/300 | Loss 2.3597
Epoch 213/300 | Loss 2.3710
Epoch 214/300 | Loss 2.3637
Epoch 215/300 | Loss 2.3368
Epoch 216/300 | Loss 2.3393
Epoch 217/300 | Loss 2.3439
Epoch 218/300 | Loss 2.3282
Epoch 219/300 | Loss 2.3376
Epoch 220/300 | Loss 2.3311
Epoch 221/300 | Loss 2.3088
Epoch 222/300 | Loss 2.2816
Epoch 223/300 | Loss 2.3165
Epoch 224/300 | Loss 2.3049
Epoch 225/300 | Loss 2.3166
Epoch 226/300 | Loss 2.2803
Epoch 227/300 | Loss 2.2801
Epoch 228/300 | Loss 2.2623
Epoch 229/300 | Loss 2.2488
Epoch 230/300 | Loss 2.2778
Epoch 231/300 | Loss 2.2534
Epoch 232/300 | Loss 2.2247
Epoch 233/300 | Loss 2.2104
Epoch 234/300 | Loss 2.2312
Epoch 235/300 | Loss 2.2154
Epoch 236/300 | Loss 2.1782
Epoch 237/300 | Loss 2.1982
Epoch 238/300 | Loss 2.2221
Epoch 239/300 | Loss 2.2370
Epoch 240/300 | Loss 2.1936
Epoch 241/300 | Loss 2.1665
Epoch 242/300 | Loss 2.1833
Epoch 243/300 | Loss 2.2566
Epoch 244/300 | Loss 2.1863
Epoch 245/300 | Loss 2.1630
Epoch 246/300 | Loss 2.1769
Epoch 247/300 | Loss 2.1719
Epoch 248/300 | Loss 2.1897
Epoch 249/300 | Loss 2.1498
Epoch 250/300 | Loss 2.1068
Epoch 251/300 | Loss 2.1013
Epoch 252/300 | Loss 2.1517
Epoch 253/300 | Loss 2.2019
Epoch 254/300 | Loss 2.1415
Epoch 255/300 | Loss 2.1271
Epoch 256/300 | Loss 2.1015
Epoch 257/300 | Loss 2.0978
Epoch 258/300 | Loss 2.0659
Epoch 259/300 | Loss 2.0846
Epoch 260/300 | Loss 2.0806
Epoch 261/300 | Loss 2.0646
Epoch 262/300 | Loss 2.0762
Epoch 263/300 | Loss 2.0639
Epoch 264/300 | Loss 2.0868
Epoch 265/300 | Loss 2.1100
Epoch 266/300 | Loss 2.0636
Epoch 267/300 | Loss 2.0772
Epoch 268/300 | Loss 2.1269
Epoch 269/300 | Loss 2.1423
Epoch 270/300 | Loss 2.0809
Epoch 271/300 | Loss 2.0319
Epoch 272/300 | Loss 2.0090
Epoch 273/300 | Loss 1.9980
Epoch 274/300 | Loss 1.9739
Epoch 275/300 | Loss 1.9664
Epoch 276/300 | Loss 1.9724
Epoch 277/300 | Loss 1.9959
Epoch 278/300 | Loss 1.9959
Epoch 279/300 | Loss 1.9715
Epoch 280/300 | Loss 1.9453
Epoch 281/300 | Loss 1.9534
Epoch 282/300 | Loss 1.9847
Epoch 283/300 | Loss 2.0047
Epoch 284/300 | Loss 2.0172
Epoch 285/300 | Loss 2.0186
Epoch 286/300 | Loss 2.0191
Epoch 287/300 | Loss 1.9908
Epoch 288/300 | Loss 2.0102
Epoch 289/300 | Loss 1.9605
Epoch 290/300 | Loss 1.9174
Epoch 291/300 | Loss 1.9530
Epoch 292/300 | Loss 1.9193
Epoch 293/300 | Loss 1.9135
Epoch 294/300 | Loss 1.9197
Epoch 295/300 | Loss 1.9010
Epoch 296/300 | Loss 1.9387
Epoch 297/300 | Loss 1.9118

Epoch 298/300 | Loss 1.9368
Epoch 299/300 | Loss 1.9002
Epoch 300/300 | Loss 1.9022

In [21]:
import torch
import csv
from torch import nn
from transformers import GPT2LMHeadModel, GPT2Tokenizer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# -----------------------------
# Generator architecture
# -----------------------------
class Generator(nn.Module):

    def __init__(self, latent_dim=100, output_dim=384):
        super().__init__()

        self.model = nn.Sequential(
            nn.Linear(latent_dim,256),
            nn.ReLU(),
            nn.Linear(256,256),
            nn.ReLU(),
            nn.Linear(256,256),
            nn.ReLU(),
            nn.Linear(256,output_dim)
        )

    def forward(self,z):
        return self.model(z)


# -----------------------------
# Load trained generators
# -----------------------------
K = 30
generators = []

for j in range(1,K+1):

    G = Generator().to(device)

    G.load_state_dict(
        torch.load(f"trained_generator_{j}.pt",map_location=device)
    )

    G.eval()
    generators.append(G)

print(f"Loaded {K} generators")


# -----------------------------
# Load GPT-2
# -----------------------------
tokenizer = GPT2Tokenizer.from_pretrained("gpt2-finetuned-fault")
tokenizer.pad_token = tokenizer.eos_token

gpt2 = GPT2LMHeadModel.from_pretrained("gpt2-finetuned-fault")
gpt2 = gpt2.to(device)
gpt2.eval()

print("GPT-2 loaded")


# -----------------------------
# Projector architecture
# (must match training)
# -----------------------------
class EmbeddingProjector(nn.Module):

    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(384,512),
            nn.GELU(),
            nn.Linear(512,768),
            nn.GELU(),
            nn.Linear(768,768)
        )

    def forward(self,x):

        B,T,D = x.size()

        x = x.view(B*T,D)
        x = self.net(x)
        x = x.view(B,T,768)

        return x


projector = EmbeddingProjector().to(device)

projector.load_state_dict(
    torch.load("trained_projector-new.pt",map_location=device)
)

projector.eval()

print("Projector loaded")


# -----------------------------
# Generation settings
# -----------------------------
latent_dim = 100
num_samples_per_gen = 500

prefix_len = 32

decoded_outputs = []

total_expected = K * num_samples_per_gen
sample_counter = 0

print(f"\nExpected samples: {total_expected}\n")


# -----------------------------
# Generate samples
# -----------------------------
with torch.no_grad():

    for g_idx,G in enumerate(generators):

        print(f"\n🔁 Generator {g_idx+1}/{K}")

        z = torch.randn(num_samples_per_gen,latent_dim).to(device)

        fake_emb = G(z)             # [N,384]

        # Convert sentence embedding → token embeddings
        fake_emb = fake_emb.unsqueeze(1).repeat(1,prefix_len,1)

        # Add small noise
        fake_emb = fake_emb + 0.01 * torch.randn_like(fake_emb)

        projected = projector(fake_emb)  # [N,prefix_len,768]

        for i in range(num_samples_per_gen):

            prefix = projected[i].unsqueeze(0)  # [1,prefix_len,768]

            output_ids = gpt2.generate(

                inputs_embeds=prefix,

                max_new_tokens=80,

                do_sample=True,

                temperature=0.8,

                top_k=40,

                top_p=0.9,

                repetition_penalty=1.15,

                pad_token_id=tokenizer.eos_token_id
            )

            decoded = tokenizer.decode(
                output_ids[0],
                skip_special_tokens=True
            )

            decoded_outputs.append(
                (f"G{g_idx+1}",f"Sample {i+1}",decoded)
            )

            sample_counter += 1

            # Show progress every 100 samples
            if sample_counter % 100 == 0:
                print(f"Progress: {sample_counter} / {total_expected}")


# -----------------------------
# Remove empty generations
# -----------------------------
decoded_outputs = [
    row for row in decoded_outputs
    if len(row[2].strip()) > 5
]


# -----------------------------
# Save results
# -----------------------------
output_file = "synthetic_fault_logs_final-2026-15k.csv"

with open(output_file,"w",newline="",encoding="utf-8") as f:

    writer = csv.writer(f)

    writer.writerow([
        "Generator",
        "Sample Number",
        "Generated Fault Description"
    ])

    for row in decoded_outputs:
        writer.writerow(row)


print(f"\nSaved {len(decoded_outputs)} samples to {output_file}")

Loaded 30 generators
GPT-2 loaded
Projector loaded

Expected samples: 15000


🔁 Generator 1/30
Progress: 100 / 15000
Progress: 200 / 15000
Progress: 300 / 15000
Progress: 400 / 15000
Progress: 500 / 15000

🔁 Generator 2/30
Progress: 600 / 15000
Progress: 700 / 15000
Progress: 800 / 15000
Progress: 900 / 15000
Progress: 1000 / 15000

🔁 Generator 3/30
Progress: 1100 / 15000
Progress: 1200 / 15000
Progress: 1300 / 15000
Progress: 1400 / 15000
Progress: 1500 / 15000

🔁 Generator 4/30
Progress: 1600 / 15000
Progress: 1700 / 15000
Progress: 1800 / 15000
Progress: 1900 / 15000
Progress: 2000 / 15000

🔁 Generator 5/30
Progress: 2100 / 15000
Progress: 2200 / 15000
Progress: 2300 / 15000
Progress: 2400 / 15000
Progress: 2500 / 15000

🔁 Generator 6/30
Progress: 2600 / 15000
Progress: 2700 / 15000
Progress: 2800 / 15000
Progress: 2900 / 15000
Progress: 3000 / 15000

🔁 Generator 7/30
Progress: 3100 / 15000
Progress: 3200 / 15000
Progress: 3300 / 15000
Progress: 3400 / 15000
Progress: 3500 / 15000

🔁 Generator 8/30
Progress: 3600 / 15000
Progress: 3700 / 15000
Progress: 3800 / 15000
Progress: 3900 / 15000
Progress: 4000 / 15000

🔁 Generator 9/30
Progress: 4100 / 15000
Progress: 4200 / 15000
Progress: 4300 / 15000
Progress: 4400 / 15000
Progress: 4500 / 15000

🔁 Generator 10/30
Progress: 4600 / 15000
Progress: 4700 / 15000
Progress: 4800 / 15000
Progress: 4900 / 15000
Progress: 5000 / 15000

🔁 Generator 11/30
Progress: 5100 / 15000
Progress: 5200 / 15000
Progress: 5300 / 15000
Progress: 5400 / 15000
Progress: 5500 / 15000

🔁 Generator 12/30
Progress: 5600 / 15000
Progress: 5700 / 15000
Progress: 5800 / 15000
Progress: 5900 / 15000
Progress: 6000 / 15000

🔁 Generator 13/30
Progress: 6100 / 15000
Progress: 6200 / 15000
Progress: 6300 / 15000
Progress: 6400 / 15000
Progress: 6500 / 15000

🔁 Generator 14/30
Progress: 6600 / 15000
Progress: 6700 / 15000
Progress: 6800 / 15000
Progress: 6900 / 15000
Progress: 7000 / 15000

🔁 Generator 15/30
Progress: 7100 / 15000
Progress: 7200 / 15000
Progress: 7300 / 15000
Progress: 7400 / 15000
Progress: 7500 / 15000

🔁 Generator 16/30
Progress: 7600 / 15000
Progress: 7700 / 15000
Progress: 7800 / 15000
Progress: 7900 / 15000
Progress: 8000 / 15000

🔁 Generator 17/30
Progress: 8100 / 15000
Progress: 8200 / 15000
Progress: 8300 / 15000
Progress: 8400 / 15000
Progress: 8500 / 15000

🔁 Generator 18/30
Progress: 8600 / 15000
Progress: 8700 / 15000
Progress: 8800 / 15000
Progress: 8900 / 15000
Progress: 9000 / 15000

🔁 Generator 19/30
Progress: 9100 / 15000
Progress: 9200 / 15000
Progress: 9300 / 15000
Progress: 9400 / 15000
Progress: 9500 / 15000

🔁 Generator 20/30
Progress: 9600 / 15000
Progress: 9700 / 15000
Progress: 9800 / 15000
Progress: 9900 / 15000
Progress: 10000 / 15000

🔁 Generator 21/30
Progress: 10100 / 15000
Progress: 10200 / 15000
Progress: 10300 / 15000
Progress: 10400 / 15000
Progress: 10500 / 15000

🔁 Generator 22/30
Progress: 10600 / 15000
Progress: 10700 / 15000
Progress: 10800 / 15000
Progress: 10900 / 15000
Progress: 11000 / 15000

🔁 Generator 23/30
Progress: 11100 / 15000
Progress: 11200 / 15000
Progress: 11300 / 15000
Progress: 11400 / 15000
Progress: 11500 / 15000

🔁 Generator 24/30
Progress: 11600 / 15000
Progress: 11700 / 15000
Progress: 11800 / 15000
Progress: 11900 / 15000
Progress: 12000 / 15000

🔁 Generator 25/30
Progress: 12100 / 15000
Progress: 12200 / 15000
Progress: 12300 / 15000
Progress: 12400 / 15000
Progress: 12500 / 15000

🔁 Generator 26/30
Progress: 12600 / 15000
Progress: 12700 / 15000
Progress: 12800 / 15000
Progress: 12900 / 15000
Progress: 13000 / 15000

🔁 Generator 27/30
Progress: 13100 / 15000
Progress: 13200 / 15000
Progress: 13300 / 15000
Progress: 13400 / 15000
Progress: 13500 / 15000

🔁 Generator 28/30
Progress: 13600 / 15000
Progress: 13700 / 15000
Progress: 13800 / 15000
Progress: 13900 / 15000
Progress: 14000 / 15000

🔁 Generator 29/30
Progress: 14100 / 15000
Progress: 14200 / 15000
Progress: 14300 / 15000
Progress: 14400 / 15000
Progress: 14500 / 15000

🔁 Generator 30/30
Progress: 14600 / 15000
Progress: 14700 / 15000
Progress: 14800 / 15000
Progress: 14900 / 15000
Progress: 15000 / 15000

Saved 15000 samples to synthetic_fault_logs_final-2026-15k.csv

In [44]:
# fine_tune_gpt2.py
import pandas as pd
import torch
from torch.utils.data import Dataset
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling

# Load fault logs
df = pd.read_excel("fault-logs-o-ran-12k.xlsx", engine="openpyxl")
fault_texts = df["Fault Description"].astype(str).tolist()

# Tokenizer and GPT-2
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained("gpt2")

# Dataset
class FaultDataset(Dataset):
    def __init__(self, texts, tokenizer):
        self.examples = tokenizer(texts, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
    def __len__(self):
        return len(self.examples["input_ids"])
    def __getitem__(self, idx):
        return {k: v[idx] for k, v in self.examples.items()}

dataset = FaultDataset(fault_texts, tokenizer)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Training
training_args = TrainingArguments(
    output_dir="./gpt2-finetuned-fault-12k",
    per_device_train_batch_size=4,
    num_train_epochs=8,
    logging_steps=10,
    save_strategy="epoch",
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset,
    tokenizer=tokenizer,
    data_collator=data_collator
)

trainer.train()
model.save_pretrained("gpt2-finetuned-fault-12k")
tokenizer.save_pretrained("gpt2-finetuned-fault-12k")

/tmp/ipykernel_544054/2898927493.py:38: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

('gpt2-finetuned-fault-12k/tokenizer_config.json',
 'gpt2-finetuned-fault-12k/special_tokens_map.json',
 'gpt2-finetuned-fault-12k/vocab.json',
 'gpt2-finetuned-fault-12k/merges.txt',
 'gpt2-finetuned-fault-12k/added_tokens.json')

In [11]:
# generate_faults_from_gan.py
import torch
import csv
from torch import nn
from transformers import GPT2Tokenizer, GPT2LMHeadModel

# --- Generator class ---
class Generator(nn.Module):
    def __init__(self, latent_dim=100, output_dim=384):
        super().__init__()
        self.model = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.ReLU(),
            nn.Linear(256, 256),
            nn.ReLU(),
            nn.Linear(256, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim)
        )
    def forward(self, z):
        return self.model(z)

# --- Projector class (must match training structure) ---
class EmbeddingProjector(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(384, 768)
    def forward(self, x):
        return self.linear(x)

# Config
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
latent_dim = 100
K = 20
num_samples_per_gen = 60

# --- Load all trained generators ---
generators = []
for j in range(1, K + 1):
    G = Generator().to(device)
    G.load_state_dict(torch.load(f"trained_generator_{j}.pt", map_location=device))
    G.eval()
    generators.append(G)

# --- Load fine-tuned GPT-2 ---
tokenizer = GPT2Tokenizer.from_pretrained("gpt2-finetuned-fault")
tokenizer.pad_token = tokenizer.eos_token
gpt2 = GPT2LMHeadModel.from_pretrained("gpt2-finetuned-fault").to(device)
gpt2.eval()

# --- Load trained projector ---
projector = EmbeddingProjector().to(device)
projector.load_state_dict(torch.load("trained_projector-old.pt", map_location=device))
projector.eval()

# --- Generate and decode ---
decoded_outputs = []

with torch.no_grad():
    for g_idx, G in enumerate(generators):
        print(f"Generating from Generator {g_idx + 1}...")
        z = torch.randn(num_samples_per_gen, latent_dim).to(device)
        fake_emb = G(z)                          # [N, 384]
        projected = projector(fake_emb)          # [N, 768]

        for i, emb in enumerate(projected):
            input_emb = emb.unsqueeze(0).unsqueeze(1)  # [1, 1, 768]
            output_ids = gpt2.generate(
                inputs_embeds=input_emb,
                max_length=128,
                do_sample=True,
                top_k=50,
                top_p=0.95,
                pad_token_id=tokenizer.eos_token_id
            )
            decoded = tokenizer.decode(output_ids[0], skip_special_tokens=True)
            decoded_outputs.append((f"G{g_idx + 1}", f"Sample {i + 1}", decoded))
            print(f"✓ G{g_idx + 1}, Sample {i + 1}: {decoded[:60]}...")

# --- Save to CSV ---
output_file = "inference-data-new.csv"
with open(output_file, mode="w", encoding="utf-8", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["Generator", "Sample Number", "Generated Fault Description"])
    for row in decoded_outputs:
        writer.writerow(row)

print(f"\n✅ Saved {len(decoded_outputs)} samples to {output_file}")

/tmp/ipykernel_4393/1602663025.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  G.load_state_dict(torch.load(f"trained_generator_{j}.pt", map_location=device))
/tmp/ipykernel_4393/1602663025.py:53: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  projector.load_state_dict(torch.load("trained_projector-old.pt", map_location=device))

Generating from Generator 1...
✓ G1, Sample 1:  is not available. [ 0 ] could not assign _ rrc _ nr _ idx _...
✓ G1, Sample 2: .o.d.u.i.c.RequestInterfaceSetup() /home/oran/openairinterfa...
✓ G1, Sample 3:  ( 1 ; 31m [ nr _ rrc ] [ dl ] ( cellid bc614e , ue id 1 rnt...
✓ G1, Sample 4: .exe /home / oran / openairinterface5g / openair2 / pdrd / ‘...
✓ G1, Sample 5: .exe /home/oran/openairinterface5g/openair2/common/pfcp-sm.c...
✓ G1, Sample 6:  the server was not available for reading/writing. (In this ...
✓ G1, Sample 7:  ausdallas-nas-amfd[13098]: 02/13/2015 sgcpcd[12882]: 02/13/...
✓ G1, Sample 8:  ( ) failed! in rx _ rx _ nr _ prach _ ru ( ) / home / oran ...
✓ G1, Sample 9:  the table [ 0m # ‘ 2a31m ‘ hw ] received unsuccessful resul...
✓ G1, Sample 10: /nrf - oai - nf_config - ue 1 [ 2015 - 11 18 : 14 : 14 ] [ a...
✓ G1, Sample 11:  [ 0m [ nas ] sctp client connects[ 0 ] ( ) to ‘ ‘ ‘ 10. 0. ...
✓ G1, Sample 12:  [ 0m # [ 93m [ mac ] ue 2aa … : request release after ul fa...
✓ G1, Sample 13: , 22Nov44 – 17:44:58 srs-ran open5gs-scpd[14895]: [sgf_app] ...
✓ G1, Sample 14:  a [0m#[93m[SCTP] sctp_bindx() SCTP_BINDX_ADD_MACRATICON fai...
✓ G1, Sample 15: , the file could not be loaded. error: ogs - util - mongodb[...
✓ G1, Sample 16:  [ 0m # ‘ 1 ; 31m [ hw ] connect ( ) to 127. 0. 0. 1 : 4043 ...
✓ G1, Sample 17:  [ 0m # ” 0m [ phy ] received phy release request # [ 0m [ u...
✓ G1, Sample 18: /11/17 18:36:44.475] [amf_n2] [debug] Handle Deleted TxListU...
✓ G1, Sample 19: -band RRC-encoded file: /home/oran/openairinterface5g/openai...
✓ G1, Sample 20:  1 - ‘ ‘ 8 ‘ 1143 : ‘ c : 1635 srs - ran open5gs - pcfd [ 14...
✓ G1, Sample 21:  [ 0m # ” ssb 0mcmdline : ” failed ” to initialize ue with n...
✓ G1, Sample 22:  the parameters : value : int32 id : 000 file : / opt / o - ...
✓ G1, Sample 23:  the timer failed at sctime in section 2133.In config/udev/c...
✓ G1, Sample 24:  srs - ran open5gs-seppd [1495]: 02/13 14:00:44.476: [sepp] ...
✓ G1, Sample 25:  and ‘ ‘ ” 1 = 0030 pdrs ‘ downlink ” 0xe000 ‘ ‘ ‘ ‘ ‘ ‘ 95 ...
✓ G1, Sample 26:  to get to the server: /usr/src / cm / cm _ app ‘ ‘ ” config...
✓ G1, Sample 27:  the band is at the end of the band. open5g-band : upgs-band...
✓ G1, Sample 28:  the SAC was running. sudo yaml / home / oran / openairinter...
✓ G1, Sample 29:  is not enough to complete the ciphering. Decode the cipheri...
✓ G1, Sample 30:  ( sizeof ( buf ) * sizeof ( nr _ rrc _ ue ) ) failed! in cl...
✓ G1, Sample 31:  srs - ran open5gs-amfd[14976]: 02/12/17 14:53:35.298: [sbi]...
✓ G1, Sample 32: s_nr_info received RNT message ” 1, sctp_idx = 3, ue idx = 0...
✓ G1, Sample 33: .rrc.Injector :line :after :error :line :of Error creating t...
✓ G1, Sample 34: .m. PDT: AEG-IMSI 1130 PDT: SIBs (3GT/sIB-TX/SIB-TXE) Receiv...
✓ G1, Sample 35:  is a syntax error. Try the provided syntaxes[0m#[CONFIG] /h...
✓ G1, Sample 36: , 16 June 2018 09:58:54.736 [amf_app] [debug] Send out notif...
✓ G1, Sample 37:  ( 1 - 99 ) : nr - uesoft [ 0 ] : remove trigger - i from bu...
✓ G1, Sample 38:  to get the file open.Exiting execution at this time is not ...
✓ G1, Sample 39: .net.UnknownHostException: failed to resolve port 7777Rename...
✓ G1, Sample 40:  a guest May 21st, 2015 13,743 ‘ ‘ ‘ 21: ‘ openair2g [pfcc] ...
✓ G1, Sample 41:  the executioner thread releases a context-dependent error m...
✓ G1, Sample 42:  and ‘ ‘ sg ‘ ‘ 0 ‘ ‘ hw ‘ ‘ ‘ ‘ ‘ ‘ ‘ … no ds ” dl ‘ ‘ ‘ ‘ ...
✓ G1, Sample 43:  ( 1 - ‘ 0 ) failed! in rx _ rx _ pd [ dl ] ( ) / home / ora...
✓ G1, Sample 44:  [ 0m # ” gtpu ] ” result _ rx ” value is not properly initi...
✓ G1, Sample 45: : 22h[NR_APP] [dbi] … error while loading NR config file[PHY...
✓ G1, Sample 46:  of the app could not be configured.PeriodicityExiting execu...
✓ G1, Sample 47:  the file was skipped or not properly initialized.Exiting ex...
✓ G1, Sample 48: -03-17 13:00:44.928] [amf_app] [debug] Initializing NFTP cli...
✓ G1, Sample 49: -2023-12 14:44:21.303] [ngap] [error] Received unsuccessful ...
✓ G1, Sample 50:  is the time the client connects. The client connects, sends...
✓ G1, Sample 51:  the gnb.conf file. o.o.d.a.t.d.u.g.i.c.R.CellSIBConfigurati...
✓ G1, Sample 52:  for the current release. This release includes bug fixes, o...
✓ G1, Sample 53:  10 21 : 44 : 48 srs - ran open5gs - pcfd [ 1495 ] : 02 / 17...
✓ G1, Sample 54:

src / cm / cm _ inet. c : 543 couldn't open socket ‘ ” ‘ c...
✓ G1, Sample 55:  to be standardized. [3025-03-17 19:30:58.715] [sebaceous] [...
✓ G1, Sample 56:  as a result of the transfer of the State, the driver was ex...
✓ G1, Sample 57:  ( 1 - > 0 && nr _ in read _ sib1 _ bandcampfrm > 0 ) failed...
✓ G1, Sample 58:  this algorithm is not properly initialized, the numerator i...
✓ G1, Sample 59:  with a message "ERROR! RRCS " in the config file. /home/ora...
✓ G1, Sample 60: , ‘ 1 ; ‘ ‘ … } … ( numelt : ‘ 0 ) ” failed! in read _ du ‘ ...
Generating from Generator 2...
✓ G2, Sample 1: .js#[config] file.. /.. /. yaml file.. /. plmn#[debug] initi...
✓ G2, Sample 2: -1305[HW] og-eployd[149]: 02/12/2015 – 11:30:59.691: [sbi] W...
✓ G2, Sample 3: :00:00.152] [ngap] [debug] Send Tx Send Request to ngx[2025-...
✓ G2, Sample 4: -bind -u -r -r' o -l ‘ ‘ ‘ home / ‘ openair – ‘ openair2 / ‘...
✓ G2, Sample 5:  the value provided _ in the stream.sctp : number of bytes ”...
✓ G2, Sample 6: s - rrc - udrd [ 0 ](.. / lib / sbi / nr - sm. c : 264 ) feb...
✓ G2, Sample 7: . 0m [ nas ] [ nas _ rrc ] [ ue id 1 ] received nas _ rrc _ ...
✓ G2, Sample 8: : 1243PM PDT | 13:16:54.240] [amf_app] [debug] Update UE Slo...
✓ G2, Sample 9:  [ 0m # ” 0m [ nr _ rrc ] received retry registration with n...
✓ G2, Sample 10:  for AMS parameters, e.g. TxSI_NR_ADD_DATA, TxSI_NR_INDEX_IN...
✓ G2, Sample 11: -sep-1-5pb22-bde5c196f78] [amf_app] [error] Failed to connec...
✓ G2, Sample 12:  ( 1 / 3 ) failed! in rx _ prach _ ru ( ) / home / oran / ‘ ...
✓ G2, Sample 13: . 0. 0. 1: [pool. dl ] [ debug ] received client release mes...
✓ G2, Sample 14:  ( 1 * dl _ rrc _ nr _ prach _ ru ) failed! in clone _ nr _ ...
✓ G2, Sample 15:  [ 0m # ‘ hw ] connect failed : connection refused [ 0m [ ‘ ...
✓ G2, Sample 16:  12 23:44:54 srs-ran open5gs-drd[13002]: 02/12 23:44:54.232:...
✓ G2, Sample 17: .exe –no-interval-1 64325 > nr _ prach _ ‘ check ‘ value ” :...
✓ G2, Sample 18: , the number of bytes in the buffer, a value between 0 and 1...
✓ G2, Sample 19:  [ 0m [ dl ] sctp_bindx : error while binding socket dl [ 0m...
✓ G2, Sample 20:  [ 0m [ nas ] [ ue 0 ] received nas _ downlink _ data _ ind ...
✓ G2, Sample 21: , 1322 : 21 : 10 srs - ran open5gs - pcfd [ 13098 ] : 02 / 1...
✓ G2, Sample 22:  ( 1 - ‘ 0 ” ‘ ‘ ” = 0 ) failed! in rx _ pd [ ' inst _ rrc ]...
✓ G2, Sample 23:  and ‘ ngap _ ngap _ configval. – asn1 ngap _ configval : le...
✓ G2, Sample 24:  - - 1 [ pool - 2 - thread - 1 ] o. o. d. s. s. c. filereade...
✓ G2, Sample 25:  1 [displayText] Logged in to NFband for registration as an ...
✓ G2, Sample 26: : 32FpuCpuList: Selected CUDA Tasks: Selected 3640F - 21F - ...
✓ G2, Sample 27:  that the subscription is authorized. Send a message to the ...
✓ G2, Sample 28:  not, it is a common problem in Linux environments. Linux is...
✓ G2, Sample 29: , the app is not properly initialized.Binary file ‘ invalid ...
✓ G2, Sample 30:  10 27 : 54 : 48 srs - ran open5gs - l2d [ 14224 ] : 02 / 13...
✓ G2, Sample 31:  [ 1 ; 31m [ rrc ] unknown ciphering algorithm " utf8 " in s...
✓ G2, Sample 32: , 12 August, 08:36:54 srs-ran open5gs-app-udrd-scpd[14876]: ...
✓ G2, Sample 33:  that, the cell is read only and all parameters out of order...
✓ G2, Sample 34:  the config file: file .. /.. /.. / projects / generic - nr ...
✓ G2, Sample 35: srs-ran open5gs-rfs-udl-scpd [15220]: [sbi] WARNING: receive...
✓ G2, Sample 36:  and ‘ 1; sctp_nr_idx = 4; nr_idx ” 0010101; sctp_tcp_idx : ...
✓ G2, Sample 37:  [ 0m # ‘ 1 ; 31m [ e1ap ] unknown ciphering algorithm ” e1a...
✓ G2, Sample 38: , 2025-04-21 18:04:54.210] [sctp] WARNING: [7] Failed to con...
✓ G2, Sample 39:  the state 0x7f failed: Error loading appxpath_config from g...
✓ G2, Sample 40:  12 22 : 44 : 59 srs - ran open5gs - bsfd [ 14963 ] : 02 / 1...
✓ G2, Sample 41:  ausdupi1 - udm / lib / openairinterface5g / nr _ pdrd / nr ...

✓ G2, Sample 42: .net.UnknownHostException: failed to initialize Fd [0] (../s...
✓ G2, Sample 43:  the sib1.conf file. …. ….. /.. /etc/rpi/conf. …. ….. /etc/r...
✓ G2, Sample 44:  at the time of registration. (3) Subscriber provided a curr...
✓ G2, Sample 45: , 93rd Session - NRG-HCTS-NR-01 Session# [2028-03-11 14:35:1...
✓ G2, Sample 46:  - 1 [ 1 ; 31m [ rrc ] unknown ciphering algorithm ” e2aa7 #...
✓ G2, Sample 47:  - 1 [ pool - 1 ] [ peer ] file.. /.. /.. / targets / projec...
✓ G2, Sample 48: [ 0m # ” 0m # ” 0m # [ 93m [ phy ] connect() to ‘ ‘ 0m ‘ ” f...
✓ G2, Sample 49:  to connect to the server (eg, 127.0.0.1:2543)Feb 17 22:21:0...
✓ G2, Sample 50:  to connect to the server. o. o. d. e. h. s. s. s. s. v. e. ...
✓ G2, Sample 51:  of 6.0.1 [drdw] Remove "libdrd[0].plmn" line 93. Remove "-o...
✓ G2, Sample 52:  that ran at a time of 10:30am PST for the current session.P...
✓ G2, Sample 53: : 02 / 13 / 11 : 44 : 59. 106 : [ sbi ] warning : [ 14100714...
✓ G2, Sample 54:  this section. Add a section ‘ ‘ ‘ ‘ down ‘ ‘ ” down ” down ...
✓ G2, Sample 55:  [ 0m # ” 0m [ EMD5 ] failed to connect to ‘ 0m [ nr _ rrc ]...
✓ G2, Sample 56: , 162323ASP-SCTP:[dbi-pfcp] WARNING: Received TxPeriodicAsso...
✓ G2, Sample 57:  ( 1 / nr - openair1 ) ” 00h ” ssi ” 1 : ” ssi shutdown ” no...
✓ G2, Sample 58: . 12:44:53 srs-ran open5gs-gswcd[12419]: 02/12/12 14:44:53.2...
✓ G2, Sample 59:  and ‘ 0x1f failed! in read _ du ‘ dl _ app ‘ nr _ nr _ ‘ ch...
✓ G2, Sample 60:  the config file. o ‘ o ‘ ‘ ‘ ‘ c : ‘ ‘ o ‘ ‘ ‘ ‘ down ” dow...
Generating from Generator 3...
✓ G3, Sample 1: .config;.. dl_config_check_nr_pager:cell_id:2aa, inst:10 # ”...
✓ G3, Sample 2:

93:04:40 srs-ran open5gs-sgwcd[12882]: 02/13 22:21:45.256:...
✓ G3, Sample 3: , cnxpd [ 0 ](.., ‘ ‘ ‘ ‘ ‘ ‘ ” ‘ ‘ ” ‘ ” 0 ) ‘ failed! in c...
✓ G3, Sample 4:  be the current sessionID : 255Genode: 00007SCTP : 00101SCTP...
✓ G3, Sample 5:  all the file system information (x86_64, yaml, rdf, …). Add...
✓ G3, Sample 6:  - 1 ( ‘ ” 0 ) failed! in rx _ nr _ prach _ ru ( ) / home / ...
✓ G3, Sample 7: .o.d[NR_APP] Handle error while encoding NRF (../src/nr-app....
✓ G3, Sample 8:  [ 1 ; 31m [ sctp ] check the integrity of the SSI section o...
✓ G3, Sample 9:  the app has been added...![ 0 ] failed! in read_du_cell_inf...
✓ G3, Sample 10:  to get the band position in the band, i.e. 8C:CONFIG_INDEX_...
✓ G3, Sample 11:  the value is r = ( 1 - > 0 & & ( sizeof(buf)) / sizeof(nr_b...
✓ G3, Sample 12: : 21m [ ngap ] [ dl ] seppd [ 3 ] handle association failure...
✓ G3, Sample 13: s[-1] (cellID bc614e, UE ID 1 RNTI 1 (cellID bc614e, UE ID 1...
✓ G3, Sample 14: , 2025. ‘ ‘ 0 ‘ ‘ ‘ ” 99 ‘ ” 1844 ‘ ‘ ‘ ‘ ” ‘ ‘ ‘ ‘ ” ” ” ” ...
✓ G3, Sample 15: : mnc_app_idx: 5GCRelevantIndex: 0000000File: /opt/ocfd/oc_c...
✓ G3, Sample 16: -ran open5gs-1-seppd[15095]: 02/13/2015 - 03/13 13:54:54.252...
✓ G3, Sample 17:  – 2 min. srs-ran open5gs-udrd [14240]: 02/13/12 14:00:53. 7...
✓ G3, Sample 18:  for the app.xaml file. #!/usr/lib/xmpp/xmprach.c line 8: du...
✓ G3, Sample 19:  ( nr - thread - 1 ) : seppd [ 0 ] : [ 44 ] error : ogsfd ( ...
✓ G3, Sample 20:  in the cell.In the cell.In the cell.In the cell.In the cell...
✓ G3, Sample 21:  a guest Oct 17th, 2015 93 Never a guest93Never! / >Never! /...
✓ G3, Sample 22:  the cell is initialized with the length int(nr_nr_cell) and...
✓ G3, Sample 23: -bind-scsi-udev-xrp: [13040] WARNING: PDU SessionReject fail...
✓ G3, Sample 24: .exe " ‘ " & -u " ‘ 0 " & -r " ” " & -p " ” " : " ‘ 0 " & -R...
✓ G3, Sample 25: 1 /etc/host.aliases.conf file.. /etc/host.aliases.conf line....
✓ G3, Sample 26: /25-03-21 12:45:44.949: [sbi] WARNING: [15acd3a-ea30-41ef-96...
✓ G3, Sample 27:  this section is to be read from a file, and after the file ...
✓ G3, Sample 28: , the application idx = 8, format = ue, buffer = 8, priority...
✓ G3, Sample 29: . plmn. c : 1843 as plmn sessionhandler : [ plmn ] aborting ...
✓ G3, Sample 30:  that was a common thread in the global search pool, and the...
✓ G3, Sample 31:  the subscription data is not available, the subscription is...
✓ G3, Sample 32: , 2025.1 [pool-1-gPP] o.c.c.d.o.r.r.cbsclientConfigurationIn...
✓ G3, Sample 33:  in the configuration file: path /opt / lib / pfcp-ng. c : 7...
✓ G3, Sample 34:  [ 1 ; 31m [ ENCRYPTION ] remove ue from NRx buffer [ dl ] (...
✓ G3, Sample 35:  the session has been requested. No session information avai...
✓ G3, Sample 36:  ( sizeof ( rrc_list )) failed! in rrc_nr ( posix ) / home /...
✓ G3, Sample 37:  srs - ran open5gs - ausfd [ 14963 ] : 02 / 13 / 12. 10. 16....
✓ G3, Sample 38: : 1243 p.m. PDT (6 May) 08:25 p.m. PDT (908):53 PDT (PDO): N...
✓ G3, Sample 39:  be provided, the current value of rx_nr_offset is 4 and no ...
✓ G3, Sample 40:  (posix ) : sw error : ent : 255 inst : 255 proc id : 000 fi...
✓ G3, Sample 41:  all file and src/app.c line 37 : duplicate setting name [ p...
✓ G3, Sample 42:  and ogWgInception : error while encoding filename[0m[PHY] s...
✓ G3, Sample 43: , 21 Dec – 21:53:44.716]: [sctp] WARNING: [14] Failed to con...
✓ G3, Sample 44:  that position has already been added.
In the config file, t...
✓ G3, Sample 45:

SIGRP: Received retry registration with NR, NRF (0xc00043f...
✓ G3, Sample 46:  2    2  7 srs - ran 5    5 minnclos  3ai ” ( nrf ) nrf _ ch...
✓ G3, Sample 47:  ( 1 - ‘ ‘ 0 ‘ ‘ ‘ ‘ ‘ ‘ ] ‘ : [ 0 ” 0m ‘ rrc ” 1 ” ‘ ” 0m ”...
✓ G3, Sample 48: .exe [0m[1;31m[PHY] unknown ciphering algorithm "aa3" in sec...
✓ G3, Sample 49: . 12 22 : 21 : 14 srs - ran open5gs - udrd [ 13098 ] : 02 / ...
✓ G3, Sample 50:  notre d'aiusg assoc id : 000 file.. /.. / targets / project...
✓ G3, Sample 51: [ 0m #[ 93m [ mac ] unknown mac address( 8192 ), authorized ...
✓ G3, Sample 52: .app.config.json : error [config_get] /home/oran/openairinte...
✓ G3, Sample 53:  : [ dl ] ogs - seppd [ 124 ] ( ) SBI refused connect after ...
✓ G3, Sample 54:  13 23 : 44 : 59 srs - ran open5gs - udrd [ 14882 ] : 02 / 1...
✓ G3, Sample 55:  - 1 file - o - du - ldrd - o - du - ldrd - localdomain | co...
✓ G3, Sample 56:  ( cell : ue 0 ) error : ent : 255 inst : 255 proc id : 000 ...
✓ G3, Sample 57: : 1044:54 srs-ran open5gs-udrd[12900]: 02/13 22 07:59:04.476...
✓ G3, Sample 58:  of the 1/16th, 2025, to 16:00 UTC (16:00 – 16:59 IST)In an ...
✓ G3, Sample 59:  - 02/11 16:54:53.600] [sebaceous] [debug] Update UE NG Sess...
✓ G3, Sample 60:  notifies the services provider (NGP) of the requested subsc...
Generating from Generator 4...
✓ G4, Sample 1:  at the time, the file was down and it was not available at ...
✓ G4, Sample 2: , 2025. The projects to be supported are: CPP (Centre for th...
✓ G4, Sample 3:  srs-ran open5gs-sfd[13095]: 02/13/2015 srs-ran open5gs-sfd[...
✓ G4, Sample 4:  at the time, the file was requested.Ack – ran an open5g, wi...
✓ G4, Sample 5: 1; -u0m[PHY] Received TASK from address 127.0.0.1:4043; port...
✓ G4, Sample 6:  is 0 )[ 0x1a04a4a0 ] [ dl ] ( cellid bc614e, ue id 1 rnti 2...
✓ G4, Sample 7:  [ 895 ] : 02 / 13 / 2025 : 21 : 16. 876 : [ sbi ] warning :...
✓ G4, Sample 8:  ausdicated.exe file.. /home/oran/openairinterface5g/openair...
✓ G4, Sample 9:  [ 0m # ‘ 1 ; 31m [ hw ] connect ( ) to ‘ ‘ ‘ ‘ 40 ” ” ” ) f...
✓ G4, Sample 10:  that the client is not running SCTP (0.0.0.10) or Transport...
✓ G4, Sample 11:  is 1 time (1 hrs ago) in thread setup for GPRS_APP: creatin...
✓ G4, Sample 12:  1 h : 44m [ nr _ rrc ] [ sbi ] [ debug ] received NRTP resp...
✓ G4, Sample 13: .js file.excludes ( ) && sctp : error ( ) / home / oran / op...
✓ G4, Sample 14: -93-12 18:59:44.298] [amf_app] [debug] SBI-ASDN ran amf-scan...
✓ G4, Sample 15:  [ 0m # ‘ 0m [ sepp ] nrf _ rrc _ sib1 : connection refused ...
✓ G4, Sample 16:  22 13:58:21 srs-ran open5gs-pcfd[14924]: [sbi] WARNING: Rej...
✓ G4, Sample 17:  and ran in the 1,000-run section with 0 failed, errno 200 o...
✓ G4, Sample 18:  [ 0m [ hw ] sctp_bindx() : failed registration with nrf (.....
✓ G4, Sample 19:  2 – dl: [ dl ] check the integrity of the amf[ 1 ] section....
✓ G4, Sample 20:  1 ] o. o. d [ s. e. c. p. d. e. h. c. loc. cbsclientconfigm...
✓ G4, Sample 21: : 02/01/17 21:00:16.235[amf_app] WARNING: [bdf8ae0d0-ea30-41...
✓ G4, Sample 22: .conf file.conf : syntax error while encoding file.. /.. /.....

✓ G4, Sample 23:  [9340] [amf_app] [debug] Initializing SBIX SEQ (../lib/sbi/...
✓ G4, Sample 24:  28 [displayText] [SIC] [com.google.gson.jsonobjective.inter...
✓ G4, Sample 25:  - 12:54:35 srs-ran open5gs-udrd[14925]: 02/13/12 13:54:35.6...
✓ G4, Sample 26:  this section ( ‘ ‘ ” ) and ‘ ‘ ” ” ” ” ” ” ” ” ” ” ” ” ” ” ...
✓ G4, Sample 27:  10 23:54:53 srs-ran open5gs-scpd[15095]: 02/10 23:54:53.436...
✓ G4, Sample 28:  the config file : /opt/app-config.yaml file.. /.. /.. / tar...
✓ G4, Sample 29: , 12 May 2018 19:21:46 srs-ran open5gs-nbcs-seppd[14930]: [s...
✓ G4, Sample 30:  ( nr - numelt > 0 && nr - > max ( 1 / nr - numelt * sizeof ...
✓ G4, Sample 31:  this section is not a section of the app.it is a configurat...
✓ G4, Sample 32:  1 h 1 h - 2 nr - 1 ; s ssb - app ] info : [ 142a196a - ea30...
✓ G4, Sample 33:  ( 1 / 3 ) failed! in rx _ prach _ ru ( ) / home / oran / ‘ ...
✓ G4, Sample 34:  the numerals with a periodicity of 0.05 (or, the numerals w...
✓ G4, Sample 35:  [ 0m # ‘ 1 ; 31m [ nr _ rrc ] received registration reject ...
✓ G4, Sample 36: , 1822-03-17 19:44:46.436] [smf_app] [debug] Initializing FS...
✓ G4, Sample 37:  notifies the driver after notification of unsuccessful regi...
✓ G4, Sample 38: s [ 0m # ” [ 93m [ sctp ] [ ue 1 ] request release after ul ...
✓ G4, Sample 39:  the thread execution is complete.In the current thread cont...
✓ G4, Sample 40:  ausdrd [ 0 ] ( sctp ) connect : session created : 1428 byte...
✓ G4, Sample 41:  this release the client has been deleted, the thread messag...
✓ G4, Sample 42:  of 2025, the State of New Jersey, the state for the 13-coun...
✓ G4, Sample 43: , 1844-03-21 08:44:44.605] [sctp] [debug] Received SEQ reque...
✓ G4, Sample 44: , 12hrsrsrs: Session aborted[1244] ogs-ran open5gs-rgn-sm.ce...
✓ G4, Sample 45:  and ‘ ‘ ‘ 2 – ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ 1 file. c : 28 ” 0 – … srs - ...
✓ G4, Sample 46:  for amf_pf_app_idx() /home/oran/openairinterface5g/openair2...
✓ G4, Sample 47: , 1442-03-21 19:59:21.363] [amf_app] [debug] Initializing UE...
✓ G4, Sample 48:  – no information provided – no data available – no ‘ ” data...
✓ G4, Sample 49:  – – – – – – – – – – – – – – – – – – – ‘ 1 – 4 – – – 10 – – ...
✓ G4, Sample 50:  not, it was a computer problem.I ran the rxconfig in order ...
✓ G4, Sample 51: , the band was, in fact, a band of all the 16 band members (...
✓ G4, Sample 52:  in the thread.module.exceptions.PHY() failed, errno(111)In ...
✓ G4, Sample 53: : 03/13 19:54:58.854] [amf_n2] [debug] [debugged the associa...
✓ G4, Sample 54:  1 min | config | ind -- no-interval - 5 | o - du ‘ gtpu | [...
✓ G4, Sample 55: .exe -C 643 cmdline : : : : : : util _ load _ sib1inter ” cm...
✓ G4, Sample 56: [0m[NGAP] Received unsuccessful result for SCTP request [0m[...
✓ G4, Sample 57:  a sbsclient ‘ ” client ” conﬁg ” sbsclient : ‘ clientconfig...
✓ G4, Sample 58:  the client connects, the app is configured to send the requ...
✓ G4, Sample 59: , ‘ 0x9 = ‘ 0x3a8f78 ” 0x3a88 ” 1 = ‘ ‘ ‘ ” ‘ ‘ ‘ ‘ ” ‘ ‘ ” ...
✓ G4, Sample 60: -03-21 08:21:53.256] [amf_app] [debug] Handle a UE Session I...
Generating from Generator 5...
✓ G5, Sample 1: . The session id is "40" in the config file. Session is not ...
✓ G5, Sample 2: , 12hrs:00p - 12hrs:06p [geo-amfd] [debug] received handshak...
✓ G5, Sample 3:  [ 31 - 03 - 17 07 : 54 : 48. 550 ] [ amf _ n2 ] [ debug ] S...
✓ G5, Sample 4:  ( ) failed! in read _ rrc _ nr _ config _ ‘ conﬁg ” gNB ” c...
✓ G5, Sample 5:  to 16:00 p.m. PDT, the SBI-ran received a warning from the ...
✓ G5, Sample 6:  is the standardized dpi. No setting parameters have been pr...
✓ G5, Sample 7:  a guest Dec 17th, 2015 95 Never a guest95Never, ‘ ‘ ‘Never ...
✓ G5, Sample 8:  be available for a release after the current number of proj...
✓ G5, Sample 9:  [ 1 ; 31m [ rrc ] unknown integrity algorithm ” sctp _ prac...
✓ G5, Sample 10: , ‘ 0x1 ( nr _ rrc ‘ 0 ) failed! in rrc _ nr _ ruination ( )...
✓ G5, Sample 11:  : 1822 : 21 srs - ran open5gs - scpd [ 12926 ] : 02 / 13 / ...
✓ G5, Sample 12: .t.u.d.u.r.c.app.x.api.i.c.iProviderInterfaceSetupResponse()...
✓ G5, Sample 13: , ‘ 0x1 [ sctp ] unknown ciphering algorithm ” e1g ” nr _ ue...
✓ G5, Sample 14:  the configuration file. o. d. c. s. s. c. s. i. filereader ...
✓ G5, Sample 15:  [ 0m [ nr _ rrc ] [ dl ] ( cellid bc614e, ue id 1 rnti 2aa ...
✓ G5, Sample 16: -NR-7 (cell.nr-band12): Received SBCS error message ERR-01 (...
✓ G5, Sample 17:  to remove all duplicate file or directory ‘ 0x2F ‘ gtpu-sm....
✓ G5, Sample 18:  10 [pool-2-thread-1] o.o.d.a.g.o.r.s.r.c.FileReader : Error...
✓ G5, Sample 19: -7 failed!errno ( 93 ) : syntax error[ - 1 ] (.. / src / cm ...
✓ G5, Sample 20: s [ERROR]: Retry registration with NF (../lib/airsoft.target...
✓ G5, Sample 21: s: 02h44m [sbi] WARNING: [14449328-ea30-41ef-9631-7d9ac4943b...
✓ G5, Sample 22: , 0m[E1AC3]: [sctp] Retry registration with NRF (../lib/sctp...
✓ G5, Sample 23:  ack_pf _ nr _ sa_bandtable _ idx : 10 inst: ‘ failed, errno...
✓ G5, Sample 24:  at 11am PDT. (Feb 13 22:30:21 GMT): [sbi] WARNING: Failed t...
✓ G5, Sample 25:  notifies the client the value of the _ NSI_APP_IDx() subscr...
✓ G5, Sample 26: s1 [ config ] file.. /.. / targets / projects / generic - nr...
✓ G5, Sample 27: .exe" failed!In config/udev/RRC_APP_RRC_RRC_PROJECTS.c:2543c...
✓ G5, Sample 28:  22 : 44 : 59 srs - ran open5gs - smfd [ 14963 ] : 02 / 13 /...
✓ G5, Sample 29: , it could have been a 1-1. The result is not available in t...
✓ G5, Sample 30: , 2025, the U.S. Information Assurance (IaaS) system has fai...
✓ G5, Sample 31:  it is not necessary to remove the amf, gfp, libfd, gnb. c :...
✓ G5, Sample 32:  – the client sends the request to the server for a Session ...
✓ G5, Sample 33:  ( 1 - ‘ ‘ ” 0 ‘ ‘ ” 1 - 2 ) failed! in read _ du ‘ data. pl...
✓ G5, Sample 34:  srs-ran open5gs-scpd [13098]: [sbi] WARNING: Retry registra...
✓ G5, Sample 35:  the parameters for the RCTS_RRCS and RCTS_MACRxceptions : 1...
✓ G5, Sample 36:  be added to the system parameters, e.g.: sizeof(TXR) / size...
✓ G5, Sample 37:  amf_inet ‘ amf_rval. c : 1843 regs debug conf _ rrc ” id 0x...
✓ G5, Sample 38:  at 21:43:16 srs-ran open5gs-drd[14963]: 02/13/15 19:44:16.7...
✓ G5, Sample 39:  the server is configured to send Tx to the client.request :...
✓ G5, Sample 40: -de-l2-rls -O -SCTP -SCTP_SERVICE:PHyPRIMARY_APP_IND:APP_ID ...
✓ G5, Sample 41: s-ran open5gs-pr-ngap-du-l2-x86_65-sc-sm.c:1043#prf-du-l2-x8...
✓ G5, Sample 42: , ‘ 0xe000 ‘ hw ‘ ‘ ‘ ‘ 0 ‘ ‘ 95 ] : check the current buffe...
✓ G5, Sample 43:
, / nr - > sctp - uesoft - 2 > nr - thread - 1 : [ 0 ] fail...
✓ G5, Sample 44: .exe ‘ ‘ 5 ) failed! ( 1 ) / ‘ 2 – ‘ ‘ 3. 4 ) failed! for i ...
✓ G5, Sample 45: , 27 23 : 44 : 58 srs - ran open5gs - udrd [ 13882 ] : 02 / ...
✓ G5, Sample 46: , 16 May 2015 08:53:16 srs-ran open5gs-md[13363]: 02/13/2015...
✓ G5, Sample 47:  (cell. xs[nr_nr_cell] = 0; num_nr_cell_idx = 0; } #[0m#[93m...
✓ G5, Sample 48:  [NR_CLIENT_IP] 0000000 - failed: registration failed [PUBLI...
✓ G5, Sample 49:  to sgcp _ transport _ rrc _ config _ check _ length 5 : ” (...
✓ G5, Sample 50: , RAR 1 = ‘ 0, 1 = 255, 2 = 106 failed, 3 = ‘ 0 (cell) ‘ ” ”...
✓ G5, Sample 51:  ( posix ) : sw error : ent : 255 inst : 255 proc id : 000 f...
✓ G5, Sample 52: , 1631:17 srs-ran open5gs-pd[13095]: 02/13/2015 – 03:58:24.2...
✓ G5, Sample 53:  the band is releasing a new album to promote the band.In or...
✓ G5, Sample 54:  be added to the list of open_s_band() : the global getband(...
✓ G5, Sample 55:  the config file : /home / oran / openairinterface5g / opena...
✓ G5, Sample 56: . 1:42:44 srs-ran open5gs-md[13098]: 02/13/2015 srs-ran open...
✓ G5, Sample 57:  28 [pool-2-thread-1] o. o. d. c. s. s. c. filereader : erro...
✓ G5, Sample 58:  – provided all parties have the requested information; no r...
✓ G5, Sample 59:  to amf_gPP_idx() : invalid value in gPP_idx_offset() /home/...
✓ G5, Sample 60:  [ 1 ; 32 srs - > = 4 ] failed : retry registration with nrf...
Generating from Generator 6...
✓ G6, Sample 1: , 22 Oct - 16:54:15 srs-ran open5gs-pcfd[13098]: [pcf] WARNI...
✓ G6, Sample 2: , 2025. – SIBs ‘ sib1 ‘ ‘ ‘ ‘ ‘ ‘ sib1. – 2130. – ‘ sib2. – ...
✓ G6, Sample 3:  (posix-> x : 32 ) failed! in clone_nr ( ) / home / oran / o...

✓ G6, Sample 4: -NR-3f-sgfr-amfd[13900]: [sbi] WARNING: [7] Failed to assign...
✓ G6, Sample 5:  1 [ gtpu ] unknown format d [ hw ] initiating sync transfer...
✓ G6, Sample 6:  the system was unsuccessful. Try again later. No data avail...
✓ G6, Sample 7:  to get the client to start up.I ran the configuration file ...
✓ G6, Sample 8: 1 session#[0m#[93m[GCC] [debug] A gnb request was received f...
✓ G6, Sample 9:  and GPRS (256), and FPU (256), the SCTP module is running.
...
✓ G6, Sample 10: , 1 ( ‘ 0 ‘ ‘ ‘ ‘ 0 ) failed! in encode_numerology ( ) / hom...
✓ G6, Sample 11:
 ( nr - > 0 ) failed! in clone _ rrc _ nr _ conﬁg ‘ config ...
✓ G6, Sample 12:  this time. Give the band the time to reactivate and start t...
✓ G6, Sample 13:  and ‘ ‘ – provided a result with no value, informing the cl...
✓ G6, Sample 14: .exe / og - ldrd / uesoft ‘ ‘ vai ‘ - pdss ”common / uesoft ...
✓ G6, Sample 15:  to read config_list_size() /home/oran/openairinterface5g/op...
✓ G6, Sample 16:  is 0xe000, ” hw ” is the current buffer length (in bytes) ”...
✓ G6, Sample 17:  notifies the application execution and handling after sendi...
✓ G6, Sample 18:  - 1 ; 16 srs - ran open5gs - udrd [ 1698 ] : 02 / 13 / 12 ‘...
✓ G6, Sample 19:  13 23:44:43 srs-ran open5gs-pd[13098]: [pfcp] WARNING: [7] ...
✓ G6, Sample 20:  [ 0m [ nr _ rrc ] received an SCTP message, encoding it pro...
✓ G6, Sample 21: .exe [1296] (debug) Failed to initialize UE 4G Subsystem for...
✓ G6, Sample 22:  - 17 22 : 54 : 27 srs - ran open5gs - pcfd [ 13098 ] : 02 /...
✓ G6, Sample 23:  – 02 / 13 / 10 : 00 : 54. 535 ] [ amf _ n2 ] [ debug ] rece...
✓ G6, Sample 24:  [ 1 ; 31m [ seppd [ 124 ] : [ sbi ] warning : retry registr...
✓ G6, Sample 25: : [ 0m # ‘ 0m [ … ‘ i ] … ue 2aa … nf ” c : … error ” c : … ...
✓ G6, Sample 26: .plist file: file.. /.. /.. / targets / projects / generic -...
✓ G6, Sample 27:  is a thread-mesh algorithm and has been standardized for th...
✓ G6, Sample 28:  1 - 50m [ nas ] [ ue 2a02a0 ] ( nrf ) sends ue 1 request fo...
✓ G6, Sample 29:  at the start.sctp:service registration failed, errno(111)Fe...
✓ G6, Sample 30:  at 18:30:54 srs-ran open5gs-app-debugged-md[14963]: 02/13 1...
✓ G6, Sample 31:  for the current session. (.. / lib / gson / ‘ ‘ app. c : 28...
✓ G6, Sample 32:  is 1 (1 ‘ ‘ ‘ ‘ 0 ) ‘ ‘ ‘ nr _ ‘ numelt : length 4 in secti...
✓ G6, Sample 33:  sctp_bindx() : error while binding socket error cbs_client ...
✓ G6, Sample 34:  ( 0m [ nas ] [ ue 0 ] received nas _ data _ ind : length 4,...
✓ G6, Sample 35:  amf | gnb - seppd [ 14920 ] : 02 / 13 / 16 / 18. 4. 7 : [ s...
✓ G6, Sample 36:  (posix - 1 ) : 02 / 19 / 09 / 17 srs - ran open5gs - pcfd [...
✓ G6, Sample 37:  for the current session. # [0m# [95m ‘ rrc ‘ hw ] connect f...
✓ G6, Sample 38:  and ‘ dl ‘ ‘ ‘ ‘ ‘ ‘ dl ” ‘ ‘ ‘ ‘ ‘ dl ‘ ‘ ‘ ‘ ‘ ‘ ‘ dl ‘ ‘...
✓ G6, Sample 39:  this is a check on the state of the rrc _ rrc _ rrc _ confi...
✓ G6, Sample 40: s _ ru ( ) : sw error : ent : 255 inst : 255 proc id : 000 f...
✓ G6, Sample 41:  the sgPRs data binding the gPRs to the gPRs environment var...
✓ G6, Sample 42:  1 ( ) failed! in rx _ rx _ prach _ ru ( ) / home / oran / ‘...
✓ G6, Sample 43: 1 00:00:58.256] [sctp] [debug] Update UE Filtering for PDU-1...
✓ G6, Sample 44:  this session, it was time to check out the current state of...
✓ G6, Sample 45:  [ 93 ] : 12 srs - ran open5gs - pcfd [ 13098 ] : 02 / 13 / ...
✓ G6, Sample 46:  28 Sep 13 22:24:25 srs-ran open5gs-pd[13196]: 02/13 22:24:2...
✓ G6, Sample 47:  ( 1 / 1033 ) : 16 srs - ran open5gs - udrd [ 12435 ] : 02 /...
✓ G6, Sample 48: .exe file.. /.. /.. / targets / projects / generic - nr - 5g...
✓ G6, Sample 49:  the session is complete, the session id is : 1066 and the s...
✓ G6, Sample 50:  the client connects, the server sends the requested data an...
✓ G6, Sample 51: 1 file.. /.. /.. / targets / projects / generic - nr - 6gc /...
✓ G6, Sample 52:  - 7 [ pool - 1 ] sctp : send Tx information transfer failur...
✓ G6, Sample 53:  the configuration file. o - o - dl _ config _ load _ config...
✓ G6, Sample 54:  the file ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/gnb....
✓ G6, Sample 55:  1 - 10 srs-ran open5gs-pd[14922]: 02/12/15 srs-ran open5gs-...
✓ G6, Sample 56:  is not available for the requested application.In the confi...
✓ G6, Sample 57: . 1:14 srs-ran open5gs-amfd[149] (amf_app): [pf_sbi] WARNING...
✓ G6, Sample 58:

0m[RRC] unknown ciphering algorithm "n2oft" in section "se...
✓ G6, Sample 59:  ( 1 - ‘ ‘ ‘ 0 ‘ ‘ ‘ ‘ 1 ” ) failed! in read _ du ‘ dl ‘ con...
✓ G6, Sample 60:  is the length of the file. Parameters: file - a file name.p...
Generating from Generator 7...
✓ G7, Sample 1:  ( posix ) : sw error : ent : 255 inst : 255 proc id : 000 f...
✓ G7, Sample 2:  to the current time frame.CMDLINE:~ /opt/Rrc - udrd /opt/Rr...
✓ G7, Sample 3:  - 0m [ nr _ rrc ] [ dl ] received handshake success _ nr _ ...
✓ G7, Sample 4:  for the band to have the bandwidth, provided that the reque...
✓ G7, Sample 5:  [ 0m # ” 0m [ ” / o ‘ / rrc ] unknown ciphering algorithm ”...
✓ G7, Sample 6:  srs-ran open5gs-scpd [13098] (...) failed: failed to initia...
✓ G7, Sample 7:  sib1. du ‘ ‘ sib1. du ‘ ‘ hw ‘ ‘ ‘ ‘ … ‘ hw ‘ ‘ ‘ ‘ ‘ ‘ ” ‘...
✓ G7, Sample 8: , 1815:21:21 srs-ran open5gs-smfd[14927]: 02/12/1815:21:21.6...
✓ G7, Sample 9:  the session has been ran.Received SCTP request (3 bytes), e...
✓ G7, Sample 10: : [13073] [amf_app] [debug] Update UE Registration State#[0m...
✓ G7, Sample 11:  a guest Dec 16th, 2015 1,722 Never a guest1,722Never

Not a...
✓ G7, Sample 12:  ( 1 * length - 1 ) failed! in clone _ pdru () / home / oran...
✓ G7, Sample 13: -1-31-17 13:59:40.619] [amf_app] [debug] Received an error w...
✓ G7, Sample 14:  sctp_debugged : error while encoding file ‘ file ” conﬁg ‘ ...
✓ G7, Sample 15:  12 19 : 21 : 21 srs - ran open5gs - pcfd [ 14927 ] : 02 / 1...
✓ G7, Sample 16: -n0rd-ru-west-2nd -shanghai-mm-sc-cm-210] [amf-xrp] [debug] ...
✓ G7, Sample 17:  the session time.Session.DownloadEvent:ADDITIONAL_CLIENT_ID...
✓ G7, Sample 18:  the state, the band is 0x7f19fa, ‘ ‘ band is ‘ 0xa0005 : ba...
✓ G7, Sample 19: .exe /home / oran / openairinterface5g / openair2 / rrc / nr...
✓ G7, Sample 20:  [ 0m # ‘ 0m [ sctp ] connect : port 7777 failed, errno ( 11...
✓ G7, Sample 21: .dsm.services.HtmlHelper :handleBindEvent(['HW']/../../lib/x...
✓ G7, Sample 22: , 12:54:24 srs-ran open5gs-sgwcd[14976]: 02/12/15 14:00:24.5...
✓ G7, Sample 23:  22 22 : 21 : 25 srs - ran open5gs - pcfd [ 142] : 02 / 13 2...
✓ G7, Sample 24: , RNG is enabled, and the RNG parameters get encoded. The RN...
✓ G7, Sample 25: : 22 Sep 18 19:11:54 srs-ran open5gs-udrd[13002]: 02/12/2015...
✓ G7, Sample 26: . 93rd session. ‘ 106 nrp: ‘ downlink failed: errno ( 93 ) ‘...
✓ G7, Sample 27: , ssb.exe ‘ 0 ‘ ‘ ‘ ‘ ‘ ” dl ‘ cmdline ” : ” dl ‘ cmdline ” ...
✓ G7, Sample 28:  the algorithm "channels" – the number of channels to be rec...
✓ G7, Sample 29: .cell.cell.cell.cell.cellUnknownFormat: 543In file config/ap...
✓ G7, Sample 30: : 25 min | | | pd | session | info | gnb. sa. band78. fr1. 1...
✓ G7, Sample 31:  to be added. (1) The file app.xnbssib1.exe file is not avai...
✓ G7, Sample 32:  [ 1 ] failed! in rscn _ prach _ ru ( ) / home / oran / ‘ ‘ ...
✓ G7, Sample 33: -ran open5g-scnb-bsfd[13098]: 02/13/12 16:44:44.743: [sbi] W...
✓ G7, Sample 34:  to debug. nr - uesoft ‘ ” 0 [ 0m # ‘ nr _ phy ‘ ” ] [ 130m ...
✓ G7, Sample 35:  – after the first period of registration and the end of the...
✓ G7, Sample 36:  1 thread created, with 1 thread setup ‘ 0x1 ‘ ‘ 1 : 22 ” ( ...
✓ G7, Sample 37: : 1222PM PDT / 1730S03P: [sbi] WARNING: [15e1007f-ea30-41ef-...
✓ G7, Sample 38:  2, 4 bytes as requested. MSCSI-binding 000095, ‘ 001100, ” ...
✓ G7, Sample 39: :25am PDT | 00:59:45.600 [amf_app] [debug] Send notification...
✓ G7, Sample 40: /10PM PDT/5PM PDT / 10PM – 11AM PDT / 11AM – 12PM – 1PM PDT ...
✓ G7, Sample 41: .exe -u rrc -i <-- o.o.d.l.pb.exe [1025] [error] failed to r...
✓ G7, Sample 42:  1;..![16m[CONFIG] config_switcher: couldn't open file or di...
✓ G7, Sample 43: s[0m#[93m[NAS] [UE 0] Received NAS Loss of Connectivity Sign...
✓ G7, Sample 44: .js file.js file.js file.json file.json : [ app ] file.json ...

✓ G7, Sample 45:  and ‘ sg_rrc_idx : ” 0xe000 ” 0xe000 ” to be added to the l...
✓ G7, Sample 46:  the amf config file. The amf config is the configuration fi...
✓ G7, Sample 47:  to the file.. /.. / targets / projects / generic - nr - 5gc...
✓ G7, Sample 48: . 03 / 12 : 36 : 53. 854 : [ sbi ] warning : [ 1340805fa - e...
✓ G7, Sample 49:  with a section, the length need not be encoded, the value i...
✓ G7, Sample 50:  to 10 p.m. PDT (5 p.m. PT), the app ran out of time. The pr...
✓ G7, Sample 51:  amf _ sib1 _ n2 _ util _ sib1 _ rrc _ config _ gnb _ config...
✓ G7, Sample 52: 1 [NR_IMAGE] sctp_applicATION_GENERIC:error code ”011100, ”0...
✓ G7, Sample 53: -bindx1, retry registration with NRF (../lib/gnb.sa.band78.f...
✓ G7, Sample 54: . 03 07 : 44 : 53 srs - ran open5gs - pcfd [ 13882 ] : 02 / ...
✓ G7, Sample 55:  ack1 [- 1 ](..,..,..,..,..,..,..,..,..,..,..,..,..,..,..) f...
✓ G7, Sample 56:  - 1 [ pool - 2 - thread - 1 ] o. o. d. s. s. s. r. fileread...
✓ G7, Sample 57:  the file. o. d. e. s. s. s. h. r. e. c. i. s. c. s. d. i. s...
✓ G7, Sample 58: , 2025, 16:00:25.256] [amf_n2] [debug] Received Send SCTP me...
✓ G7, Sample 59:  13 22 : 21 : 10 srs - ran open5gs - pcfd [ 14926 ] : 02 / 1...
✓ G7, Sample 60:  ack [ 13036 ] : 02 / 13 / 13 ‘ : 21 : 16. 550 : [ sbi ] war...
Generating from Generator 8...
✓ G8, Sample 1: , 19 Oct 17 22:21:17 srs-ran open5gs-bsfd[12691]: [biject] W...
✓ G8, Sample 2:  of ‘ ‘ ‘ 1 ‘ 2 ‘ ‘ ‘ ‘ ‘ ” ” ” ” ” ” ” ” ” ” ” ” ” ” ” ” ” ...
✓ G8, Sample 3:  [ 1 ; 31m [ nr _ rrc ] unknown ciphering algorithm ” e1fa14...
✓ G8, Sample 4: m[NR_PUF][HW] Update driver release algorithm: NR_PUF_ADD (1...
✓ G8, Sample 5:  [ gnb _ app ] check the configuration file. o. o. d. s. s. ...
✓ G8, Sample 6: . 02 / 13 / 12 : 35 : 53. 256 ] [ amf _ n2 ] [ debug ] [ con...
✓ G8, Sample 7: , the client connects to the Node.js server and sends the re...
✓ G8, Sample 8:  1 : 13 srs - ran open5gs - pcfd [ 14922 ] : 02 / 13 / 17 / ...
✓ G8, Sample 9:  [ 1 ; 31m [ dl ] nr _ rrc _ nr _ prach _ : send rrc release...
✓ G8, Sample 10: -ran (256): ‘ failed to initialize udr (../lib/udr.c:169)Feb...
✓ G8, Sample 11:  is no longer available [ 0 ] o. o. d. s. r. s. c. filereade...
✓ G8, Sample 12:  the file. c : 28 # ” c : 28 # ” c : 28 unknown encoding bdf...
✓ G8, Sample 13: .js file, it could have been app.json : error, errno [ 124 ]...
✓ G8, Sample 14:  and ‘ 514 [displayText] Update the AMF to the standardized ...
✓ G8, Sample 15:  [ 0m # ‘ 0m [ mnc ] unknown ciphering algorithm " utf8 " in...
✓ G8, Sample 16:  the value of s.length > 0; in s.length < 16; in s.posix[0]....
✓ G8, Sample 17:  28 [displayText] Update the parameters of the NFTP environm...
✓ G8, Sample 18:  amf _ n2 _ rrc _ ue n2 _ rrc _ gnb _ app _ config _ ue _ am...
✓ G8, Sample 19:  ( 0m [ EMDLINE ] ue 1 : send buffer release request [ ue 0x...
✓ G8, Sample 20:  in 0..99 … nr - ld [ 0 ](.., ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ nr - 1 )...
✓ G8, Sample 21:  ( numelt > 0 ) failed! in read _ pf _ nr _ rrc _ configcomm...
✓ G8, Sample 22: , SIB 0xe000, SIB 0xe000, SIB 0xe000, … ” 0xe000: ” failed t...
✓ G8, Sample 23:  to amf_rval.c:306 May 12 22:59:21 sctp[12428]: [sbi] WARNIN...
✓ G8, Sample 24: -bindx() failed: errno(111) couldn't open socket ‘ ‘ ‘ open5...
✓ G8, Sample 25:  as a generic algorithm, with the length d and the algorithm...
✓ G8, Sample 26: s [ 0m # ‘ hw ] srs - ran open5gs ‘ phy [ 0m [ 93m [ seppd [...
✓ G8, Sample 27: : 02/17 23:59:54.800: [sebaceous] WARNING: [seb_app] Failed ...
✓ G8, Sample 28:  and ‘ 1 failed! ( ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ” failed! ) ”! ( ‘ ‘ ‘ ” ...
✓ G8, Sample 29:  ausdprf _ app _ check _ prach _ prach _ ruination : prach _...
✓ G8, Sample 30:  12 23:44:58 srs-ran open5gs-udrd[14976]: 02/12 23:44:58.600...
✓ G8, Sample 31:  the configuration file. o. o. o. o. d. s. s. s. s. c. e. cb...
✓ G8, Sample 32:  ( ) failed! in rx _ nr _ prach _ ru ( ) / home / oran / ope...
✓ G8, Sample 33:  -03-21 13:25:46.853] [app] [debug] Initializing SRCS PDO[13...
✓ G8, Sample 34: .exe - file .. /.. / targets / projects / generic - nr - 5gc...
✓ G8, Sample 35:  of a session. Session ID: 600. Session begin: 00101. Permis...
✓ G8, Sample 36:  is a global data format for values, in the format: UICode, ...
✓ G8, Sample 37:  to 16000. ‘ ” failed. dl ‘ gtpu ‘ ‘ ‘ ” failed, errno ‘ 0xe...
✓ G8, Sample 38:  it was the SACS client-server association, and in the confi...
✓ G8, Sample 39:  [ 0m [ nas ] [ ue 0 ] received nas _ data _ ind : length 4,...
✓ G8, Sample 40:  to initialize the context (e.g., the current instance): # ‘...
✓ G8, Sample 41: -se-03-17 16:44:21.790] [seb-client] [debug] Error loading U...
✓ G8, Sample 42:  is the period of time after the execution of the transferra...
✓ G8, Sample 43: -bind-xr-xr-1 0x7fde800 ” 00000 ” 00101m ” rrc _ gnb. sa. ba...
✓ G8, Sample 44: .conf file : file .. /.. / targets / projects / generic - nr...
✓ G8, Sample 45:  the algorithm was unsuccessful.Periodicity: 00h30m: Signal ...
✓ G8, Sample 46:  ( 1 - ‘ ‘ ‘ … – ‘ ” ‘ ‘ 0 ‘ … ” ) to complete the transfer....
✓ G8, Sample 47: , ‘ 0 , ” 0. ‘ ‘ ” 1. ” 0 : ‘ no information available [ 1 ”...
✓ G8, Sample 48:  and ‘ ‘ ‘ noaa ‘ srr _ prach _ ‘ ‘ ‘ ‘ ‘ ‘ ” not ‘ ‘ ” or ‘...
✓ G8, Sample 49: s_nr_band: failed to bind NF_CTYPE_INDEX to ue id 1 (0xc0a40...
✓ G8, Sample 50:  that section has already been added.In the section "SetupSe...
✓ G8, Sample 51:  [ 0m [ ngap ] receive notification that app has been added ...
✓ G8, Sample 52:  the length of time that the thread is in execution. Paramet...
✓ G8, Sample 53:  the band was already in the band.[54] The band failed.[54] ...
✓ G8, Sample 54:  ack [ 1 ] : 02 / 12 / 17 / 12 srs - ran open5gs - pcfd [ 14...
✓ G8, Sample 55:  ( pl ‘ ‘ ‘ ‘ ‘ pl ‘ ‘ ‘ pl ‘ ‘ ‘ ‘ ” pl ‘ ‘ ‘ ” ” ” ” … ” …...
✓ G8, Sample 56: .g. gnb _ app ‘ appx _ band ” gtpu ‘ gnb _ appx _ band ” int...
✓ G8, Sample 57:  ( 1 / 3 ) failed! in rx _ nr _ ru ( ) / home / oran / ‘ ‘ h...
✓ G8, Sample 58: , nr _ rrc _ nr _ prach _ : send prach _ request _ upvoted ‘...
✓ G8, Sample 59: : 1 [pool-1-3-thread-1] o.o.d.c.i.c.i.u.r.cell.DataCellInter...
✓ G8, Sample 60:  in 2nd sib1 [2025-03-17 19:00:53.476] [amf_n2] [debug] IE i...
Generating from Generator 9...
✓ G9, Sample 1: .zip ) file .. /.. / targets / projects / generic - nr - 5gc...
✓ G9, Sample 2: 1 [pool-2-thread] o.o.d.d.n.o.client.CbsClient.cbsConfigMap....
✓ G9, Sample 3: , 03 27 : 54 : 22 srs - ran open5gs - udrd [ 1495 ] : 02 / 1...
✓ G9, Sample 4:  or later, the journal data integrity check failed, with no ...
✓ G9, Sample 5: , 2025. 00:00:00. 944] [amf_n2] [debug] Create Transport Slo...
✓ G9, Sample 6:  the configuration file. ”(.. /.. /. c : 1712 /home / oran /...
✓ G9, Sample 7: , ‘ 1 ‘ ‘ ‘ 0.5 ‘ ‘ ‘ ‘ – 1 skipped min 1 ‘ ‘ ‘ 1 ‘ ‘ ‘ ‘ – ...
✓ G9, Sample 8:  [ 0m # ‘ … ‘ … : 00m [ hw ] connect : ‘ received connection...
✓ G9, Sample 9:  - 02 / 13 16 : 44 : 58. 256 ] [ ngap ] [ debug ] init clien...
✓ G9, Sample 10:  (cellID: 698)Feb 13 22:53:12 srs-ran open5gs-sfd[14900]: 02...
✓ G9, Sample 11:  - 02 - 12 17 : 19 : 48. 936 ] [ amf _ n2 ] [ debug ] remove...
✓ G9, Sample 12:  srs-ran open5gs-udrd [12436]: 02/12/2015 srs-ran open5gs-ud...
✓ G9, Sample 13: 1 _ app. c : 2825 asn1 message encoding (ssb)[PHY] [error] N...
✓ G9, Sample 14: s - ran open5gs-smfd[14998] ogs-sbi-app - smfd[14774]: 02/12...
✓ G9, Sample 15:  the client connects, it sends the requested file to the ser...
✓ G9, Sample 16: , nr _ rrc _ ue 0xe000 # ” 0800 ” # nr _ rrc _ ue ‘ ‘ ” 0010...
✓ G9, Sample 17:  23 : 44 : 58 srs - ran open5gs - udrd [ 14983 ] : 02 / 13 2...
✓ G9, Sample 18: , gtpu_idx[0].posix_idx = 4; nr _ rrc _ idx[1].posix_idx = 2...
✓ G9, Sample 19:  ( sizeof ( buf ) ) failed! in clone_pusch_configcommon ( ) ...
✓ G9, Sample 20: 1 [CONFIG] config_switches: priority: 50 for i3 sw error cod...
✓ G9, Sample 21:  the current session, the session state has already been ini...
✓ G9, Sample 22:  [ 1 ; 31m [ rrc ] unknown ciphering algorithm ” # ” # [ 93m...
✓ G9, Sample 23:  not to remove the app after an error (nullptr, ‘nullptr+1)!...
✓ G9, Sample 24: .net.minecraft.client.resources.sa.client.resources.sa.clien...
✓ G9, Sample 25:  1 rrc _ prach _ nrp _ prach _ ru ( ) : prach _ nrp _ prach ...

✓ G9, Sample 26: : 00 / 14 23 : 44 : 53. 256 ] [ ngap ] [ debug ] received ng...
✓ G9, Sample 27:  12 23:44:44 srs-ran open5gs-pcfd[14002]: 02/12 23:44:44.342...
✓ G9, Sample 28:  [ 0m [ nas ] [ ue 0 ] received nas _ request message [ mnc ...
✓ G9, Sample 29: .exe file and get the current position.xpath : / ‘ ‘ ” hw ‘ ...
✓ G9, Sample 30:  – the band is complete. JBHW releases the band info, while ...
✓ G9, Sample 31:  12:44:02 srs-ran open5gs-bsfd[14940]: 02/12/14 13 22 : 44 :...
✓ G9, Sample 32: .m. PDT / 12:35:20. 895: [sbi] WARNING: [7] Failed to connec...
✓ G9, Sample 33:  be added to the pool section.In this file: rfs _ config _ g...
✓ G9, Sample 34:  13 22 : 21 : 16 srs - ran open5gs - pcfd [ 13098 ] : 02 / 1...
✓ G9, Sample 35:  12 23:44:44 srs-ran open5gs-bde-sgwcd[14876]: 02/13 23:44:4...
✓ G9, Sample 36:  0m [ nas ] [ ue 0 ] ( ue id 1 rnti ) send data transfer [ g...
✓ G9, Sample 37: , 03 23 : 44 : 59 srs - ran open5gs - nssfd [ 14876 ] : 02 /...
✓ G9, Sample 38: /src/drd/lib/drd.c:1305[SCTP] WARNING: Failed to initialize ...
✓ G9, Sample 39:  1 [ pool - 1 ] ue 0 [ 3 ] : ogs _ n2 _ ssb _ id 3 [ pool - ...
✓ G9, Sample 40:  – 2025. Not only is this period a bit of a problem for the ...
✓ G9, Sample 41:  [ 0m # ‘ 0m [ mac ] ue 1 : received reject release request ...
✓ G9, Sample 42:  28 [pool-1-2-thread-1] o.o.d.s.s.t.u.r.interface.f.s.api.rs...
✓ G9, Sample 43:  0m [ nr _ rrc ] [ sbi ] ( cellid bc614e, ue id 1 rnti 6 ) s...
✓ G9, Sample 44: , the band is expected to release a full length EP in the ba...
✓ G9, Sample 45:  all the parameters need to have the standardized values ‘ 0...
✓ G9, Sample 46:  notifies the local time. (5) /usr/src/app_xpi/app.c:196 war...
✓ G9, Sample 47:  10 min ago # ‘ ‘ ” # ” 00:00 ‘ cbsd [ 12440 ] : [ sbi ] war...
✓ G9, Sample 48:  ackpf _ imd [ 0 ] : handle ackpf _ imd [ 1 ] (.. / lib / im...
✓ G9, Sample 49: -ran open2fs -pf -o 2f -r ngap -pf config | config | o - udr...
✓ G9, Sample 50:  amf | amf | amf | amf | amf | amf | [fr4] [debug] Release a...
✓ G9, Sample 51: -NR-7gNR-MAC ”-MAC-ADDR: ”-MAC-MAC-MAC-ADDITIONAL-MAC: ”-MAC...
✓ G9, Sample 52: , 12 o'clock; ” sctp sctp_idx = 12, ” sctp _ idx ” = 3, ” sc...
✓ G9, Sample 53: -bindx ( ) failed! in rx _ gnb _ sync _ nr ( ) / home / oran...
✓ G9, Sample 54:  in the config file.. /home/oran/openairinterface5g/openair2...
✓ G9, Sample 55: m [ pool - 2 - thread - 1 ] o. o. d. s. s. s. c. filereader ...
✓ G9, Sample 56:  ( nr - ue loc ‘ ‘ ‘ ” ) failed! in encode _ du ‘ numelt : ‘...
✓ G9, Sample 57: : 0xe000[NR_APP] ogsf_drd[NR_CTYPE] is not supported! ogsf_m...
✓ G9, Sample 58:  the band added a section for "sib1" (cell id 28) in the con...
✓ G9, Sample 59:  the band is running out of bandwidth. Couldn't send us an S...
✓ G9, Sample 60:  [ 0m [ nas ] ue 2aa … : request release after ul failure ti...
Generating from Generator 10...
✓ G10, Sample 1:  22 : ‘ nr - thread – instance ‘ id : 10 available [ dl ] ( ...
✓ G10, Sample 2:  the time the check failed, the execution context could not ...
✓ G10, Sample 3:  the configuration file. # [ 0m # [ 93m ‘ phy ] connect() to...
✓ G10, Sample 4:  in section 7.5 of the SBI.[1] Addresses SBI-APCTP-MAC addre...
✓ G10, Sample 5: -bind-xr-xr-1: Rejected association '../../../xr-targets/PRO...
✓ G10, Sample 6:  [ 32 ] fd [ o ‘ 1 ] ( cell ‘ pdu ‘ ‘ ‘ ‘ cellid bc614e, ue ...
✓ G10, Sample 7:  a guest Oct 16th, 2012 1,173 Never a guest1,173Never

Not a...
✓ G10, Sample 8: .npr _ prach _ inst _ rrc _ nr _ prach _ inst _ rrc _ inet _...
✓ G10, Sample 9:  ( 1 - ‘ ‘ – ‘ ‘ 0 ) failed! in rx _ rx _ ru ( ) / home / or...
✓ G10, Sample 10:  a guest Dec 22nd, 2015 93 Never a guest93Never

not a membe...
✓ G10, Sample 11:  to get an association, the association parameters have the ...
✓ G10, Sample 12: , ‘ ‘ 0 … : ‘ failed, errno ( 111 ) ‘ ” : ” 0x3a ” 0xe ” 0xe...
✓ G10, Sample 13:  amf ( ‘ ‘ ‘ ) ‘ ‘ ‘ ‘ ‘ noctime – 6 o ‘ ‘ ‘ ‘ ‘ ‘ noctime ‘...
✓ G10, Sample 14:  is not available. Connectivity is not provided. Connection ...
✓ G10, Sample 15:  the cell is received from client-server:5#![0m#[93m[NR_CTP]...
✓ G10, Sample 16: , 12hrs:53m[SCTP] WARNING: ogs_app_handle() failed!In read_d...
✓ G10, Sample 17: .exe - o - rlc - udrd [ 0 ] (.. / lib / drd / gnb. sa ) feb ...
✓ G10, Sample 18: : 02/13 23:44:44.256] [nas_ngap] [error] Received unsuccessf...
✓ G10, Sample 19:  1 / 10 srs - ran open5gs - pcfd [ 14976 ] : 02 / 13 / 21 / ...
✓ G10, Sample 20:  [ 0m # ‘ 0m [ sctp ] connect failed: Connection refused, SS...
✓ G10, Sample 21: : ‘ 0 # ‘ ‘ – – 1 … : ‘ down … : 99 pdu ‘ downlink pdu sessi...
✓ G10, Sample 22: .rrc:210 syntax error (enc_rval.encoded > 0 && encoding_rval...
✓ G10, Sample 23:  to seppd [ 1 ] : 02 / 13 / 13 16 : 16. 854 : [ sbi ] warnin...
✓ G10, Sample 24:  to connect to the server, or to an external peer: connect_c...
✓ G10, Sample 25:  a bandpass algorithm was not available, the ciphertext coul...
✓ G10, Sample 26: /src/llvm/RRC_SRC.c:1928FIG 6: [dbi] PLATFORMER_DATA_ADD_PRO...
✓ G10, Sample 27:  10 min. ‘ 0 – ‘ ‘ 2 ‘ 3 hiccups ‘ ‘ numofs – 1 noctime – ” ...
✓ G10, Sample 28: -sdr-rsc-libsg-6.conf | gnb.path.i1821 | info@rpi.org:122no-...
✓ G10, Sample 29:

#[cfg_rpi] PLATFORM_TIBCLIMIT="-o "-DL" "gnb _ app _ confi...
✓ G10, Sample 30: : 1722:21 srs-ran open5gs-bsfd[12976]: 02/13/2015 – 12:44:46...
✓ G10, Sample 31:  the app is running, it sends out a request for information,...
✓ G10, Sample 32:  a[config] bg_app_idx = 8 inst_rrc_idx = 1 inst_rrc_name = "...
✓ G10, Sample 33: 1 session - 1 failed, error - 1 [ sctp ] o. o. d. s. c. file...
✓ G10, Sample 34: /n1/tcp - peer | tail -n1 | sc - udrd | gnb _ app | gnb _ co...
✓ G10, Sample 35:  of this session. We have not been able to send the requeste...
✓ G10, Sample 36:  [ 0m # ‘ 0m [ ‘ rrc ] unknown integrity algorithm " gnb _ r...
✓ G10, Sample 37:  – 0m [ sctp ] [ dl ] [ dl ] ( cellid bc614e, ue id 1 rnti 0...
✓ G10, Sample 38:

CONFIG_IMAGE = "../../src/lib/imf-sm.c:2825" SUPL_PREFIX =...
✓ G10, Sample 39:  the time the request was received, the client requested the...
✓ G10, Sample 40:  the global data binding algorithm nf_softmodem ran out of o...
✓ G10, Sample 41:  the configuration file. Add /etc/yaml/xrdb_config.json to t...
✓ G10, Sample 42: .exe : ‘ 0xe000 ” 001100 ” 00101 – 0015 ” c : 28 ” 00101 hw ...
✓ G10, Sample 43:  the band is up. (I ran out of bandwidth) … srs - ran the og...
✓ G10, Sample 44: .srs-ran open5gs-mnc-xrdb-xrpf[14299]: 02/13/11 14:02:24.196...
✓ G10, Sample 45:  the periodicity algorithm ‘ values ” c ‘ ‘ ‘ ‘ nr _ standar...
✓ G10, Sample 46:  all the current parameters need to have the length in the u...
✓ G10, Sample 47:  a client connect() to server: Connection refused. Failed. F...
✓ G10, Sample 48: , 22 Oct 13 22:44:59 srs-ran open5gs-pcfd[13098]: 02/13 22:4...
✓ G10, Sample 49:  the thread is already in execution: thread is not available...
✓ G10, Sample 50:  ( sbi ) : sw error : ent : 255 inst : 255 proc id : 000 fil...
✓ G10, Sample 51:  : 02 / 13 / 17 srs - ran open5gs - ausfd [ 14935 ] : 02 / 1...
✓ G10, Sample 52:  with the current subscription subscription period.

Cell ph...
✓ G10, Sample 53: : 1322:17 srs-ran open5gs-udrd-scpd[13098]: 02/13 22:17.600:...
✓ G10, Sample 54:  the parameters: length, instrucntime, nrchannels, iInetStat...
✓ G10, Sample 55:  the server sends it an errno (111), informing the client of...
✓ G10, Sample 56:  the client connects, connect() : error, errno(111) Connecti...
✓ G10, Sample 57:  the session started, but the session couldn't start. ‘ ” co...
✓ G10, Sample 58: s - [ 1 ] ( nr _ prach _ phy _ nr _ phy ) [ 93 ] ( nr _ prac...
✓ G10, Sample 59: , 12 hours IST, 1.30am IST. No data available. No ERR messag...
✓ G10, Sample 60:  the algorithm is not properly initialized and the ciphering...
Generating from Generator 11...
✓ G11, Sample 1:  the number of parameters i: m : num_band : value: usr _ ban...
✓ G11, Sample 2:  and ‘ ‘ 0 – 99 failed! in rx _ prach _ ru ( ) / home / oran...
✓ G11, Sample 3:  0m [ nr _ rrc ] [ dl ] ( cellid bc614e, ue id 1 rnti 3e04 )...
✓ G11, Sample 4:  all parameters have been encoded in the value 1, the encode...
✓ G11, Sample 5: .config file:line: 1843need to have a buffer section in conf...

✓ G11, Sample 6:  amf _ nr _ prach _ ru ( ) : seppd [ hw ] trying to connect ...
✓ G11, Sample 7: .exe -usr -prd[0m#[93m[HW] UP Received PSEUDO UE Error Respo...
✓ G11, Sample 8:  be added: Remove the file system information. /home/oran/op...
✓ G11, Sample 9: 1 session ‘ 0m[NR_CONFIG] / home / oran / openairinterface5g...
✓ G11, Sample 10:  ( 2 - nr - 1 ) failed! in rx _ prach _ ru ( ) / home / oran...
✓ G11, Sample 11:  [ 0m [ nas ] [ ue 0 ] received nas _ message _ ind : length...
✓ G11, Sample 12: .exe -u imd[0m[93m[PHY] PLATFORMER WARNING: PDO PLATFORMER E...
✓ G11, Sample 13: : [1140] [amf_app] [debug] Retry registration with NRF [1290...
✓ G11, Sample 14:  and 1822-03-21 08:44:52.600] [sebaceous] [debug] SIB-onCrea...
✓ G11, Sample 15:  ( sizeof ( ue ) ) : failed encodeURLCMDLINE ( ) / home / or...
✓ G11, Sample 16:  and Tx[9].channels.inet6.BindIBmRXTime() failed: Connection...
✓ G11, Sample 17:  – 1 file : o.o.d.t.c.CbsClientConfiguration : int[0xe000-0x...
✓ G11, Sample 18:  is the periodicity for the sib1 file. The periodicity value...
✓ G11, Sample 19: -ran.targets[0].targets[1].xpath=/opt/oc - path=/opt/o-du-l2...
✓ G11, Sample 20: . og. hw. sa. ue. ue. rrc. conf. sa. rrc. org. app. sib1clie...
✓ G11, Sample 21:  ( posix ) : sw error : ent : 255 inst : 255 proc id : 000 f...
✓ G11, Sample 22:  the period.exe -n 1 > & = 1; 31m[LOG] Failed to resolve ass...
✓ G11, Sample 23:  that the system was running.CreateFileExe:cellListSetupExe(...
✓ G11, Sample 24:  the current subscription period (1 subscription = 6 ) faile...
✓ G11, Sample 25:  of the current session (4 sessions), ” 12 hours ” 1 min. ‘ ...
✓ G11, Sample 26:  the parameters : y, m : length, s : number of sibils in the...
✓ G11, Sample 27:  13 22 : 54 : 36 srs - ran open5gs - scpd [ 13098 ] : 02 / 1...
✓ G11, Sample 28:  that the app is running.CMDLINE:app_idx=130CMDLINE:line:app...
✓ G11, Sample 29:  [ 93 ] : ciphering not supported [ gtpu-sm. c : 255 ] ( ) f...
✓ G11, Sample 30:  the current thread is open

#[0m#[93m[PHY] SSB socket shutd...
✓ G11, Sample 31:  a guest Dec 18th, 2015 93 Never a guest93Never

Not a membe...
✓ G11, Sample 32:  1 (min. txout. txout. posix > 0 && tx. posix < max. txout. ...
✓ G11, Sample 33: -93-11 14:53:44.605] [amf_n2] [debug] IE Send Tx Reactivatio...
✓ G11, Sample 34:  amf_n1 | config | gnb _ app | gnb _ config _ handle | gnb _...
✓ G11, Sample 35:  the config file for rx _ app _ config.json : error[ SUPPLY_...
✓ G11, Sample 36:  as an int [ 0 ] nr _ saff phy _ config _ freq _ handle [ 3 ...
✓ G11, Sample 37:  of the Session. (d5f9914 –e100 ) : 02 / 12 / 17 / 10. 10. 1...
✓ G11, Sample 38:  (cellID bc614e, UE ID 1 RNTI 1 ) failed! in clone _ pdu_idx...
✓ G11, Sample 39:  the parameters' value. o. d. e. s. s. c. s. c. d. e. h. a. ...
✓ G11, Sample 40:  to receive the Signal Encoded Authentication (SIGA) and Ret...
✓ G11, Sample 41:  1 ) failed! in rx _ ru ( ) / home / oran / openairinterface...
✓ G11, Sample 42: .plmn[149]: 02/13 22:25:58.232: [sbi] WARNING: [bdf8efd0-ea3...
✓ G11, Sample 43:  of the current period (Feb 21 00:44:25 srs-ran open5gs-amfd...
✓ G11, Sample 44:  - 1 [ pool - 2 - thread - 1 ] o. o. d. s. s. s. filereader ...
✓ G11, Sample 45:  [ 0m [ hw ] ue 1 : send buffer release errno ( 106 ) [ mnc_...
✓ G11, Sample 46:  a nr - rrc - ue 2aa ” # ” 0 ‘ nr _ prach _ uesoft [ 0mcmdli...
✓ G11, Sample 47: -sctp: Received handshake failure while encoding TxEvent_IDx...
✓ G11, Sample 48:  [ 0m # ‘ 1 ; 31m [ phy ] connect ( ) to 127. 0. 0. 1 : 4043...
✓ G11, Sample 49: /src/scn/locals.c:2543: [scm_app] Error loading config_path ...
✓ G11, Sample 50:  - seppd [ 13076 ] : 02 / 13 / 12. 8. 6 : [ sbi ] warning : ...
✓ G11, Sample 51:  in rrc_inet.c:2222: [sbi] WARNING: Retry registration with ...
✓ G11, Sample 52:  auschwes … c : 1722 ent hw ‘ ‘ ” ” c : 1825 ent hw ” ” c : ...
✓ G11, Sample 53:  the table, the cell type is: cell_idx ‘ 0xe000, ‘ idx 0xe00...
✓ G11, Sample 54: : 02/17 23:54:59 srs-ran open5gs-amfd[15095]: 02/17 23:54:59...
✓ G11, Sample 55:  the SBCS sends the file.SBCS _ get_sbs() : error [ pool - 2...
✓ G11, Sample 56:  a posix ( ) : sw error : ent : 255 inst : 255 proc id : 000...
✓ G11, Sample 57:  [ 0m [ gnb 0 ] ue 0 [ gnb 0mcmdline : informing ue 1 [ 0m [...
✓ G11, Sample 58: s - c : 1843 asn1 rfs [ 14983 ] : 02 / 13 / 13. 1 : [ sbi ] ...
✓ G11, Sample 59:  at all! - nr - uesoft - sc - smfd [ 1 ] : 02 / 13 / 12 / 12...
✓ G11, Sample 60:  12 22 : 21 : 16 srs - ran open5gs - amfd [ 13098 ] : 02 / 1...
Generating from Generator 12...
✓ G12, Sample 1:  the gnb_app _ config _ check _ length : 500 failed, cnx _ a...
✓ G12, Sample 2:  a guest Jun 16th, 2015 93 Never a guest93Never

Not a membe...
✓ G12, Sample 3:  to the home server. o. o. s. s. r. c. e. i. cbsclientconfig...
✓ G12, Sample 4: -ran with nr - softlink - 2 enabled [ 2015-03-16 13:04:15.87...
✓ G12, Sample 5: , RENEGADER 3.0 (or later), standardized standardized ‘ 0mcg...
✓ G12, Sample 6:  [ 0m [ nas ] unknown interface ‘ ” ngap ] or ngxplorationha...
✓ G12, Sample 7: . 93am: ” srs-ran open5gs-sfd[14210]: 02/13/93rd periodicity...
✓ G12, Sample 8: : 22 Oct 13 22:11:59 srs-ran open5gs-bsfd[13098]: [sbi] WARN...
✓ G12, Sample 9: , sgcp - udrd [ 0 ] [ debug ] trigger pdu session release af...
✓ G12, Sample 10: , 03 Oct – 14:16:04 srs-ran open5gs-scpd[14900]: 02/13 Oct 1...
✓ G12, Sample 11:  as a thread-binding interface (e.g., thread_idx() /home/ora...
✓ G12, Sample 12:  is the center of the band, and the band is 4.4.2.1:4(2) ”0[...
✓ G12, Sample 13:  the parameters. The parameters have the format json_rval.gs...
✓ G12, Sample 14:  and ‘ ‘ ‘ 5am. – ‘ ‘ 1 [ 6 ] [ 93 ] ‘ [ gtpu ] ” cminer : s...
✓ G12, Sample 15:  28 [pool-2-thread-1] o.o.d.s.r.s.c.ClientConfigCell.BindEve...
✓ G12, Sample 16: , 23 Sep – 21:59:59 srs-ran open5gs-udrd[14898]: 02/13 23 Se...
✓ G12, Sample 17:
 ( 0x0C0C3AAD ” 0x2F44800 ) fails! in clone _ pusch_configc...
✓ G12, Sample 18:  to 3rd party projects to have a peer-to-peer (P2P) file-hos...
✓ G12, Sample 19: , 1322, 12p--am: [dnc-east-1g-app] [dnc-app] [debug] Handle ...
✓ G12, Sample 20:  1 ; pd [ nr _ rrc ] [ bcd ] starting up nrf ( ) : nrf ( ) d...
✓ G12, Sample 21: : 25 min. sib1 message starting syncup errno 99; ” ssb 00000...
✓ G12, Sample 22: , sgcp_debug_idx, gnb_idx_idx, gnb_idx_idx_spoof, gnb_pkt_id...
✓ G12, Sample 23:  a session. Session ID: 18 Session created: 02/17/15 23:59:2...
✓ G12, Sample 24:  [ 0m # ” 0m [ 1 ; 31m [ ENCM ] unknown integrity algorithm ...
✓ G12, Sample 25: :00:44.619] [amf_app] [debug] Received AMF request for PDU D...
✓ G12, Sample 26: .exe /home/oran/openairinterface5g/openair2/RRC/NR/nr_rrc_co...
✓ G12, Sample 27: , nr _ prach _ prach _ nr [ 0 ] ( ) failed : prach couldn't ...
✓ G12, Sample 28: 1 hw ] sctp - connect : up ” [ 14895 ] : 02 / 13 / 16 : 18. ...
✓ G12, Sample 29: : 22 Oct – 21:44:44 srs-ran open5gs-udrd-amfd[12790]: 02/21/...
✓ G12, Sample 30:  ausdwim3a (.. / lib / sctp. c : 169 ) feb 13 22 : 54 : 16 s...
✓ G12, Sample 31:  [ 0m # ‘ 1 ; 31m [ rrc ] unknown integrity algorithm ” e. g...
✓ G12, Sample 32:  28 [displayText] [pfcc] [dbi-sm-association] ” 0x1 [dbi] un...
✓ G12, Sample 33:  ( 1 / nr - app ] rrc _ config ‘ 0 ‘ ‘ … errno 9399 ” ‘ ” ‘ ...
✓ G12, Sample 34:  is the current value in mRNTIMEGR.gNBss(4) and the current ...
✓ G12, Sample 35: , 16 August, 13:11:21.256] [app] [debug] Send an error messa...
✓ G12, Sample 36:  1 [pool-1-thread-1] o.o.d.s.s.r.p.c.ClientHandler:errorHand...
✓ G12, Sample 37: .exe file.. /.. /.. / targets / projects / generic - nr - 5g...
✓ G12, Sample 38:

# ‘ sctp ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ” ‘ ‘ 0 ‘ ” ‘ ‘ ” ” ” 1 ” 1 ” 0 ]...
✓ G12, Sample 39: .g. gnb 0.9.3 [common] Error loading UE with associated id :...
✓ G12, Sample 40:  sg_pf_debug ( ) failed! in clone_pf ( ) / home / oran / ope...
✓ G12, Sample 41:  and failed – or ran out of fuel – to complete the race. ‘ ‘...
✓ G12, Sample 42: . o. d. e. r. i. s. s. s. c. s. p. e. s. c. e. c. i. s. s. c...
✓ G12, Sample 43:  28 [displayText] => Passed/agreed to in Senate: Passed Sena...
✓ G12, Sample 44:  1 : 02 / 13 srs - ran open5gs - seppd [ 14976 ] : 02 / 13 s...
✓ G12, Sample 45: /17-03-17 13:44:54.600: [sbi] WARNING: [bdf8a40-ea30-41ef-bc...

✓ G12, Sample 46:  - 1 - gpu-scm [ 12976 ] : [ sbi ] warning : retry registrat...
✓ G12, Sample 47:  the band has provided.I ran it out of the box, i.e. 1 mac, ...
✓ G12, Sample 48:  all config values have the format json encoded.I added the ...
✓ G12, Sample 49:  13 23:59:58 srs-ran open5gs-nbclbs2gs-smfd[14900]: 02/13 23...
✓ G12, Sample 50:  ( gnb _ app _ pf _ app ) failed! in clone_pf_configcommon (...
✓ G12, Sample 51: .targets[NR_APP] is not available[0m#[93m[NGAP] no amf_sg_co...
✓ G12, Sample 52: .targets[NR_APP] /home/oran/openairinterface5g/openair2/RRC/...
✓ G12, Sample 53:  the client sends out an HTTP request. Parameters: band : in...
✓ G12, Sample 54:  – 12 – 17 : 44 : 59 srs - ran open5gs - pcfd [ 12999 ] : 02...
✓ G12, Sample 55:  a rnti thread ngInitiated : sw error : ent : 255 inst : 255...
✓ G12, Sample 56: . o. d. s. s. s. c. f. s. e. c. i. s. s. p. a. d. s. s. c. h...
✓ G12, Sample 57:  1 time out of 2,000,000 in the app. ” 134493 failed, errno ...
✓ G12, Sample 58:  amf srs-ran open5gs-udmd[13098]: 02/13/12 19:59:54.363: [sb...
✓ G12, Sample 59: : 21m [ ngap ] ( cellid bc614e, ue id 1 rnti 3e04 ) send ds ...
✓ G12, Sample 60:  ausd-ru-du-band-config-map : priority : 105 cmn : binding r...
Generating from Generator 13...
✓ G13, Sample 1:  to send data to the server. dl_imd_idx() : failed, errno(11...
✓ G13, Sample 2:  [ 0m # ‘ rrc ] unknown ciphering algorithm ” nr - 5 for ue ...
✓ G13, Sample 3:  amf-ran open5gs-seppd [13098]: [sg] WARNING: Retry establis...
✓ G13, Sample 4: 1 # CONFIG_DEBUG is not supported in rxprach # CONFIG_PHY is...
✓ G13, Sample 5: , srs-ran open5gs-udrd-scpd[13098]: 02/13/2015 srs-ran open5...
✓ G13, Sample 6:  the value of rng_size is not available, the value in the fo...
✓ G13, Sample 7: , iSCSI: Received unsuccessful result for sctp_inet_dw (3) a...
✓ G13, Sample 8: .js : [ 8 ] error : response _ handler ( ) failed [ 6 ] ( ) ...
✓ G13, Sample 9: .plmn [NR_SCTP] Send to NRF [0m#[0m[RRC] Received handshake ...
✓ G13, Sample 10:  (cellid bc614e, path /opt / odu – path. c : 264 ) feb 13 23...
✓ G13, Sample 11:  1 – 25, 22hrs ‘ sgwc ‘ sgwc ‘ : 16 ” failed, errno ( 99 ) ‘...
✓ G13, Sample 12:  1-Feb-16 19:44:44.342: [sctp] WARNING: [5] Failed to connec...
✓ G13, Sample 13:  - 8 Oct - 22:40:53 srs-ran open5gs-scpd[14976]: [sbi] WARNI...
✓ G13, Sample 14: , c: 1719 | o.o.d.t.c.r.u.u.o.d.r.cell.CellReader : error wh...
✓ G13, Sample 15:  0m [ ngap ] [ dl ] check the address[ bmdline : nr - 2a 0 ]...
✓ G13, Sample 16: . The cell id is 16. The cell id is not in ‘ ‘ ‘ 3. … … … ‘ ...
✓ G13, Sample 17:  12 22:44:44 srs-ran open5gs-udrd[15014]: 02/13 22:44:44.307...
✓ G13, Sample 18: .conf file: line: 1741app: [dbi] WARNING: received failure r...
✓ G13, Sample 19:  the system couldn't find a suitable address. The address co...
✓ G13, Sample 20: 1 ngap _ config _ handle _ sib1 : upg _ configval : value ou...
✓ G13, Sample 21: , Sib1, ran open5gs-rse-xrxrxtp [14963] (--) No SBI is assoc...
✓ G13, Sample 22:  at 11am.I received an email informing me that I have to con...
✓ G13, Sample 23: .m. (Feb 23 21:00:44 srs-ran open5gs-udrd-scpd[15014]: 02/23...
✓ G13, Sample 24: .o.d.s.c.UnknownHostException: Retry registration with provi...
✓ G13, Sample 25:  ( sizeof ( buf ) ) failed! in clone_pusch_configcommon ( ) ...
✓ G13, Sample 26:  and ‘5g (16SCTP) ” failed! in SendDataExiting() ” to server...
✓ G13, Sample 27:  srs-ran open5gs-bsfd[122] (libsctp) Node.js client with soc...
✓ G13, Sample 28:  [ 1 ; 31m [ nr _ rrc ] [ dl ] ( cellid bc614e , ue id 1 rnt...
✓ G13, Sample 29:  and nr _ rrc _ dl : length 4 in section " optimization " ” ...
✓ G13, Sample 30: s-ran open5gs-1g-amfd[SCTP] [9340]: 02/12/2015 sctp-rsc-requ...
✓ G13, Sample 31:  ( 0m ‘ 0m ‘ 1 : ‘ down ) failed ‘ ( 1 ” ” ” 0m ‘ ‘ ‘ ‘ ” ” ...
✓ G13, Sample 32:  [ 0m # ” 1 ; 31m [ rrc ] unknown integrity algorithm ” ssi5...
✓ G13, Sample 33: .app.route.getGson() /home/oran/openairinterface5g/openair2/...
✓ G13, Sample 34:  is not available in this format: rx_nss_idx = 3 # ” 0xc000 ...
✓ G13, Sample 35:  of course! (3) ERROR![CONFIG] CONFIG_SRC_SRC_ADD_PTR failed...
✓ G13, Sample 36:  a task.I need to check the file system integrity while enco...
✓ G13, Sample 37:  to remove all duplicate projects. Remove all projects from ...
✓ G13, Sample 38:  the band received a band information message informing them...
✓ G13, Sample 39: , sg-ran open5gs-bsfd[17002]: 02/13/15 14:58:48.235: [sbi] W...
✓ G13, Sample 40:  a file, it could only contain the application information, ...
✓ G13, Sample 41: .exe file: /home/oran/openairinterface5g/openair2/common/ppd...
✓ G13, Sample 42:  a guest Oct 16th, 2015 208 Never a guest208Never

Not a mem...
✓ G13, Sample 43:  to connect and initialize the instance. Connect() : failed ...
✓ G13, Sample 44:  ( nr - 1 ) : … error : ent : 255 inst : 255 proc id : 000 f...
✓ G13, Sample 45: , the cell type: C, the ciphering algorithm: ALF-256, the ci...
✓ G13, Sample 46:  with the app ” appx _ gson ‘ gnb _ appx _ appx _ gson ” jso...
✓ G13, Sample 47:  the server config file. # CONFIG_HWADB 0G # CONFIG_PHY 0G #...
✓ G13, Sample 48: -n1 [dca] [amf_app] [debug] Handle a UE UPnP request for sct...
✓ G13, Sample 49:  28 [displayText] => Passed/agreed to in Senate: Passed Sena...
✓ G13, Sample 50: .dru.client.config.getLCM(.. / lib / clientconfig ) failed!I...
✓ G13, Sample 51:  that was not the time, the time ran out to complete the exe...
✓ G13, Sample 52: .conf file. Try to get the file format in your environment v...
✓ G13, Sample 53: .exe /home/oran/openairinterface5g/openair2/common/config/Co...
✓ G13, Sample 54: 1 = 0m[NGAP] SBI ran open5gs-tcp-udrd [13096] (...) failed: ...
✓ G13, Sample 55: .exe -prg -sc -prginfo [ 1 ] o.o.d.a.p.s.r.t.i.v.c.CbsClient...
✓ G13, Sample 56:  with a length of 5 or 6, and the thread is open (i.e., at l...
✓ G13, Sample 57:  sib1.dll, ‘ sib1.sys, ‘ ‘ ‘ sib1.conf ” 0, ‘ ‘ ‘ ‘ ‘ ” 0 ‘ ...
✓ G13, Sample 58: : 21m [ dl] (elt rfs _ gnb. sa. band78. fr1. 105. 106.122. 1...
✓ G13, Sample 59:  and ‘ 1.5 ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ 3d – 1 – ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ 1 ‘ … ...
✓ G13, Sample 60: -n-am-rs-eval-3sg 1 #[config] config_line.imsi_idx = 3 #[con...
Generating from Generator 14...
✓ G14, Sample 1:  to get the ngap request: connect() to server: connection re...
✓ G14, Sample 2: , plmn. c : 1827 plmn. c : 95 plmn. c : 1827 file : dl : 228...
✓ G14, Sample 3:  the current running time, the time is : 00101. ” 00101 [ po...
✓ G14, Sample 4:  all the entries.In step 1, the gnb _ app _ config ‘ config....
✓ G14, Sample 5:  be the number of gnb_app_idx and gnb _ gnb _ mac _ idx byte...
✓ G14, Sample 6: , 1422 Sep 13 23:59:54 srs-ran open5gs-udrd[12691]: 02/13 23...
✓ G14, Sample 7:  – 0m [ nr _ rrc ] [ dl ] ( cellid bc614e, ue id 1 rnti 3e04...
✓ G14, Sample 8: /13 23:44:21 srs-ran open5gs-sgwcd[122122]: [pfcp] WARNING: ...
✓ G14, Sample 9:  ( 1 - numelt > 0 && nr _ rrc > 0 && nr _ mac ” / nr _ rrc ”...
✓ G14, Sample 10: . dlopen() : failed, errno( 111 ) ” egtp ” sctp ” conﬁg ” co...
✓ G14, Sample 11:  not only was this a standardized, standardized app, it was ...
✓ G14, Sample 12:  [ 0m # ‘ 1 ; 31m [ hw ] [ rrc ] [ dl ] downlink detection f...
✓ G14, Sample 13: -256 check the integrity of the file.In the file system, the...
✓ G14, Sample 14:  in step 3 [config] file.. /.. / targets / projects / generi...
✓ G14, Sample 15:  13 23 : 44 : 58 srs - ran open5gs - pcfd [ 13098 ] : 02 / 1...
✓ G14, Sample 16:  the app has to have a section with a name that isn't an "IO...
✓ G14, Sample 17:  and ‘ ‘ ‘ ‘ ‘ sctp ‘ sctp ‘ ‘ sctp ‘ ‘ pdw ‘ pd ‘ ‘ csw ‘ p...
✓ G14, Sample 18: .exe – ran open5gs-sgwcd [Feb 13 22:44:40 srs-ran open5gs] [...
✓ G14, Sample 19:  the table configuration file. o. o. d. e. s. c. s. c. d. e....
✓ G14, Sample 20:  the execution server sends a request for a TxBuffer and the...
✓ G14, Sample 21:  1 [ pool - 2 - thread - 1 ] o. o. d. s. s. s. buf[ 8 ] = [ ...
✓ G14, Sample 22:  the algorithm is invalid! … ( … - 1 ) no ent : 255 inst : 2...
✓ G14, Sample 23:  it could have already been performed – as it was. The cell ...
✓ G14, Sample 24:  0m [ ngap ] [ dl ] ( cellid bc614e, ue id 1 rnti 3e04 ) sen...
✓ G14, Sample 25:  10 [ pool - 2 - thread - 1 ] o. o. d. s. s. s. s. filereade...

✓ G14, Sample 26:  and 10 min ago srs-ran open5gs-smf-drd[13099]: [sbi] WARNIN...
✓ G14, Sample 27: .exe /home/oran/openairinterface5g/openair2/RRC/NR/nr_rrc_co...
✓ G14, Sample 28:  - 1 - 8 ) failed! in clone _ pf _ configcommon ( ) / home /...
✓ G14, Sample 29:  - 03 - 18 19 : 00 : 53. 256 ] [ ngap ] [ debug ] remove ng ...
✓ G14, Sample 30: .app.xpi.xpiProviderNullPeriodicUpdateEvent |.. /.. / lib / ...
✓ G14, Sample 31:  ( 0m ‘ 1 ; 31m ” 1 rrc ‘ 0m ” c : cmines [ hw ] request dat...
✓ G14, Sample 32:  at the start of the current session. ( ‘ ‘ ‘ ‘ ‘ ‘ failed ‘...
✓ G14, Sample 33:  and 12.04 – 03 – 21 : 08. 800 ” out of order ” ‘ noaa ‘ pd ...
✓ G14, Sample 34:  nr - threadcreate ( ) : error - / o - du - l2 / src / cm / ...
✓ G14, Sample 35: : 0031PM PDT / 12 May – 03:30PM EDT / 619:30 IST / 9528Km [ ...
✓ G14, Sample 36: . sgcp - ue 1 [.. / src / cm / cm _ inet. c : 169 ] file.. /...
✓ G14, Sample 37:  ( 1 / nr - regen ) failed! in rrc _ rrc _ pd [ 0mcmdline : ...
✓ G14, Sample 38: , while the algorithm is running, the file format (BMP) is n...
✓ G14, Sample 39: . o. d. s. s. s. s. p. c. 519 : s. r. e. d. s. r. c. 619 : s...
✓ G14, Sample 40:  this section to the application config file. CONFIG_SRC_DEB...
✓ G14, Sample 41:  - 1 : 25 srs - ran open5gs - ausfd [ 12900 ] : 02 / 13 / 12...
✓ G14, Sample 42: .app.config.map(u8, UIConfig) FAILUE!In config/app.iniFileEx...
✓ G14, Sample 43: . 1 : ‘ 2 nr _ prach ” : ” failed ‘ srch ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ” ‘...
✓ G14, Sample 44:  this section has been removed. This section has not been de...
✓ G14, Sample 45:  a guest May 13th, 2015 58 Never a guest58Never!tai | [bdf5f...
✓ G14, Sample 46: s_interval : 30 execcheck : error while encoding video data ...
✓ G14, Sample 47:  - 1 [ 0m # ” 0m [ rrc ] [ dl ] [ rrc ] check the UE ID of t...
✓ G14, Sample 48:  or later. Send to serverconfig@localhost:3025#![config] og_...
✓ G14, Sample 49: . 1 : 40 srs - ran open5gs - nssfd [ 1440 ] : 02 / 13 / 12. ...
✓ G14, Sample 50:  ack! = 0xe000# ” 0xe000 – – ” 0m # ” no ssi # ” no … # ” ” ...
✓ G14, Sample 51: .xr - l2 - udrd [ 0 ] (.. / lib / udrd / lib. c : 145 ) feb ...
✓ G14, Sample 52: : 28 Sep 16 22:54:59 srs-ran open5gs-udrd[13363]: 02/13/16 2...
✓ G14, Sample 53:  to encode the ciphertext.UTF-8: the ciphertext has already ...
✓ G14, Sample 54: .exe /opt/oamfranix /home / oran / openairinterface5g / open...
✓ G14, Sample 55:  ( 0m [ ‘ 0m [ hw ] received an e-mail with the format : ue-...
✓ G14, Sample 56:  for the algorithm to reject all values in the buffer. The g...
✓ G14, Sample 57:  [ 0m # ” mnemon ] [ rrc ] [ dl ] sib1 session open ” sib1 s...
✓ G14, Sample 58:  [ 0m [ nas ] o. v. h. r. c. s. i. d. c. a. c. a. cbsclientc...
✓ G14, Sample 59: -ran with the client and it ran.In the debug session, the cl...
✓ G14, Sample 60:  – the length of the sib1 buffer. The length of the sib1 fil...
Generating from Generator 15...
✓ G15, Sample 1:  [ 0m [ nas ] [ ue 0 ] received nas _ downlink _ id ( 1 ), e...
✓ G15, Sample 2: s _ nr _ frs _ nr _ prach _ rrc _ frs _ frx _ ” ‘ ” ‘ ‘ ‘ ‘ ...
✓ G15, Sample 3:  the application was not available. ‘ ‘ 0 ‘ 1 ] failed ‘ ( …...
✓ G15, Sample 4: , 12Feb 13 22:21:24 srs-ran open5gs-seppd[13098]: 02/13 22:2...
✓ G15, Sample 5:  a guest Dec 31st, 2015 17:59:19 srs-ran open5gs-seppd[14928...
✓ G15, Sample 6:  1 sgcrsh – txspf : send tx [ 0 ] request complete [ 0 ] ” s...
✓ G15, Sample 7:  the file ../../targets/PROJECTS/GENERIC-NR-5GC.conf - line ...
✓ G15, Sample 8:  - 03 - 21 : 21 : 21 : 21 : 21 : 21 : 21 : 21 : 21 : 21. 211...
✓ G15, Sample 9: , the algorithm ” ue ” 1 failed!In the section ” ue ” ” valu...
✓ G15, Sample 10: , 1422ASPM: [nas_n2] [debug] Remove NSF registration failure...
✓ G15, Sample 11:  to 1235, line: 2722, ssb_idx_tokens: check integrity in ssb...
✓ G15, Sample 12:  ( 1 - > 0 && nr _ rrc _ idx < nr _ inode > & vr _ celltype ...
✓ G15, Sample 13:  the server is down. Try running /opt/mongodb-xr-west-2/ngap...
✓ G15, Sample 14: , it failed to get the subscription information, and the sub...
✓ G15, Sample 15:  (numSibils=0) failed!In read_du_config_info() /home/oran/op...
✓ G15, Sample 16:  that it is not only to be provided, but to have an interfac...
✓ G15, Sample 17:  0m [ sbi ] [ debug ] file .. /.. /.. / targets / projects /...
✓ G15, Sample 18:  the config file : yaml config _ get, section log _ configva...
✓ G15, Sample 19: -ran open5gs-mfd [13099]: 02/12/12 14:45:35.256: [sbi] WARNI...
✓ G15, Sample 20: s_dyn _ rrc _ pf _ amf _ n2 _ rrc _ config _ rrc _ pf _ n2 _...
✓ G15, Sample 21: . sib1. dl2. client. cbsclient : error[12944]: Error loading...
✓ G15, Sample 22: , the data center configuration file was skipped, the UE thr...
✓ G15, Sample 23:  1 session[ rlc ] [ dl ] ( cellid bc614e, ue id 1 rnti 3e04 ...
✓ G15, Sample 24:  in the section "Options" of the configuration file.In the s...
✓ G15, Sample 25:  1 ) failed! in clone _ rrc _ timezone ‘ 10 ( ) / home / ora...
✓ G15, Sample 26:  with a sib1 ciphering algorithm ‘ 0, with a sib1-encoded bu...
✓ G15, Sample 27:  - 1 : ‘ no data available [ hw ] connect ( ) to 127. 0. 0. ...
✓ G15, Sample 28:  [ 0m ‘ hw ] connect failed : connection refused [ 93 ] / ho...
✓ G15, Sample 29: .exe "C:\Program Files (x86)\Steam\steamapps\common\Counter-...
✓ G15, Sample 30:  12 23:44:54 srs-ran open5gs-bsfd[12882]: 02/13 23:44:54.166...
✓ G15, Sample 31:
[0m#[32m[ACME] SBCS is not supported #[0m[RRC] No SBCS is a...
✓ G15, Sample 32:  the parameters get the bandname of the RTC interface (eg TA...
✓ G15, Sample 33:  [2023-03-21 19:25:54.263] [smf_app] [debug] SBCS Peer is Fa...
✓ G15, Sample 34: 1 _ prach _ sibils _ prach _ prach _ ruic _ synch _ prach _ ...
✓ G15, Sample 35: / ‘ 1. 0 ‘ 0 ‘ ” ‘ ‘ ‘ ‘ 95. 0. ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ” 95. 0 ‘ ...
✓ G15, Sample 36:  and 1133:44 am. [app] WARNING: [1033aa5a-ea30-41ef-9631-93b...
✓ G15, Sample 37: .exe " / o - v - rrc - ldrd " " 2025 - 03 - 19 18 : 25 : 54....
✓ G15, Sample 38: .config.json : [ 922 ] error : failed to assign _ ue idx _ t...
✓ G15, Sample 39:  srs - ran open5gs - pcfd [ 142 ] : 02 / 13 / 2025 : 16. 550...
✓ G15, Sample 40:  sctp sctp.sys: 1607 errno: 500 Fri 13 Oct 16 19:22:30.600: ...
✓ G15, Sample 41:  2 : [ sbi ] warning : failed to initialize ue with ue id 1 ...
✓ G15, Sample 42:  is no longer available. Try it out!
. ‘ 0 ‘ ‘ ‘ 1 is no lon...
✓ G15, Sample 43:  1 : ‘ srs - ran open5gs - seppd [ 12440 ] : 02 / 13 / 10 : ...
✓ G15, Sample 44: : ” 0m [ dl ] [ gnb : gnb _ app ] handle the association fai...
✓ G15, Sample 45:  the data binding was removed.In the config/airinterface.c:2...
✓ G15, Sample 46:  (posix ) : sw error : ent : 255 inst : 255 proc id : 000 fi...
✓ G15, Sample 47:  ( ‘ 0 ‘ ‘ ” – 0 ) ‘ ‘ ‘ ” ” 2e 9 ‘ ” 1 ) failed, errno ( 11...
✓ G15, Sample 48:  the time. (1)The length of the current buffer is not enough...
✓ G15, Sample 49:  0m [ ngap ] [ dl ] ( cellid bc614e, ue id 1 rnti 3e04 ) sen...
✓ G15, Sample 50:  the configuration file. e.g. /etc/ngap/ngap_config.yaml[1]....
✓ G15, Sample 51:  this section] [Exceptions] Cannot create thread ‘ sctp_dru_...
✓ G15, Sample 52:  it has been added to the config file.json : parameters, val...
✓ G15, Sample 53:  the association with ngInet ( ) failed! in read _ sib1 _ nr...
✓ G15, Sample 54: .nodb(CONFIG, ‘ config, ue, band11) FAIL!Exiting executionCM...
✓ G15, Sample 55:  [ 0m [ nr _ rrc ] received registration reject cause : ‘ ” ...
✓ G15, Sample 56:  amf ( nr _ amf ) feb 13 22 : 21 : 21 : 11 srs - ran open5gs...
✓ G15, Sample 57:  to get the gnb_pf_debug value of gNB 8.0: invalid format(8)...
✓ G15, Sample 58: , 1822-03-21 07:59:59.256] [app] [error] Received unsuccessf...
✓ G15, Sample 59: /1/6-thread-1:30am PDT#[0m#[93m[SCTP] Send in request to SCT...
✓ G15, Sample 60: .exe, or mongodb [config] file.. /.. / targets / projects / ...
Generating from Generator 16...
✓ G16, Sample 1:  ausdru-client-id :~ gnb 0xe000-nr-1 gnb _ app ‘ gnb _ appx ...
✓ G16, Sample 2:

numerology : ue [ 0 ] : numerology ( cell id : 1243 ) fail...
✓ G16, Sample 3:  in config/air1.c : 1243ASUS failed: decode_UEI(0x1) /home/o...
✓ G16, Sample 4:  2 ) failed : cminetsacmdline : syntax error ( 2 * sizeof ( ...
✓ G16, Sample 5:  : ‘ ‘ ‘ ‘ 0 ‘ 1 : ” [ srs - ran open5gs ] [ debug ] connect...

✓ G16, Sample 6: , 21 Sep 18 18 21:54:22 srs-ran open5gs-smfd[14976]: 02/19 1...
✓ G16, Sample 7: , 12 August 2015: 21:59:54 srs-ran open5gs-seppd[13098]: 02/...
✓ G16, Sample 8:  that isn't the end of it. Try to connect to the server and ...
✓ G16, Sample 9:  [ 0m # [ 93m [ mac ] ue 0xe000 [ 2a02 # [ 0m [ rrc ] receiv...
✓ G16, Sample 10:  ( 1 - > 0 && nr _ rrc _ rrc _ rnti > 0 && nr _ rrc _ nr _ r...
✓ G16, Sample 11:  the length of the buffer[0m: 8] (NB8) Node error: SubSIDR f...
✓ G16, Sample 12:
 ( 1 / 4 in ‘ 1, 2 ‘ ‘ ‘ ‘ ‘ 0 ) failed! in rx _ rx _ nr _ ...
✓ G16, Sample 13:  at 14:44:25 srs-ran open5gs-udrd[14963]: 02/12/14 21:44:25....
✓ G16, Sample 14:  12 22 : 21 : 21 : 07 srs - ran open5gs - seppd [ 14940 ] : ...
✓ G16, Sample 15:  1 – 5 of 7 – Oct 25 22:54:59 srs-ran open5gs-bsfd[14928]: 0...
✓ G16, Sample 16:  – 0m # ‘ ‘ srs - ran open5gs - scpd [ 14976 ] : [ sbi ] war...
✓ G16, Sample 17:  the buffer is not properly initialized, errno ( 106 ) == - ...
✓ G16, Sample 18: . c : 28prach – retry registration with nrf ( ) error - > sc...
✓ G16, Sample 19: : 23rd June, 2015 11:30:11.736 [sebaceous5g] [amf_app] [debu...
✓ G16, Sample 20:  ackpf[9301] (.. / lib / cm / gnb. sa. band78. fr1. 106prb. ...
✓ G16, Sample 21: /14 23:54:44 srs-ran open5gs-udrd[14928]: 02/14 23:54:44.436...
✓ G16, Sample 22:  a band of saffron-greens (NR-band 6), with 8 bytes of lengt...
✓ G16, Sample 23: .plist file : path / application ‘ config.json file : ‘ opts...
✓ G16, Sample 24:  0m [ nr _ rrc ] [ dl ] ( cellid bc614e, ue id 1 rnti 3e04 )...
✓ G16, Sample 25:  the current state (0xc0a30) could not be created: file ../....
✓ G16, Sample 26:  : ” 0 [ 0m # ‘ 1 ; 31m [ e1ap ] unknown integrity algorithm...
✓ G16, Sample 27: .conf file.bindsym : /opt/bindsym /home / openairinterface5g...
✓ G16, Sample 28:  as a result of a request to the Linux Foundation for a stan...
✓ G16, Sample 29:  [ 0m # ‘ rrc ] [ dl ] [ ue 0 ] starting tx out of order 255...
✓ G16, Sample 30:  – the number of cells in the system (1, 2, 3), ‘ and ‘ ‘ 0 ...
✓ G16, Sample 31: s - lsb - oai | sa | gnb. sa | [ 1825 - 03 - 18 07 : 48 : 59...
✓ G16, Sample 32:  23rd - ‘ : 21 : 21 srs - ran open5gs - smfd [ 13098 ] : 02 ...
✓ G16, Sample 33: , while it was running at the time.CMDLINE: /opt/lib/app.c:2...
✓ G16, Sample 34: , plmnw [ 130 ] : 02 / 13 / 16 srs - ran open5gs - seppd [ 1...
✓ G16, Sample 35:  the config file. /home/oran/openairinterface5g/openair2/con...
✓ G16, Sample 36: , 16 Sep 18 23:53:59 srs-ran open5gs-sgwcd[14976]: 02/17 23:...
✓ G16, Sample 37: -bind - rfsim5 - o- gtpu / openairinterface5g - smfd [ 0 ] [...
✓ G16, Sample 38:  [ 0m # ” gtpu ] ue thread amf _ init aborted for thread ‘ :...
✓ G16, Sample 39: .exe " / -O " ‘ " ‘ rrc ”.shrc " " ”.shrcx " ” ”rrc ”.exe " ...
✓ G16, Sample 40:  - 12 23:59:59 srs-ran open5gs-bsfd[14976]: 02/12 23:59:59.6...
✓ G16, Sample 41: .exe nr - udrd[0m # ”m [93m ” sctp ] connect failed: Connect...
✓ G16, Sample 42:  to be standardized. A value of ‘3 is required to encode all...
✓ G16, Sample 43:  [ 0m # ” 0m [ phy ] init aborted for ue 2.. ” 0m [ hw ] try...
✓ G16, Sample 44:  all the time! (I'm notating it with a sectional cell, notat...
✓ G16, Sample 45: .t.c.o.d.u.u.u.u.i.i.c.u.pl.u.ti.pl.p.ti.pl.c.u.pl.r.pl.r.t....
✓ G16, Sample 46: .exe file.. /.. / targets / projects / generic - nr - 5gc / ...
✓ G16, Sample 47:  to the nr _ prach _ sibils _ ‘ ‘ ‘ ‘ ” ‘ ” ” ” ” ” ” ” ” ” ...
✓ G16, Sample 48: , 12:00:44 srs-ran open5gs-amfd[14976]: 02/13/2015 srs-ran o...
✓ G16, Sample 49:  the configuration file.conf file. /etc/host.aliases.list.i1...
✓ G16, Sample 50:  0m [ nr _ rrc ] [ dl ] ( cellid bc614e, ue id 1 rnti … ) se...
✓ G16, Sample 51:  to the node.ai.ai.u.placement.placementInterface.placementE...
✓ G16, Sample 52:  - 1 [ 0m # ‘ ‘ 0m # ‘ ‘ ‘ … ] ue [ hw ] send Tx request for...
✓ G16, Sample 53:  12:44:53 srs-ran open5gs-smfd[14963]: 02/12/14 13:59:45.777...
✓ G16, Sample 54:  for a period of time to notify the client and send the requ...
✓ G16, Sample 55: :00PM PDT – 1:00PM EDT (3025 UTC) 08/10/15 – 07:00PM PDT / 7...
✓ G16, Sample 56:  the association (MAC) has been created.MAC ID : 4GPP : ‘ 0M...
✓ G16, Sample 57:  28 [displayText] (c) Reauthorization of the NRDC for the 1s...
✓ G16, Sample 58:  amf _ n2 _ rrc _ band : 4 numelt : 1 numeltas : 0 errcode :...
✓ G16, Sample 59:  to release 0.9.0-rc1 # ‘ ‘ ‘ 0.9.0-rc2 # ” ‘ ” ” ” ” … ‘ ‘ ...
✓ G16, Sample 60: : mnc_rval_idx : 11 [ sctp ] unknown encoders : rlc_addr, sc...
Generating from Generator 17...
✓ G17, Sample 1: . o. d. e. s. d. s. s. i. s. s. p. e. s. c. r. e. s. s. s. r...
✓ G17, Sample 2: : 16 srs-ran open5gs-drd-amfd[13099]: 02/13/15 – 14:44. 835:...
✓ G17, Sample 3:

config_info : error [ 8 ] : syntax error [ 8 ] (.. / lib /...
✓ G17, Sample 4:  : [ 0m # ‘ 1 ; 31m [ rrc ] unknown ciphering algorithm ” ce...
✓ G17, Sample 5:  - 0m [ ngap ] [ dl ] ( cellid bc614e, ue id 1 rnti 1 – 1 ) ...
✓ G17, Sample 6: , 2015-02-17 19:25:14.256] [ngap] [debug] Received Authentic...
✓ G17, Sample 7:  this section.In this section, a variable name is provided, ...
✓ G17, Sample 8:  ( enc _ rval. encoded > 0 & & enc _ rval. encoded < = max _...
✓ G17, Sample 9:  - 1631 | [pfcp] [debug] [pfcp client pfcp handshake failure...
✓ G17, Sample 10:  12hrs ‘ – 12m ‘ 12m ‘ ‘ nr downlink ‘ downlink – ‘ downlink...
✓ G17, Sample 11: : 08/13 19:19:16.363] [app] [debug] Update UE State Registra...
✓ G17, Sample 12:  in libconfig_json : line : 466 ue 0xe000 [.. / lib / odu - ...
✓ G17, Sample 13:  the value of nr _ rval.length > 0 & & & nr _ rval.length < ...
✓ G17, Sample 14:  the system failed! – /home/oran/openairinterface5g/openair2...
✓ G17, Sample 15: , 2025 ‘ 10:00:59.263] [amf_app] [debug] Update UE Registrat...
✓ G17, Sample 16: -bind-pfcconsole-handler: assertion (1==0) failed handler(CO...
✓ G17, Sample 17:  to 0xe000c0 … / lib / o - nf - sm. c : 255 need to have a t...
✓ G17, Sample 18:  12 22 : 21 : 14 srs - ran open5gs - pcfd [ 14976 ] : 02 / 1...
✓ G17, Sample 19: .app.xm[config]: file.. /.. / targets / projects / generic -...
✓ G17, Sample 20:  ack [ 1696 ] : 02 / 12 / 17 / 17. 9. 7. 13 : [ sbi ] warnin...
✓ G17, Sample 21:  – the band was already in the band – 0 – ‘ ‘ 0 (cello – 163...
✓ G17, Sample 22:  the session.CMDLINE: mnemonaldswim30clientconfigmap : error...
✓ G17, Sample 23: , 2025. The State of Washington is setting out to create an ...
✓ G17, Sample 24:  the association with the amf (cellID 8, gnb _ sa_usd[17002]...
✓ G17, Sample 25:  1 srs - ran open5gs - l2 - smfd [ 142 ] : 02 / 13 / 17 ‘ ‘ ...
✓ G17, Sample 26: -bind-rx5g-app [13028] (debug) received PDO request for PDO ...
✓ G17, Sample 27:  is the standardized SIB (sbi256): value is the encoded int ...
✓ G17, Sample 28: -1-7 [dca-src-pfcp] ogs-pfcp-common: path=/opt/gcm/oc_rrc_co...
✓ G17, Sample 29: : 02 / 13 / 18 — 19:44:53. 753 ] [ ngap ] [ debug ] send buf...
✓ G17, Sample 30:  the file system information received. [.. /.. / targets / p...
✓ G17, Sample 31:  the cell is deleted, the cell id is not provided, and no ce...
✓ G17, Sample 32:  the current value, the current time is the current period. ...
✓ G17, Sample 33: /2.0/NR_NR_RRC_DEBUG] PLATFORM_RRC_DEBUG: PLATFORM_RRC_DEBUG...
✓ G17, Sample 34:  the session to complete.The session id is: 0x1F200000 and s...
✓ G17, Sample 35:  - 1 [ gtpu ] unknown ciphering algorithm ” 0xe000 ” [ hw ] ...
✓ G17, Sample 36:  - 03 - 18 19 : 48 : 59. 256 ] [ amf _ n2 ] [ debug ] Remove...
✓ G17, Sample 37:  a file : filename : / app - config / application ‘ config. ...
✓ G17, Sample 38:  : ‘ 0x7f1933c042e0 [ sbi ] unknown sbi format d [ hw ] tryi...
✓ G17, Sample 39:  to SCTP interface (sctp): Received SCTP request from client...
✓ G17, Sample 40: -ran open5gs-scpd-scp-nbccd [21098] (...) no data received f...
✓ G17, Sample 41:  the SSA band with the address ffffffff22aa5e0 (CONNECT TAC)...
✓ G17, Sample 42:  [ 0m [ sctp ] connect failed : connection refused [ 0m [ nr...
✓ G17, Sample 43:  the number of projects ran, all projects performed. The pro...
✓ G17, Sample 44: : 22 Oct – 19:06:19 srs-ran open5gs-sgwcd[13098]: 02/19/2015...
✓ G17, Sample 45:  the cell parameters: cell_idx : 6, cell_name : 'MMORPG', of...

✓ G17, Sample 46:  12:35:54 srs-ran open5gs-amfd[14922]: 02/12/14 19:04:03.256...
✓ G17, Sample 47: .srs-ran open5gs-cmogs-rlc-xrlc2fs[13691]: 02/13/12 16:59:25...
✓ G17, Sample 48:  with a buffer of 256 bytes. Subsequent buffer initializatio...
✓ G17, Sample 49:  28 23 : 44 : 59 srs - ran open5gs - udrd [ 14976 ] : 02 / 1...
✓ G17, Sample 50:  at the time of registration and received it. (Februy 23rd, ...
✓ G17, Sample 51:  and ‘ gtpu_idx : 16 ciphering priority : 2 ciphering algori...
✓ G17, Sample 52:  (posix ) - > max ( 4 * ( table - > idx * 2 - > max ( nr _ t...
✓ G17, Sample 53:  is not available to all gnb 0. 1. 1 is not available. 2 is ...
✓ G17, Sample 54:  the numerator and denominator values in the cell. Parameter...
✓ G17, Sample 55:  to get the rrc_nr_rrc_nr and rrc_nr_nr_bandwidth values. 0m...
✓ G17, Sample 56:  a file imd[..rp] o.o.d.b.c.t.o.u.f.s.r.c.o.i.d.c.x.e.p.x.rd...
✓ G17, Sample 57: .scm: error while encoding file[-1][amfd[HW] Trying to conne...
✓ G17, Sample 58:  that the cell number in the json_reader() format is out of ...
✓ G17, Sample 59:  and the parameters, mRxInitSrc() : fails: error(3), port(98...
✓ G17, Sample 60:  a thread ‘ threadcreate ( ) failed: error while encoding vi...
Generating from Generator 18...
✓ G18, Sample 1:  [ 0m # ‘ 0m [ nr _ rrc ] received [ ue 0 ] releasing ue 1 #...
✓ G18, Sample 2:

# ” 0m [ o - r - ld [ nr _ rrc ] ( ) connects ” time : ‘ 0...
✓ G18, Sample 3: .app.route(.get, ‘null, ”cell) succeeded!In cloneAssertionEx...
✓ G18, Sample 4:  the numerator and denominator of sizeof(nr_bandtable) of th...
✓ G18, Sample 5:  the app has to have the mnemonics.conf file in the app.json...
✓ G18, Sample 6:  the periodicity check is not performed, the time periodicit...
✓ G18, Sample 7: .SRC – 12 Oct: 44:54:08 srs-ran open5gs-seppd[12976]: [sepp]...
✓ G18, Sample 8:  10 23 : 44 : 48 srs - ran open5gs - pcfd [ 14976 ] : 02 / 1...
✓ G18, Sample 9: -de-l2-x-ms-pfcp-cm] [error] Could not open config/udev/cm_i...
✓ G18, Sample 10:  1 [pool-1-thread-1] o.o.d.p.g.c.u.v.s.r.r.a.t.i.d.r.m.a.s.r...
✓ G18, Sample 11:  the time, the algorithm could have skipped execution and th...
✓ G18, Sample 12:  22:44:24 srs-ran open5gs-scpd[12430]: [sbi] WARNING: [14100...
✓ G18, Sample 13: .exe filename : /opt/pfcp -u / nr - 3 ~ /.. /.. / targets / ...
✓ G18, Sample 14: -ran.gson[NR_APP] /home/oran/openairinterface5g/openair2/NR/...
✓ G18, Sample 15:  (posix - > 0 && posix < ( sizeof(buf)) / sizeof(r_i)) faile...
✓ G18, Sample 16:  is the time for the registration period, the subscription p...
✓ G18, Sample 17:  12 22:54:21 srs-ran open5gs-udrd[13002]: 02/12 22:54:21.210...
✓ G18, Sample 18:  a thread pooling... please read the thread execution parame...
✓ G18, Sample 19:  be a "buffer" in file or directory ‘ ” / ‘ /home / oran / o...
✓ G18, Sample 20:  the gnb.conf file. Parameters: gnb_idx - number of bytes to...
✓ G18, Sample 21:  sctp : request release after ul failure timer ‘ 0pi ”. iau ...
✓ G18, Sample 22:  28 [displayText] (--UTIL_APP) ” 00000 ” 00000 ” ” 16 bytes ...
✓ G18, Sample 23:  sctp_bindx() Failed: ogs_pf_app (1) failed! ogs_pf_config_g...
✓ G18, Sample 24:  all dl_rrc_idx = 16 ciphertext[CONFIG] /home/oran/openairin...
✓ G18, Sample 25: : 22m [ pool - 2 - thread - 1 ] o. o. d. s. s. s. s. filerea...
✓ G18, Sample 26:  sib1. imdb | config | gnb. sa. band78. fr1. 106prb. usrpb21...
✓ G18, Sample 27:  a client sends a message informing the client that a check ...
✓ G18, Sample 28:

Init failed!In rscpu_config_scanned :could not get scmnap_...
✓ G18, Sample 29:  ack [ 0m # ” 0m # ” hw ] connect : ‘ received connect reque...
✓ G18, Sample 30:  with mnc_rval_idx : 2 number of UL values in section "secur...
✓ G18, Sample 31:  the system has been configured properly.

In step 1 the sys...
✓ G18, Sample 32:  the client connects, the thread is created: threadcreate ( ...
✓ G18, Sample 33:  in the config file. /etc/host.aliases.conf:line 743Config f...
✓ G18, Sample 34:  amf _ in rrc _ nr _ config. c : 843need to have a nr _ conf...
✓ G18, Sample 35:  and ‘ ‘ g ‘ ‘ ‘ ‘ c ‘ ‘ ‘ down ‘ ” down ” ” ” ” ” ‘ ‘ ‘ ‘ ‘...
✓ G18, Sample 36: .plist file.. /.. /.. / targets / projects / generic - nr - ...
✓ G18, Sample 37:  the config file: line: 543 execcheck: Registration failed a...
✓ G18, Sample 38:  that I am the bearer of this message.I am the bearer of a m...
✓ G18, Sample 39:  1 time srs-ran open5gs-pfd[14963]: 02/12/15 srs-ran open5gs...
✓ G18, Sample 40: .exe – file .. /.. / targets / projects / generic - nr - 5gc...
✓ G18, Sample 41:  ( 0m [ ENCS ] [ amf _ n2 ] send buffer release request for ...
✓ G18, Sample 42:  1073 | 00:54:02.736 | [ngap] [debug] Send notification of r...
✓ G18, Sample 43:  is the result of a buffer transfer, and the length in the b...
✓ G18, Sample 44: . plmn [ 0m # ‘ ‘ 6 ] [ hw ] sctp shutdown event ” 0m ” hw ”...
✓ G18, Sample 45:  12 22 : 21 : 12 srs - ran open5gs - udrd [ 12882 ] : 02 / 1...
✓ G18, Sample 46:  1.0 [CONFIG] config_check_bandwidth: num_bandwidth_sextuple...
✓ G18, Sample 47:  [ 1 ; 31m [ nas ] received registration reject cause : / o ...
✓ G18, Sample 48:  all services ‘ enabled ‘ all services ‘ received no informa...
✓ G18, Sample 49:  the value of the rval.length > 0x1F8In this instance, the r...
✓ G18, Sample 50:  13 23:54:48 srs-ran open5gs-amfd[14963]: 02/13 23:54:48.691...
✓ G18, Sample 51: .o.o.d.b.c.o.d.s.g.r.o.d.c.r.o.d.e.e.f.g.g.gsa.gsa.gs.gssa.b...
✓ G18, Sample 52:  it is time to get your ass out of the way. (1) ” 1, 2, 3: ‘...
✓ G18, Sample 53:  [ 0m # ” 0m [ nas ] ” nas _ get data # ” 0m [ …. / …. rrc ]...
✓ G18, Sample 54:  [ 0m [ nas ] received nas _ fr1 message [ ue 1 ] ( enc _ rv...
✓ G18, Sample 55: . plmn (src / cm / cm _ inet. c line : 28 ) feb 13 23 : 59 :...
✓ G18, Sample 56:  the SBI (7) section received a request for a standardized s...
✓ G18, Sample 57:  1 / 10 srs - ran open5gs - pcfd [ 14922 ] : 02 / 13 / 2025 ...
✓ G18, Sample 58:  the band was down, I ran out of time to find a band to chec...
✓ G18, Sample 59:  of the subscription period; the subscription period end, 14...
✓ G18, Sample 60:  – after the session. A session started. Session ended. A se...
Generating from Generator 19...
✓ G19, Sample 1:  aaa5 [ o - rrc ] ( ) connect ( ) to ‘ ‘ ‘ ‘ ” 1111 : ‘ ” fa...
✓ G19, Sample 2:  ( nr - ue [ 1 ] : send rrc _ nr _ phy _ info transfer [ 2 b...
✓ G19, Sample 3: s: ssb - seppd [ 12900 ] (.. / lib / ssb - sm. c : 169 ) sep...
✓ G19, Sample 4:  22: ‘ 1644:25 srs-ran open5gs-bsfd[13363]: 02/22/1544:25.26...
✓ G19, Sample 5: /sctp/NR_NR_CONFIG.c:543Exiting execution while encoding fil...
✓ G19, Sample 6: , 0m[UE1; 31m[PHY] Received authentication failure while try...
✓ G19, Sample 7:  23:59:54 srs-ran open5gs-bsfd[12422]: 02/13 19:59:54.777: [...
✓ G19, Sample 8:  at the time.In order to start the file sync, a CUF file has...
✓ G19, Sample 9: [0m#[93m[MAC] Update UE Session State#[0m[SCTP] Received UE ...
✓ G19, Sample 10:  the UE is initialized with the UE ID 1, the UE ID 2, and th...
✓ G19, Sample 11: .rval.cell.cellList.map(cellAval, cellBval.cellIDx = 0) fail...
✓ G19, Sample 12:  - 03 - 17 18 : 59 : 48. 298 ] [ ngap ] [ debug ] Received T...
✓ G19, Sample 13: .exe /home/oran/openairinterface5g/openair2/RRC/NR/NR_NR_APP...
✓ G19, Sample 14:  0m [ ngap ] [ ue 2a21 : [ sbi ] warning : failed to connect...
✓ G19, Sample 15:  - 03 - 18 19 : 59 : 48. 211 ] [ nr _ rrc ] [ debug ] send s...
✓ G19, Sample 16:  ( 1 - ‘ ‘ 0 ‘ ‘ ‘ numelt > 0 ) failed! in read _ du ‘ info ...
✓ G19, Sample 17:  [ 0m [ nr _ rrc ] received handshake success [ bdf8 ] (.. /...
✓ G19, Sample 18: .m. PDT.SBI.amfd[10600]:SBI is releasing the PDU (Periodicit...
✓ G19, Sample 19:  the configuration file. /etc/nginx/conf.yaml file.. /. /. /...
✓ G19, Sample 20: 1 ( ‘ 0m [ sctp ] retry registration with nrf ( ) /home / or...
✓ G19, Sample 21: .bindx() failed, errno(106) /home/oran/openairinterface5g/op...
✓ G19, Sample 22:  1 [ sbi ] unknown sbi file.. /.. /.. / targets / projects /...
✓ G19, Sample 23:  ( 1 - ‘ ” 0 ‘ ‘ ‘ ‘ 2 ” 0 ‘ 1 ” 0 ) failed! in read _ du ‘ ...
✓ G19, Sample 24:  ( 1 - ‘ ‘ 2 ) failed! in rx _ gnb _ app _ ru ( ) / home / o...
✓ G19, Sample 25:  [ 0m # ‘ 0m [ rrc ] [ dl ] check the integrity of the rrc_i...

✓ G19, Sample 26: , ‘ 1 : ‘ ‘ down, ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ ‘ down ‘ ‘ ‘ ‘ ‘ down ‘ ...
✓ G19, Sample 27:  for the current session.ERROR! Failed to initialize PDO (.....
✓ G19, Sample 28: -dru-rs-3g-du-smf-sc-cmfs' centralized directory /etc/rfc14s...
✓ G19, Sample 29:  is not standardized in the syntax, or in the syntaxes for t...
✓ G19, Sample 30:  this section.CMDLINE: dl_nr_esc_intval:cell_id 1378 cells: ...
✓ G19, Sample 31: -ran : 0030 : 44 srs - ran open5gs - bsfd [ 12976 ] : 02 / 1...
✓ G19, Sample 32:  - 12 21 : 21 : 25 srs - ran open5gs - bsfd [ 14940 ] : 02 /...
✓ G19, Sample 33: , nr _ rrc _ prach _ prach _ ruised _ ue _ imd _ imd _ in _ ...
✓ G19, Sample 34: . o. o. d. c. s. i. e. f. s. r. e. g. u. pld. ue. ue. pld. u...
✓ G19, Sample 35:  the problem! ‘ ‘ ” 0 ‘ ‘ ‘ ” ( 1 ‘ ‘ ‘ ‘ 1 ) is not the val...
✓ G19, Sample 36:  2 o'clock. ‘ sctp : ‘ … sctp shutdown ” ” 0x1 parameters : ...
✓ G19, Sample 37:  [ 0m # ” 00m [ pfcp ] connect : ” failed ” port 7777 # ” 00...
✓ G19, Sample 38: -1305-2100-03-21 00:00:00. 944 ] [ amf _ n2 ] [ debug ] Hand...
✓ G19, Sample 39:  - 02 - 17 19 : 58 : 59. 256 ] [ amf _ n1 ] [ debug ] connec...
✓ G19, Sample 40:  and ‘ 0 rrc ‘ - ldrd[1303]: ” error ” rrc ” e1fa440 ” cdfd ...
✓ G19, Sample 41: -bind-interface 0xe000 - > nr - thread - 1 # ‘ no-inter ” bi...
✓ G19, Sample 42:  as a generic ciphering algorithm (EGAP) is provided.Exiting...
✓ G19, Sample 43: , 03 22 : 21 : 02 srs - ran open5gs - seppd [ 14940 ] : 02 /...
✓ G19, Sample 44:  [ 0m [ dl ] ( cellid bc614e, ue id 1 rnti … ) sends … errdx...
✓ G19, Sample 45:  ( posix ) : sw error : ent : 255 inst : 255 proc id : 000 f...
✓ G19, Sample 46:  of the periodicity ( 0, 1, ‘ 0 ) ” failed!In read_du_cell_i...
✓ G19, Sample 47:  and ‘ ‘ ‘ ‘ ‘ ‘ ‘ 1: ‘ failed to initialize ue with mnc _ i...
✓ G19, Sample 48:  in section 1243: [sbi] WARNING: [7] Failed to connect to 12...
✓ G19, Sample 49:  1 : 22 srs - ran open5gs - pcfd [ 12427 ] : 02 / 13 / 2025 ...
✓ G19, Sample 50:  ( 0m [ nr _ rrc ] [ b : ue 0 ] received ue [ mnc _ mnc _ id...
✓ G19, Sample 51:  amf _ in _ ru [ 3 ] ( ) nef _ rrc _ gnb. sa. c : 2722 asn1 ...
✓ G19, Sample 52:  with a TxgSBtgID 8 and a RATename "security-app" /home/oran...
✓ G19, Sample 53:  the algorithm ran out of "duo" (0) and the bandpass algorit...
✓ G19, Sample 54:  the bandai sends the message and the rx sends out the relea...
✓ G19, Sample 55:  ( ‘ 0mc1 ) failed! in rx _ nr _ prach _ ru ( ) / home / ora...
✓ G19, Sample 56:  aryx2[NR_ADDR] ” 1 failed, errno 93 [111m [SCTP] unknown au...
✓ G19, Sample 57:  be added - yodom - pcfd [ 13098 ] : 02 / 13 / 2025 : 00 : 5...
✓ G19, Sample 58:  a guest Oct 17th, 2015 166 Never a guest166Never

Not a mem...
✓ G19, Sample 59:  the current thread.numelt > 0, threadnum > 0 (.. / lib / gs...
✓ G19, Sample 60:  0m [ dl ] ssi2 [ 1 ] remove nrf ( ) feb 13 23 : 53 : 54 : 5...
Generating from Generator 20...
✓ G20, Sample 1:  aaa5 [ 1] o. o. d. s. s. s. c. 99 ‘cell. s. r. a. c. 99 ‘ce...
✓ G20, Sample 2:  ausdicated services.service :[PHY] Failed to initialize aut...
✓ G20, Sample 3:  the band has not been properly configured, the band informa...
✓ G20, Sample 4:  the section of the ERP that targets the ERP message encodin...
✓ G20, Sample 5:  the app is not available on your local computer, open the ‘...
✓ G20, Sample 6:  the configuration file. /etc/host.aliases: affinity_list = ...
✓ G20, Sample 7:  to connect. o. d. e. h. s. s. r. s. s. c. c. i. e. o. o. d....
✓ G20, Sample 8: -93-11 19:59:44.800: [sbi] WARNING: [1499152a-ea30-41ef-8173...
✓ G20, Sample 9:  the band has been available for 5 years, with a band of 10,...
✓ G20, Sample 10: , o. o. d. s. s. s. c. i. cbsclientconfigmap : error loading...
✓ G20, Sample 11:  a guest Dec 13rd, 2015 95 Never a guest95Never[16014] : [sb...
✓ G20, Sample 12: .targets: [1;31m[ACMDLINE:m[MAC] Received authentication rej...
✓ G20, Sample 13:  all the nr. parameters have been standardized. Parameters :...
✓ G20, Sample 14:  ack [ 20898 ] : 02 / 13 / 12 18 : 35. 600 : [ app ] warning...
✓ G20, Sample 15:  the band provided an AEGI, SSI, PDU, PDU ID, UE ID, UE UE S...
✓ G20, Sample 16:  (posix) / home / oran / openairinterface5g / openair2 / rrc...
✓ G20, Sample 17:  to get the file format: gnb _ app _ info ” 00000-101m# ” 00...
✓ G20, Sample 18: .nodb[NR_APP] 00000 ” 00101 failed, errno 9544[SCTP] sctp_bi...
✓ G20, Sample 19:  to get the data binding json_idx[0].val_list[0].val_type = ...
✓ G20, Sample 20:  – 8 p.m. – 7 p.m. – 12 p.m. – 12 noon (PDT) – No band infor...
✓ G20, Sample 21:  ( 2 * rngi ) / o. c : 36 wrong value for ue variable / nr (...
✓ G20, Sample 22:  at nr - 1 : 31 srs - ran open5gs - pcfd [ 14922 ] : 02 / 12...
✓ G20, Sample 23:  the client connects, it sends the requested data to the ser...
✓ G20, Sample 24:  and 13 May, 2017 07:54:21.790] [amf_n2] [error] ogs_app_duc...
✓ G20, Sample 25:  in 0m [ ngap ] [ dl ] sctp_encoded " : ciphertext " " " val...
✓ G20, Sample 26: . The cell is configured to receive the data transfer reques...
✓ G20, Sample 27: : 16minutesSIB1: Error loading SIB configuration file: /etc/...
✓ G20, Sample 28:  – ‘ 50 min ‘ 4 rrc ( ‘ ‘ ‘ ‘ cell ” ) ran out of bandwidth ...
✓ G20, Sample 29: s-ran open5gs-udrd [10900]: 02/12/2015 ssb - ran open5gs-udr...
✓ G20, Sample 30:  [ 0m # [ 93m [ mac ] ue threadcreate ( ) for task _ rrc _ g...
✓ G20, Sample 31:  as a result of the algorithm 'd3dc' in section 'debug' of t...
✓ G20, Sample 32: : 19 22 : 21 : 17 srs - ran open5gs - udrd [ 142296 ] : 02 /...
✓ G20, Sample 33: .d[1271]: [sbi] WARNING: Received unsuccessful result for UE...
✓ G20, Sample 34:  1 / 10. ‘ ‘ ‘ … ‘ ‘ … … ” 0. 95 ‘ ‘ ‘ … ” 0. 93 ” ‘ … ‘ 95 ...
✓ G20, Sample 35:  1 - 5 [ mongodb : / / - rrc ] o. o. d. s. c. c. filereader ...
✓ G20, Sample 36: .conf file.. /.. /.. / targets / projects / generic - nr - 5...
✓ G20, Sample 37: , the system was running amf_rpi_pkt _applicATION_INDEX fail...
✓ G20, Sample 38: , 12 Oct 18 19:21:08 srs-ran open5gs-udrd[13098]: 02/12/18 1...
✓ G20, Sample 39: -03-19 18:21:22.440] [nas_app] [debug] Create subscription, ...
✓ G20, Sample 40:  a guest Sep 28th, 2014 99 Never a guest99Never

Not a membe...
✓ G20, Sample 41:  the global standardized standardized format has been standa...
✓ G20, Sample 42:  in order to have a standardized algorithm available, the se...
✓ G20, Sample 43:  0m [ ngap ] [ dl ] ( cellid bc614e, ue id 1 rnti 1 rnti 2aa...
✓ G20, Sample 44:  the current file... /.. / targets / projects / generic - nr...
✓ G20, Sample 45:  [ 93 ] : o. o. d. d. e. d. c. s. s. p. h. c. p. r. e. c. a....
✓ G20, Sample 46:  a soft-press release!Download the code from the release pag...
✓ G20, Sample 47:

#[0m#[93m[PHY] [UE 0] Received failure result for pdu_rrc_...
✓ G20, Sample 48:  with gtpu_config_info : priority : 5, thread : 8 , buffer :...
✓ G20, Sample 49:  ( 1 / 2 ; 31 srs - ran open5gs - pcfd [ 124 ] : 02 / 13 / 2...
✓ G20, Sample 50:  all the time. If the stream is deleted, the thread is delet...
✓ G20, Sample 51: .net2 /usr/src / cm / cm _ application ‘ ‘ cm _ prach _ ‘.c ...
✓ G20, Sample 52:  be added. ”[0m#[99m[NGAP] Received an error while encoding ...
✓ G20, Sample 53:  this is not a problem, as the file system isn't geared towa...
✓ G20, Sample 54:  the bandai, a common thread in the home-bandai system, is t...
✓ G20, Sample 55:  - 03-03 16 19:00:53.800] [amf_app] [debug] Send notificatio...
✓ G20, Sample 56:  [CONFIG] config_check_bam_band: value not supported for ogs...
✓ G20, Sample 57:  (posix_idx = 0) failed!In clone_pdu_cell_info() /home/oran/...
✓ G20, Sample 58:  - 0x7f 00 [ sbi ] [ dl ] ue 2aa0a0 : [ 7 ] error : failed t...
✓ G20, Sample 59:  a client connects, the client sends an SMS (3 bytes) inform...
✓ G20, Sample 60:  with the cell id - 1 (1). Create association with cell id -...

✅ Saved 1200 samples to inference-data-new.csv

In [5]:
import pandas as pd

# Group outputs by generator index
gen_ids = []
texts = []

for g_idx in range(K):
    for i in range(num_samples_per_gen):
        idx = g_idx * num_samples_per_gen + i
        gen_ids.append(f"G{g_idx + 1}")
        texts.append(decoded_outputs[idx])

# Create DataFrame with generator ID
df = pd.DataFrame({
    "Generator": gen_ids,
    "Synthetic Fault Log": texts
})

# Save to CSV
df.to_csv("synthetic_fault_logs_by_generator-12k.csv", index=False)
print("✅ Saved to synthetic_fault_logs_by_generator-12k.csv")

✅ Saved to synthetic_fault_logs_by_generator.csv

In [1]:
import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from rouge import Rouge

# Load data with generator column
df_fake = pd.read_csv("gmm_inference_evaluation.csv")
fake_logs = df_fake["Synthetic Fault Log"].dropna().astype(str).tolist()
generator_ids = df_fake["Generator"].tolist()

# Load real logs
df_real = pd.read_excel("fault-logs-o-ran-350.xls")
real_logs = df_real["Fault Description"].dropna().astype(str).tolist()

# Models
embedder = SentenceTransformer("all-MiniLM-L6-v2")
rouge = Rouge()
smoothie = SmoothingFunction().method1

# Evaluation records
records = []

for i, fake in enumerate(fake_logs):
    fake_emb = embedder.encode([fake])
    real_embs = embedder.encode(real_logs)
    sims = cosine_similarity(fake_emb, real_embs)[0]
    best_idx = sims.argmax()
    ref = real_logs[best_idx]

    # BLEU & ROUGE
    bleu = sentence_bleu([ref.split()], fake.split(), smoothing_function=smoothie)
    rouge_score = rouge.get_scores(fake, ref)[0]['rouge-l']['f']
    cosine_sim = sims[best_idx]

    records.append({
        "Generator": generator_ids[i],
        "Fake Log": fake,
        "Best Match Real Log": ref,
        "BLEU": bleu,
        "ROUGE_L_F1": rouge_score,
        "Cosine Similarity": cosine_sim
    })

# Save detailed evaluation
results_df = pd.DataFrame(records)
results_df.to_csv("synthetic_fault_log_eval_detailed.csv", index=False)

# Summary metrics per generator
summary_df = results_df.groupby("Generator")[["BLEU", "ROUGE_L_F1", "Cosine Similarity"]].mean()
summary_df.reset_index(inplace=True)
summary_df.to_csv("evaluation_metrics_by_generator.csv", index=False)

print("✅ Evaluation complete. Metrics saved to:")
print("- synthetic_fault_log_eval_detailed.csv")
print("- evaluation_metrics_by_generator.csv")

KeyError: 'Generator'